// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
#include "OneNativeSecureFieldShadowNode.h"

namespace facebook::react {
extern const char OneNativeSecureFieldComponentName[] = "OneNativeSecureField";
}
