import type { FormProps, HostProps, MenuProps, PopoverProps, SectionProps, SheetProps, SlotProps, TabProps, TabsProps } from './types';
declare function Tabs(_props: TabsProps): never;
declare function Tab(_props: TabProps): never;
declare function Menu(_props: MenuProps): never;
declare function Sheet(_props: SheetProps): never;
declare function Popover(_props: PopoverProps): never;
declare function Host(_props: HostProps): never;
declare function Form(_props: FormProps): never;
declare function Section(_props: SectionProps): never;
declare function Slot(_props: SlotProps): never;
export declare const Swift: {
    Picker: (_props: import("./types").PickerProps) => never;
    DatePicker: (_props: import("./types").DatePickerProps) => never;
    ColorPicker: (_props: import("./types").ColorPickerProps) => never;
    Toggle: (_props: import("./types").ToggleProps) => never;
    Slider: (_props: import("./types").SliderProps) => never;
    Stepper: (_props: import("./types").StepperProps) => never;
    Text: (_props: import("./types").TextProps) => never;
    Label: (_props: import("./types").LabelProps) => never;
    Button: (_props: import("./types").ButtonProps) => never;
    ProgressView: (_props: import("./types").ProgressViewProps) => never;
    Gauge: (_props: import("./types").GaugeProps) => never;
    Image: (_props: import("./types").ImageProps) => never;
    VideoPlayer: (_props: import("./types").VideoPlayerProps) => never;
    Map: (_props: import("./types").MapProps) => never;
    TextField: (_props: import("./types").TextFieldProps) => never;
    SecureField: (_props: import("./types").SecureFieldProps) => never;
    Alert: (_props: import("./types").AlertProps) => never;
    ConfirmationDialog: (_props: import("./types").ConfirmationDialogProps) => never;
    QuickLook: (_props: import("./types").QuickLookProps) => never;
    Tabs: typeof Tabs;
    Tab: typeof Tab;
    Menu: typeof Menu;
    Sheet: typeof Sheet;
    Popover: typeof Popover;
    Host: typeof Host;
    Form: typeof Form;
    Section: typeof Section;
    Slot: typeof Slot;
};
export type * from './types';
//# sourceMappingURL=unsupported.d.ts.map