import { Auth, Browser as NativeBrowser, Widgets, LiveActivities, LocalAuthentication, ProtectedStore, Location, FileSystem, Audio, CameraView, Share, Open, PhotoLibrary, MapServices, AppTracking, AppIcon, ScreenOrientation, ScreenCapture, Purchases, ImageManipulator, Device, Motion, DeviceAttestation, Contacts, Calendar, WidgetUI, Clipboard as NativeClipboard, AppInfo, Database, Compose, Fonts, DocumentPicker, Haptics, ImagePicker, LaunchScreen, MenuAction, Menu as NativeMenu, ContextMenu as NativeContextMenu, Notifications, Network as NativeNetwork, SecureStore as NativeSecureStore, Speech as NativeSpeech, Updates as NativeUpdates, SplitView, Swift, TextInput, ToolbarHost, ToolbarItem, UI as NativeUI, ReservedRegions, ZoomTransitionAlignmentRectDetector, ZoomTransitionEnabler, ZoomTransitionSource, type ColorType } from './platform';
import { SafeAreaProvider, SafeAreaView, initialWindowMetrics } from './safe-area-context';
export type OnePlatform = 'web' | 'ios' | 'android' | 'rnx';
export type OneIOS = typeof Swift & {
    readonly Widgets: typeof Widgets;
    readonly LiveActivities: typeof LiveActivities;
    readonly WidgetUI: typeof WidgetUI;
    readonly LocalAuthentication: typeof LocalAuthentication;
    readonly ProtectedStore: typeof ProtectedStore;
    readonly Location: typeof Location;
    readonly FileSystem: typeof FileSystem;
    readonly Audio: typeof Audio;
    readonly CameraView: typeof CameraView;
    readonly Share: typeof Share;
    readonly PhotoLibrary: typeof PhotoLibrary;
    readonly MapServices: typeof MapServices;
    readonly AppTracking: typeof AppTracking;
    readonly AppIcon: typeof AppIcon;
    readonly ScreenOrientation: typeof ScreenOrientation;
    readonly ScreenCapture: typeof ScreenCapture;
    readonly Purchases: typeof Purchases;
    readonly ImageManipulator: typeof ImageManipulator;
    readonly Device: typeof Device;
    readonly Motion: typeof Motion;
    readonly DeviceAttestation: typeof DeviceAttestation;
    readonly Contacts: typeof Contacts;
    readonly Calendar: typeof Calendar;
    readonly Color: ColorType['ios'];
    readonly MenuAction: typeof MenuAction;
    readonly SplitView: typeof SplitView;
    readonly ToolbarHost: typeof ToolbarHost;
    readonly BarButtonItem: typeof ToolbarItem;
    readonly ZoomTransitionAlignmentRectDetector: typeof ZoomTransitionAlignmentRectDetector;
    readonly ZoomTransitionEnabler: typeof ZoomTransitionEnabler;
    readonly ZoomTransitionSource: typeof ZoomTransitionSource;
};
export type OneAndroid = typeof Compose & {
    readonly Color: ColorType['android'];
    readonly Menu: typeof NativeMenu;
    readonly ContextMenu: typeof NativeContextMenu;
};
export type OneSafeArea = {
    readonly Provider: typeof SafeAreaProvider;
    readonly View: typeof SafeAreaView;
    readonly initialMetrics: typeof initialWindowMetrics;
};
export type OneUI = typeof NativeUI & {
    readonly Fonts: typeof Fonts;
    readonly SafeArea: Readonly<OneSafeArea>;
    readonly TextInput: typeof TextInput;
    readonly ReservedRegions: typeof ReservedRegions;
};
export type OneNotifications = typeof Notifications;
export type OneAPI = {
    readonly platform: OnePlatform;
    readonly openURL: typeof Open.openURL;
    readonly openShare: typeof Open.openShare;
    readonly openSettings: typeof Open.openSettings;
    readonly AppInfo: typeof AppInfo;
    readonly Database: typeof Database;
    readonly iOS: Readonly<OneIOS>;
    readonly Android: Readonly<OneAndroid>;
    readonly UI: Readonly<OneUI>;
    readonly Notifications: Readonly<OneNotifications>;
    readonly Clipboard: typeof NativeClipboard;
    readonly Haptics: typeof Haptics;
    readonly LaunchScreen: typeof LaunchScreen;
    readonly Network: typeof NativeNetwork;
    readonly Auth: typeof Auth;
    readonly Browser: typeof NativeBrowser;
    readonly ImagePicker: typeof ImagePicker;
    readonly DocumentPicker: typeof DocumentPicker;
    readonly SecureStore: typeof NativeSecureStore;
    readonly Speech: typeof NativeSpeech;
    readonly Updates: typeof NativeUpdates;
};
export declare const One: OneAPI;
//# sourceMappingURL=one.d.ts.map