// re-exports table row types generated by drizzle-zero in schema.ts.
// add a new drizzle table → its row type shows up here automatically.

import type { Comment, Post, UserPublic, Schema } from './data/generated/schema'
import type { Row } from '@rocicorp/zero'

export type * from './data/generated/schema'

export type CommentWithUser = Comment & {
  user?: UserPublic
}

export type PostWithUser = Post & {
  user?: UserPublic
}

export type PostWithLatestComment = Post & {
  user?: UserPublic
  comments?: readonly CommentWithUser[]
}

// update<T> — primary keys required, everything else optional.
type Tables = Schema['tables']
export type Update<T extends keyof Tables> = Partial<Row<Tables[T]>> &
  Pick<Row<Tables[T]>, Tables[T]['primaryKey'][number]>
