import type { ComposeAlertDialogProps, ComposeBoxProps, ComposeButtonProps, ComposeColumnProps, ComposeDialogProps, ComposeIconProps, ComposeProgressIndicatorProps, ComposeRowProps, ComposeSliderProps, ComposeStyle, ComposeSwitchProps, ComposeTextFieldProps, ComposeTextProps } from './composeTypes';
export declare const horizontalAlignments: readonly ['start', 'centerHorizontally', 'end'];
export declare const verticalAlignments: readonly ['top', 'centerVertically', 'bottom'];
export declare const contentAlignments: readonly ['topStart', 'topCenter', 'topEnd', 'centerStart', 'center', 'centerEnd', 'bottomStart', 'bottomCenter', 'bottomEnd', 'top', 'bottom', 'start', 'end'];
export declare const verticalArrangements: readonly ['top', 'center', 'bottom', 'spaceBetween', 'spaceAround', 'spaceEvenly'];
export declare const horizontalArrangements: readonly ['start', 'center', 'end', 'spaceBetween', 'spaceAround', 'spaceEvenly'];
export declare const textAlignments: readonly ['unspecified', 'left', 'right', 'center', 'justify', 'start', 'end'];
export declare const fontWeights: readonly ['thin', 'extraLight', 'light', 'normal', 'medium', 'semiBold', 'bold', 'extraBold', 'black'];
export declare const buttonVariants: readonly ['filled', 'outlined', 'text'];
export declare const buttonTones: readonly ['default', 'danger'];
export declare const textFieldVariants: readonly ['filled', 'outlined'];
export declare const textFieldKeyboardTypes: readonly ['default', 'number', 'decimal', 'email', 'password', 'phone', 'url'];
export declare const progressVariants: readonly ['linear', 'circular'];
export declare function assertComposeStyle(style: ComposeStyle | undefined): void;
export declare function assertString(value: unknown, name: string, nonEmpty?: boolean): asserts value is string;
export declare function assertOptionalString(value: unknown, name: string): void;
export declare function assertBoolean(value: unknown, name: string): void;
export declare function assertOptionalBoolean(value: unknown, name: string): void;
export declare function assertOneOf<T extends string>(value: unknown, name: string, values: readonly T[]): void;
export declare function assertFiniteNumber(value: unknown, name: string): void;
export declare function assertFunction(value: unknown, name: string): void;
export declare function validateColumnProps(props: ComposeColumnProps): void;
export declare function validateRowProps(props: ComposeRowProps): void;
export declare function validateBoxProps(props: ComposeBoxProps): void;
export declare function validateTextProps(props: ComposeTextProps): void;
export declare function composeIconGlyph(owner: string, name: string): string;
export declare function validateIconProps(props: ComposeIconProps): void;
export declare function validateButtonProps(props: ComposeButtonProps): void;
export declare function validateSwitchProps(props: ComposeSwitchProps): void;
export declare function validateTextFieldProps(props: ComposeTextFieldProps): void;
export declare function validateSliderProps(props: ComposeSliderProps): void;
export declare function validateAlertDialogProps(props: ComposeAlertDialogProps): void;
export declare function validateDialogProps(props: ComposeDialogProps): void;
export declare function validateProgressIndicatorProps(props: ComposeProgressIndicatorProps): void;
//# sourceMappingURL=composeValidation.d.ts.map