import { ControlGroup, DisclosureGroup, Divider, Form, Glass, Group, HStack, Host, LabeledContent, LazyHStack, LazyVStack, Link, List, ScrollView, Section, Slot, Spacer, VStack, ZStack } from './Containers.native';
import { ContextMenu, Menu } from './Menu.native';
import { Page, Pager } from './Pager.native';
import { Popover } from './Popover.native';
import { FullScreenCover, Sheet } from './Sheet.native';
import { Tab, Tabs } from './Tabs.native';
import { Compose } from './compose';
import * as UI from './effects';
export * from './extras';
export declare const Swift: {
    Picker({ selection, onSelectionChange, revision, label, disabled, options, pickerStyle, swiftStyle, style, ...props }: import("./types").PickerProps): import("react/jsx-runtime").JSX.Element;
    DatePicker({ selection, onSelectionChange, revision, label, disabled, minimumDate, maximumDate, displayedComponents, datePickerStyle, swiftStyle, style, ...props }: import("./types").DatePickerProps): import("react/jsx-runtime").JSX.Element;
    ColorPicker({ selection, onSelectionChange, revision, label, disabled, supportsOpacity, swiftStyle, style, ...props }: import("./types").ColorPickerProps): import("react/jsx-runtime").JSX.Element;
    Toggle({ isOn, onIsOnChange, revision, label, disabled, toggleStyle, swiftStyle, style, ...props }: import("./types").ToggleProps): import("react/jsx-runtime").JSX.Element;
    Slider({ value, onValueChange, revision, label, disabled, minimumValue, maximumValue, step, minimumValueLabel, maximumValueLabel, minimumValueImage, maximumValueImage, swiftStyle, style, ...props }: import("./types").SliderProps): import("react/jsx-runtime").JSX.Element;
    Stepper({ value, onValueChange, revision, label, disabled, minimumValue, maximumValue, step, swiftStyle, style, ...props }: import("./types").StepperProps): import("react/jsx-runtime").JSX.Element;
    Text({ text, swiftStyle, style, ...props }: import("./types").TextProps): import("react/jsx-runtime").JSX.Element;
    Label({ label, disabled, systemImage, swiftStyle, style, ...props }: import("./types").LabelProps): import("react/jsx-runtime").JSX.Element;
    Button({ onPress, label, disabled, subtitle, systemImage, buttonRole, buttonStyle, disclosureIndicator, swiftStyle, style, ...props }: import("./types").ButtonProps): import("react/jsx-runtime").JSX.Element;
    ProgressView({ label, disabled, value, total, progressViewStyle, swiftStyle, style, ...props }: import("./types").ProgressViewProps): import("react/jsx-runtime").JSX.Element;
    Gauge({ label, disabled, value, minimumValue, maximumValue, currentValueLabel, minimumValueLabel, maximumValueLabel, gaugeStyle, swiftStyle, style, ...props }: import("./types").GaugeProps): import("react/jsx-runtime").JSX.Element;
    Image({ systemName, symbolRenderingMode, symbolVariant, imageScale, variableValue, colorRole, swiftStyle, style, ...props }: import("./types").ImageProps): import("react/jsx-runtime").JSX.Element;
    ShareLink({ label, disabled, systemImage, item, itemType, subject, message, swiftStyle, style, ...props }: import("./types").ShareLinkProps): import("react/jsx-runtime").JSX.Element;
    ContentUnavailableView({ onAction, title, systemImage, description, actions, swiftStyle, style, ...props }: import("./types").ContentUnavailableViewProps): import("react/jsx-runtime").JSX.Element;
    VideoPlayer({ url, autoplay, swiftStyle, style, ...props }: import("./types").VideoPlayerProps): import("react/jsx-runtime").JSX.Element;
    PhotosPicker({ onPick, onPickError, label, disabled, systemImage, maxSelectionCount, selectionBehavior, filter, preferredItemEncoding, swiftStyle, style, ...props }: import("./types").PhotosPickerProps): import("react/jsx-runtime").JSX.Element;
    WebView({ onNavigate, onTitleChange, onLoadingChange, url, html, backForwardNavigationGestures, magnificationGestures, linkPreviews, elementFullscreen, contentBackground, swiftStyle, style, ...props }: import("./types").WebViewProps): import("react/jsx-runtime").JSX.Element;
    SignInWithAppleButton({ onCompletion, requestedScopes, nonce, swiftStyle, style, ...props }: import("./types").SignInWithAppleButtonProps): import("react/jsx-runtime").JSX.Element;
    Map({ onRegionChange, latitude, longitude, distance, markers, swiftStyle, style, ...props }: import("./types").MapProps): import("react/jsx-runtime").JSX.Element;
    TextField({ text, onTextChange, revision, focused, onFocusChange, focusRevision, onSubmit, label, disabled, prompt, textFieldStyle, submitLabel, textInputAutocapitalization, autocorrectionDisabled, keyboardType, textContentType, axis, swiftStyle, style, ...props }: import("./types").TextFieldProps): import("react/jsx-runtime").JSX.Element;
    SecureField({ text, onTextChange, revision, focused, onFocusChange, focusRevision, onSubmit, label, disabled, prompt, textFieldStyle, submitLabel, textInputAutocapitalization, autocorrectionDisabled, keyboardType, textContentType, swiftStyle, style, ...props }: import("./types").SecureFieldProps): import("react/jsx-runtime").JSX.Element;
    Alert({ isPresented, onIsPresentedChange, revision, onAction, title, message, presenting, actions, swiftStyle, style, ...props }: import("./types").AlertProps): import("react/jsx-runtime").JSX.Element;
    ConfirmationDialog({ isPresented, onIsPresentedChange, revision, onAction, title, message, presenting, actions, titleVisibility, swiftStyle, style, ...props }: import("./types").ConfirmationDialogProps): import("react/jsx-runtime").JSX.Element;
    QuickLook({ isPresented, onIsPresentedChange, revision, url, swiftStyle, style, ...props }: import("./types").QuickLookProps): import("react/jsx-runtime").JSX.Element;
    FileImporter({ isPresented, onIsPresentedChange, revision, onCompletion, allowedContentTypes, allowsMultipleSelection, swiftStyle, style, ...props }: import("./types").FileImporterProps): import("react/jsx-runtime").JSX.Element;
    Tabs: typeof Tabs;
    Tab: typeof Tab;
    Menu: typeof Menu;
    ContextMenu: typeof ContextMenu;
    Sheet: typeof Sheet;
    FullScreenCover: typeof FullScreenCover;
    Popover: typeof Popover;
    Host: typeof Host;
    HStack: typeof HStack;
    VStack: typeof VStack;
    ZStack: typeof ZStack;
    Form: typeof Form;
    Section: typeof Section;
    Glass: typeof Glass;
    LabeledContent: typeof LabeledContent;
    List: typeof List;
    ScrollView: typeof ScrollView;
    LazyVStack: typeof LazyVStack;
    LazyHStack: typeof LazyHStack;
    ControlGroup: typeof ControlGroup;
    DisclosureGroup: typeof DisclosureGroup;
    Divider: typeof Divider;
    Link: typeof Link;
    Group: typeof Group;
    Overlay: (({ alignment, children, style, ...props }: import("./groupTypes").OverlayProps) => import("react/jsx-runtime").JSX.Element) & {
        Content: typeof import("./Containers.native").OverlayContent;
    };
    SwipeActions: (({ children, style, ...props }: import("./groupTypes").SwipeActionsProps) => import("react/jsx-runtime").JSX.Element) & {
        Actions: typeof import("./Containers.native").SwipeActionsActions;
    };
    Pager: typeof Pager;
    Page: typeof Page;
    Spacer: typeof Spacer;
    Slot: typeof Slot;
};
export { Compose };
export { useNativeState, type NativeState } from './nativeState';
export { TextInput } from './universal/TextInput/index';
export type { TextInputProps, TextInputRef, TextInputSelection, } from './universal/TextInput/textInputTypes';
export type * from './types';
export type * from './composeTypes';
export { UI };
//# sourceMappingURL=index.native.d.ts.map