import type { ButtonProps, ContextMenuProps, ControlGroupProps, DisclosureGroupProps, DividerProps, FormProps, FullScreenCoverProps, GlassProps, GroupProps, HostProps, LabeledContentProps, LazyHStackProps, LazyVStackProps, LinkProps, ListProps, MenuProps, OverlayContentProps, OverlayProps, PageProps, PagerProps, PopoverProps, ScrollViewProps, SectionProps, SheetProps, SlotProps, SpacerProps, StackProps, SwipeActionsActionsProps, SwipeActionsProps, TabProps, TabsProps, TabViewBottomAccessoryProps, ZStackProps } from './types';
declare function Tabs(_props: TabsProps): never;
declare function Tab(_props: TabProps): never;
declare function TabViewBottomAccessory(_props: TabViewBottomAccessoryProps): never;
declare function Menu(_props: MenuProps): never;
declare function ContextMenu(_props: ContextMenuProps): never;
declare function Sheet(_props: SheetProps): never;
declare function FullScreenCover(_props: FullScreenCoverProps): never;
declare function Popover(_props: PopoverProps): never;
declare function Host(_props: HostProps): never;
declare function HStack(_props: StackProps): never;
declare function VStack(_props: StackProps): never;
declare function ZStack(_props: ZStackProps): never;
declare function Spacer(_props: SpacerProps): never;
declare function Form(_props: FormProps): never;
declare function Section(_props: SectionProps): never;
declare function LabeledContent(_props: LabeledContentProps): never;
declare function Button(_props: ButtonProps): never;
declare function Glass(_props: GlassProps): never;
declare function Slot(_props: SlotProps): never;
declare function List(_props: ListProps): never;
declare function ScrollView(_props: ScrollViewProps): never;
declare function LazyVStack(_props: LazyVStackProps): never;
declare function LazyHStack(_props: LazyHStackProps): never;
declare function ControlGroup(_props: ControlGroupProps): never;
declare function DisclosureGroup(_props: DisclosureGroupProps): never;
declare function Divider(_props: DividerProps): never;
declare function Link(_props: LinkProps): never;
declare function Group(_props: GroupProps): never;
declare function OverlayContent(_props: OverlayContentProps): never;
declare function OverlayFn(_props: OverlayProps): never;
declare function SwipeActionsActions(_props: SwipeActionsActionsProps): never;
declare function SwipeActionsFn(_props: SwipeActionsProps): never;
declare function Page(_props: PageProps): never;
declare function Pager(_props: PagerProps): never;
export declare const Swift: {
    Picker: (_props: import("./types").PickerProps) => never;
    DatePicker: (_props: import("./types").DatePickerProps) => never;
    ColorPicker: (_props: import("./types").ColorPickerProps) => never;
    Toggle: (_props: import("./types").ToggleProps) => never;
    Slider: (_props: import("./types").SliderProps) => never;
    Stepper: (_props: import("./types").StepperProps) => never;
    Text: (_props: import("./types").TextProps) => never;
    Label: (_props: import("./types").LabelProps) => never;
    ProgressView: (_props: import("./types").ProgressViewProps) => never;
    Gauge: (_props: import("./types").GaugeProps) => never;
    Image: (_props: import("./types").ImageProps) => never;
    ShareLink: (_props: import("./types").ShareLinkProps) => never;
    ContentUnavailableView: (_props: import("./types").ContentUnavailableViewProps) => never;
    Circle: (_props: import("./types").CircleProps) => never;
    Capsule: (_props: import("./types").CapsuleProps) => never;
    Rectangle: (_props: import("./types").RectangleProps) => never;
    RoundedRectangle: (_props: import("./types").RoundedRectangleProps) => never;
    Ellipse: (_props: import("./types").EllipseProps) => never;
    VideoPlayer: (_props: import("./types").VideoPlayerProps) => never;
    PhotosPicker: (_props: import("./types").PhotosPickerProps) => never;
    WebView: (_props: import("./types").WebViewProps) => never;
    SignInWithAppleButton: (_props: import("./types").SignInWithAppleButtonProps) => never;
    Map: (_props: import("./types").MapProps) => never;
    TextField: (_props: import("./types").TextFieldProps) => never;
    SecureField: (_props: import("./types").SecureFieldProps) => never;
    Alert: (_props: import("./types").AlertProps) => never;
    ConfirmationDialog: (_props: import("./types").ConfirmationDialogProps) => never;
    QuickLook: (_props: import("./types").QuickLookProps) => never;
    FileImporter: (_props: import("./types").FileImporterProps) => never;
    EditButton: (_props: import("./types").EditButtonProps) => never;
    EmptyView: (_props: import("./types").EmptyViewProps) => never;
    Tabs: typeof Tabs;
    Tab: typeof Tab;
    TabViewBottomAccessory: typeof TabViewBottomAccessory;
    Menu: typeof Menu;
    ContextMenu: typeof ContextMenu;
    Sheet: typeof Sheet;
    FullScreenCover: typeof FullScreenCover;
    Popover: typeof Popover;
    Host: typeof Host;
    HStack: typeof HStack;
    VStack: typeof VStack;
    ZStack: typeof ZStack;
    Form: typeof Form;
    Section: typeof Section;
    Glass: typeof Glass;
    LabeledContent: typeof LabeledContent;
    Button: typeof Button;
    Spacer: typeof Spacer;
    Slot: typeof Slot;
    List: typeof List;
    ScrollView: typeof ScrollView;
    LazyVStack: typeof LazyVStack;
    LazyHStack: typeof LazyHStack;
    ControlGroup: typeof ControlGroup;
    DisclosureGroup: typeof DisclosureGroup;
    Divider: typeof Divider;
    Link: typeof Link;
    Group: typeof Group;
    Overlay: typeof OverlayFn & {
        Content: typeof OverlayContent;
    };
    SwipeActions: typeof SwipeActionsFn & {
        Actions: typeof SwipeActionsActions;
    };
    Pager: typeof Pager;
    Page: typeof Page;
};
export type * from './types';
//# sourceMappingURL=unsupported.d.ts.map