import type { ComposeAlertDialogProps, ComposeAssistChipProps, ComposeBadgeProps, ComposeBoxProps, ComposeButtonProps, ComposeCardProps, ComposeCheckboxProps, ComposeColumnProps, ComposeDialogProps, ComposeDividerProps, ComposeFilterChipProps, ComposeFlowRowProps, ComposeFloatingActionButtonProps, ComposeIconProps, ComposeIconButtonProps, ComposeInputChipProps, ComposeListItemProps, ComposeLoadingIndicatorProps, ComposeContainedLoadingIndicatorProps, ComposeProgressIndicatorProps, ComposeRadioButtonProps, ComposeRowProps, ComposeSliderProps, ComposeSuggestionChipProps, ComposeStyle, ComposeSurfaceProps, ComposeSwitchProps, ComposeTextFieldProps, ComposeTextProps, ComposeToggleButtonProps, ComposeSegmentedButtonProps } from './composeTypes';
export declare const horizontalAlignments: readonly ['start', 'centerHorizontally', 'end'];
export declare const verticalAlignments: readonly ['top', 'centerVertically', 'bottom'];
export declare const contentAlignments: readonly ['topStart', 'topCenter', 'topEnd', 'centerStart', 'center', 'centerEnd', 'bottomStart', 'bottomCenter', 'bottomEnd', 'top', 'bottom', 'start', 'end'];
export declare const verticalArrangements: readonly ['top', 'center', 'bottom', 'spaceBetween', 'spaceAround', 'spaceEvenly'];
export declare const horizontalArrangements: readonly ['start', 'center', 'end', 'spaceBetween', 'spaceAround', 'spaceEvenly'];
export declare const textAlignments: readonly ['unspecified', 'left', 'right', 'center', 'justify', 'start', 'end'];
export declare const fontWeights: readonly ['thin', 'extraLight', 'light', 'normal', 'medium', 'semiBold', 'bold', 'extraBold', 'black'];
export declare const buttonVariants: readonly ['filled', 'tonal', 'elevated', 'outlined', 'text'];
export declare const buttonTones: readonly ['default', 'danger'];
export declare const textFieldVariants: readonly ['filled', 'outlined'];
export declare const textFieldKeyboardTypes: readonly ['default', 'number', 'decimal', 'email', 'password', 'phone', 'url'];
export declare const textFieldImeActions: readonly ['default', 'none', 'go', 'search', 'send', 'previous', 'next', 'done'];
export declare const textFieldCapitalizations: readonly ['none', 'characters', 'words', 'sentences'];
export declare const progressVariants: readonly ['linear', 'circular', 'linearWavy', 'circularWavy'];
export declare const progressStrokeCaps: readonly ['round', 'butt', 'square'];
export declare function validateListItemProps(props: ComposeListItemProps): void;
export declare function validateBadgeProps(props: Pick<ComposeBadgeProps, 'containerColor' | 'contentColor'>): void;
export declare function assertComposeStyle(style: ComposeStyle | undefined): void;
export declare function assertString(value: unknown, name: string, nonEmpty?: boolean): asserts value is string;
export declare function assertOptionalString(value: unknown, name: string): void;
export declare function assertBoolean(value: unknown, name: string): void;
export declare function assertOptionalBoolean(value: unknown, name: string): void;
export declare function assertOneOf<T extends string>(value: unknown, name: string, values: readonly T[]): void;
export declare function assertFiniteNumber(value: unknown, name: string): void;
export declare function assertFunction(value: unknown, name: string): void;
export declare function validateColumnProps(props: ComposeColumnProps): void;
export declare function validateRowProps(props: ComposeRowProps): void;
export declare function validateFlowRowProps(props: ComposeFlowRowProps): void;
export declare function validateBoxProps(props: ComposeBoxProps): void;
export declare function validateTextProps(props: ComposeTextProps): void;
export declare function composeIconGlyph(owner: string, name: string): string;
export declare function validateIconProps(props: ComposeIconProps): void;
export declare function validateButtonProps(props: ComposeButtonProps): void;
export declare function validateIconButtonProps(props: ComposeIconButtonProps): void;
export declare function validateFloatingActionButtonProps(props: ComposeFloatingActionButtonProps & {
    expanded?: boolean;
}, variant: string): void;
export declare function validateToggleButtonProps(props: ComposeToggleButtonProps): void;
export declare function validateSegmentedButtonProps(props: ComposeSegmentedButtonProps): void;
export declare function validateSwitchProps(props: ComposeSwitchProps): void;
export declare function validateCheckboxProps(props: ComposeCheckboxProps): void;
export declare function validateRadioButtonProps(props: ComposeRadioButtonProps): void;
export declare function validateCardProps(props: ComposeCardProps, kind: 'Card' | 'ElevatedCard' | 'OutlinedCard'): void;
export declare function validateSurfaceProps(props: ComposeSurfaceProps): void;
export declare function validateChipProps(props: ComposeAssistChipProps | ComposeFilterChipProps | ComposeInputChipProps | ComposeSuggestionChipProps, kind: 'AssistChip' | 'FilterChip' | 'InputChip' | 'SuggestionChip'): void;
export declare function validateDividerProps(props: ComposeDividerProps, kind: 'HorizontalDivider' | 'VerticalDivider'): void;
export declare function validateTextFieldProps(props: ComposeTextFieldProps): void;
export declare function validateSliderProps(props: ComposeSliderProps): void;
export declare function validateAlertDialogProps(props: ComposeAlertDialogProps): void;
export declare function validateDialogProps(props: ComposeDialogProps): void;
export declare function validateProgressIndicatorProps(props: ComposeProgressIndicatorProps): void;
export declare function validateLoadingIndicatorProps(props: ComposeLoadingIndicatorProps | ComposeContainedLoadingIndicatorProps): void;
//# sourceMappingURL=composeValidation.d.ts.map