import { Button, ControlGroup, DisclosureGroup, Divider, Form, Glass, GlassEffectContainer, Group, GroupBox, ViewThatFits, HStack, Host, LabeledContent, LazyHStack, LazyVStack, LazyHGrid, LazyVGrid, Grid, GridRow, Link, List, ScrollView, Section, Slot, Spacer, VStack, ZStack } from './Containers.native';
import { ContextMenu as AndroidContextMenu, Menu as AndroidMenu } from './AndroidMenu';
import { Page, Pager } from './Pager.native';
import { Popover } from './Popover.native';
import { NavigationStack, Toolbar, ToolbarItem, ToolbarItemGroup, ToolbarSpacer } from './NavigationStack.native';
import { FullScreenCover, Sheet } from './Sheet.native';
import { Tab, Tabs, TabSection, TabViewBottomAccessory, TabViewSlot } from './Tabs.native';
import { Compose } from './compose';
import * as UI from './effects';
import { Widgets, LiveActivities, WidgetUI } from './widgets/index.native';
export * from './extras';
export type { ToolbarHostProps, ToolbarItemProps } from './extras';
export { useSizeClass, getSizeClass, useHinge, getHinge, onHingeChange, ReservedRegions, useReservedRegions, useReservedRegionsReady, useWindowSegments, useSpanning, } from './adaptive/index.native';
export type { UserInterfaceSizeClass, SizeClass, HingeStatus, HingeState, ReservedRegionKind, ReservedRegion, WindowSegment, ReservedRegionOptions, ReservedRegionsProviderProps, } from './adaptive/types';
export type { ArrangementViewProps, ArrangementPaneProps, ArrangementViewStyle, SplitLayoutRatio, SplitLayoutSize, SplitFixedLayoutSize, OverlayArrangementEdge, } from './ArrangementView.native';
declare const Menu: typeof AndroidMenu;
declare const ContextMenu: typeof AndroidContextMenu;
export declare const Swift: {
    Picker({ selection, onSelectionChange, revision, label, disabled, options, pickerStyle, swiftStyle, style, ...props }: import("./types").PickerProps): import("react/jsx-runtime").JSX.Element;
    DatePicker({ selection, onSelectionChange, revision, label, disabled, minimumDate, maximumDate, displayedComponents, datePickerStyle, swiftStyle, style, ...props }: import("./types").DatePickerProps): import("react/jsx-runtime").JSX.Element;
    ColorPicker({ selection, onSelectionChange, revision, label, disabled, supportsOpacity, swiftStyle, style, ...props }: import("./types").ColorPickerProps): import("react/jsx-runtime").JSX.Element;
    Toggle({ isOn, onIsOnChange, revision, label, disabled, systemImage, toggleStyle, swiftStyle, style, ...props }: import("./types").ToggleProps): import("react/jsx-runtime").JSX.Element;
    Slider({ value, onValueChange, revision, label, disabled, minimumValue, maximumValue, step, minimumValueLabel, maximumValueLabel, minimumValueImage, maximumValueImage, swiftStyle, style, ...props }: import("./types").SliderProps): import("react/jsx-runtime").JSX.Element;
    Stepper({ value, onValueChange, revision, label, disabled, minimumValue, maximumValue, step, swiftStyle, style, ...props }: import("./types").StepperProps): import("react/jsx-runtime").JSX.Element;
    PasteButton({ onPaste, disabled, swiftStyle, style, ...props }: import("./types").PasteButtonProps): import("react/jsx-runtime").JSX.Element;
    Text({ text, swiftStyle, style, ...props }: import("./types").TextProps): import("react/jsx-runtime").JSX.Element;
    Label({ label, disabled, systemImage, swiftStyle, style, ...props }: import("./types").LabelProps): import("react/jsx-runtime").JSX.Element;
    ProgressView({ label, disabled, value, total, progressViewStyle, swiftStyle, style, ...props }: import("./types").ProgressViewProps): import("react/jsx-runtime").JSX.Element;
    Gauge({ label, disabled, value, minimumValue, maximumValue, currentValueLabel, minimumValueLabel, maximumValueLabel, gaugeStyle, swiftStyle, style, ...props }: import("./types").GaugeProps): import("react/jsx-runtime").JSX.Element;
    Image({ systemName, uri, renderingMode, symbolRenderingMode, symbolVariant, imageScale, variableValue, colorRole, swiftStyle, style, ...props }: import("./types").ImageProps): import("react/jsx-runtime").JSX.Element;
    ShareLink({ label, disabled, systemImage, item, itemType, subject, message, swiftStyle, style, ...props }: import("./types").ShareLinkProps): import("react/jsx-runtime").JSX.Element;
    ContentUnavailableView({ onAction, title, systemImage, description, actions, swiftStyle, style, ...props }: import("./types").ContentUnavailableViewProps): import("react/jsx-runtime").JSX.Element;
    Circle({ fill, swiftStyle, style, ...props }: import("./types").CircleProps): import("react/jsx-runtime").JSX.Element;
    Capsule({ fill, swiftStyle, style, ...props }: import("./types").CapsuleProps): import("react/jsx-runtime").JSX.Element;
    Rectangle({ fill, swiftStyle, style, ...props }: import("./types").RectangleProps): import("react/jsx-runtime").JSX.Element;
    RoundedRectangle({ fill, cornerRadius, swiftStyle, style, ...props }: import("./types").RoundedRectangleProps): import("react/jsx-runtime").JSX.Element;
    Ellipse({ fill, swiftStyle, style, ...props }: import("./types").EllipseProps): import("react/jsx-runtime").JSX.Element;
    UnevenRoundedRectangle({ fill, topLeadingRadius, bottomLeadingRadius, bottomTrailingRadius, topTrailingRadius, swiftStyle, style, ...props }: import("./types").UnevenRoundedRectangleProps): import("react/jsx-runtime").JSX.Element;
    ConcentricRectangle({ fill, swiftStyle, style, ...props }: import("./types").ConcentricRectangleProps): import("react/jsx-runtime").JSX.Element;
    LinearGradient({ colors, startPoint, endPoint, swiftStyle, style, ...props }: import("./types").LinearGradientProps): import("react/jsx-runtime").JSX.Element;
    RadialGradient({ colors, center, startRadius, endRadius, swiftStyle, style, ...props }: import("./types").RadialGradientProps): import("react/jsx-runtime").JSX.Element;
    EllipticalGradient({ colors, center, startRadiusFraction, endRadiusFraction, swiftStyle, style, ...props }: import("./types").EllipticalGradientProps): import("react/jsx-runtime").JSX.Element;
    AngularGradient({ colors, center, angle, swiftStyle, style, ...props }: import("./types").AngularGradientProps): import("react/jsx-runtime").JSX.Element;
    VideoPlayer({ url, autoplay, swiftStyle, style, ...props }: import("./types").VideoPlayerProps): import("react/jsx-runtime").JSX.Element;
    PhotosPicker({ onPick, onPickItemIdentifier, onPickError, label, disabled, systemImage, maxSelectionCount, selectionBehavior, filter, preferredItemEncoding, swiftStyle, style, ...props }: import("./types").PhotosPickerProps): import("react/jsx-runtime").JSX.Element;
    WebView({ onNavigate, onTitleChange, onLoadingChange, url, html, backForwardNavigationGestures, magnificationGestures, linkPreviews, elementFullscreen, contentBackground, swiftStyle, style, ...props }: import("./types").WebViewProps): import("react/jsx-runtime").JSX.Element;
    SignInWithAppleButton({ onCompletion, requestedScopes, nonce, label, swiftStyle, style, ...props }: import("./types").SignInWithAppleButtonProps): import("react/jsx-runtime").JSX.Element;
    Map({ onRegionChange, latitude, longitude, distance, markers, swiftStyle, style, ...props }: import("./types").MapProps): import("react/jsx-runtime").JSX.Element;
    TextField({ text, onTextChange, revision, focused, onFocusChange, focusRevision, onSubmit, label, disabled, prompt, textFieldStyle, submitLabel, textInputAutocapitalization, autocorrectionDisabled, keyboardType, textContentType, axis, swiftStyle, style, ...props }: import("./types").TextFieldProps): import("react/jsx-runtime").JSX.Element;
    SecureField({ text, onTextChange, revision, focused, onFocusChange, focusRevision, onSubmit, label, disabled, prompt, textFieldStyle, submitLabel, textInputAutocapitalization, autocorrectionDisabled, keyboardType, textContentType, swiftStyle, style, ...props }: import("./types").SecureFieldProps): import("react/jsx-runtime").JSX.Element;
    TextEditor({ text, onTextChange, revision, focused, onFocusChange, focusRevision, disabled, textInputAutocapitalization, autocorrectionDisabled, keyboardType, textContentType, swiftStyle, style, ...props }: import("./types").TextEditorProps): import("react/jsx-runtime").JSX.Element;
    Alert({ isPresented, onIsPresentedChange, revision, onAction, title, message, presenting, actions, swiftStyle, style, ...props }: import("./types").AlertProps): import("react/jsx-runtime").JSX.Element;
    ConfirmationDialog({ isPresented, onIsPresentedChange, revision, onAction, title, message, presenting, actions, titleVisibility, swiftStyle, style, ...props }: import("./types").ConfirmationDialogProps): import("react/jsx-runtime").JSX.Element;
    QuickLook({ isPresented, onIsPresentedChange, revision, url, swiftStyle, style, ...props }: import("./types").QuickLookProps): import("react/jsx-runtime").JSX.Element;
    FileImporter({ isPresented, onIsPresentedChange, revision, onCompletion, allowedContentTypes, allowsMultipleSelection, swiftStyle, style, ...props }: import("./types").FileImporterProps): import("react/jsx-runtime").JSX.Element;
    EditButton({ swiftStyle, style, ...props }: import("./types").EditButtonProps): import("react/jsx-runtime").JSX.Element;
    EmptyView({ swiftStyle, style, ...props }: import("./types").EmptyViewProps): import("react/jsx-runtime").JSX.Element;
    ArrangementView: typeof import("./ArrangementView.native").ArrangementViewComponent & {
        Primary: typeof import("./ArrangementView.native").ArrangementPrimary;
        Secondary: typeof import("./ArrangementView.native").ArrangementSecondary;
        Leading: typeof import("./ArrangementView.native").ArrangementPrimary;
        Detail: typeof import("./ArrangementView.native").ArrangementSecondary;
    };
    Tabs: typeof Tabs;
    Tab: typeof Tab;
    TabSection: typeof TabSection;
    TabViewBottomAccessory: typeof TabViewBottomAccessory;
    TabViewSlot: typeof TabViewSlot;
    Menu: typeof AndroidMenu;
    ContextMenu: typeof AndroidContextMenu;
    Sheet: typeof Sheet;
    FullScreenCover: typeof FullScreenCover;
    Popover: typeof Popover;
    Host: typeof Host;
    HStack: typeof HStack;
    VStack: typeof VStack;
    ZStack: typeof ZStack;
    Form: typeof Form;
    Section: typeof Section;
    Glass: typeof Glass;
    GlassEffectContainer: typeof GlassEffectContainer;
    LabeledContent: typeof LabeledContent;
    Button: typeof Button;
    List: typeof List;
    ScrollView: typeof ScrollView;
    LazyVStack: typeof LazyVStack;
    LazyHStack: typeof LazyHStack;
    LazyVGrid: typeof LazyVGrid;
    LazyHGrid: typeof LazyHGrid;
    Grid: typeof Grid;
    GridRow: typeof GridRow;
    ControlGroup: typeof ControlGroup;
    DisclosureGroup: typeof DisclosureGroup;
    Divider: typeof Divider;
    Link: typeof Link;
    Group: typeof Group;
    GroupBox: typeof GroupBox;
    ViewThatFits: typeof ViewThatFits;
    Overlay: (({ alignment, children, style, ...props }: import("./groupTypes").OverlayProps) => import("react/jsx-runtime").JSX.Element) & {
        Content: typeof import("./Containers.native").OverlayContent;
    };
    ViewSlot: (({ name, options, children, style, ...props }: import("./groupTypes").ViewSlotProps) => import("react/jsx-runtime").JSX.Element) & {
        Content: typeof import("./Containers.native").OverlayContent;
    };
    SwipeActions: (({ children, style, ...props }: import("./groupTypes").SwipeActionsProps) => import("react/jsx-runtime").JSX.Element) & {
        Actions: typeof import("./Containers.native").SwipeActionsActions;
    };
    Pager: typeof Pager;
    Page: typeof Page;
    NavigationStack: typeof NavigationStack;
    Toolbar: typeof Toolbar;
    ToolbarItem: typeof ToolbarItem;
    ToolbarItemGroup: typeof ToolbarItemGroup;
    ToolbarSpacer: typeof ToolbarSpacer;
    Spacer: typeof Spacer;
    Slot: typeof Slot;
};
export { Compose };
export { Notifications } from './notifications';
export { Widgets, LiveActivities, WidgetUI };
export { Menu, ContextMenu };
export { useNativeState, type NativeState } from './nativeState';
export { TextInput } from './universal/TextInput/index';
export type { TextInputProps, TextInputRef, TextInputSelection, } from './universal/TextInput/textInputTypes';
export type * from './types';
export type * from './composeTypes';
export { Haptics } from './haptics/index.native';
export { LaunchScreen } from './launchScreen/index.native';
export { LocalAuthentication } from './local-authentication/index.native';
export type { LocalAuthenticationStatus } from './local-authentication/index.native';
export { ProtectedStore } from './protected-store/index.native';
export type { ProtectedStorePolicy } from './protected-store/index.native';
export { Location } from './location/index.native';
export type { LocationPermissionStatus, LocationPosition, LocationPlace, LocationWatchError } from './location/index.native';
export { FileSystem } from './file-system/index.native';
export type { FileDirectories, FileEncoding, FileEntry, FileInfo } from './file-system/index.native';
export { Audio } from './audio/index.native';
export { CameraView } from './camera/index.native';
export type { CameraCode, CameraCodeType, CameraFacing, CameraState, CameraViewProps, } from './camera/index.native';
export type { AudioPlaybackState, AudioPlaybackStatus, AudioRecordingPermission, AudioRecordingResult, AudioRecordingState, AudioRecordingStatus, } from './audio/index.native';
export { Share } from './share/index.native';
export { Open } from './open/index.native';
export type { OpenShareContent } from './open/index.native';
export type { ShareItem, ShareItemType, ShareResult } from './share/index.native';
export { PhotoLibrary } from './photo-library/index.native';
export type { PhotoLibraryPermissionStatus } from './photo-library/index.native';
export { AppTracking } from './app-tracking/index.native';
export type { AppTrackingPermissionStatus } from './app-tracking/index.native';
export { ImageManipulator } from './image-manipulator/index.native';
export type { ImageCrop, ImageFormat, ImageResize, ImageManipulatorOptions, ImageTransformResult } from './image-manipulator/index.native';
export { Device } from './device/index.native';
export type { DeviceInfo, LocalizationInfo } from './device/index.native';
export { Contacts } from './contacts/index.native';
export type { ContactChanges, ContactInfo, ContactInput, ContactsPermissionStatus } from './contacts/index.native';
export { Calendar } from './calendar/index.native';
export type { CalendarEvent, CalendarEventChanges, CalendarEventInput, CalendarPermissionStatus, ReminderInfo, ReminderInput, } from './calendar/index.native';
export type { HapticImpact, HapticNotification, HapticsApi } from './haptics/index.native';
export type { LaunchScreenApi, LaunchScreenHideOptions } from './launchScreen/index.native';
export { AppInfo } from './app-info/index.native';
export type { AppInfoApi } from './app-info/index.native';
export { ImagePicker } from './image-picker/index.native';
export { DocumentPicker } from './document-picker/index.native';
export { Database } from './database/index.native';
export type { ImagePickerAsset, ImagePickerCanceledResult, ImagePickerMediaType, ImagePickerOptions, ImagePickerPermissionResponse, ImagePickerResult, ImagePickerSuccessResult, } from './image-picker/index.native';
export type { DocumentPickerAsset, DocumentPickerCanceledResult, DocumentPickerOptions, DocumentPickerResult, DocumentPickerSuccessResult, } from './document-picker/index.native';
export { UI };
//# sourceMappingURL=index.native.d.ts.map