// generated by one typegen; edits will be replaced
import type { ReactElement } from 'react'

export declare function Level(props: { value: number; onChange: (value0: number) => void }): ReactElement
