// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type {
  DirectEventHandler,
  Int32,
  Double,
} from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
type MapMarker = Readonly<{
  id: string
  label: string
  latitude: Double
  longitude: Double
}>
interface NativeProps extends ViewProps {
  latitude: Double
  longitude: Double
  distance: Double
  markers: ReadonlyArray<MapMarker>
  onNativeMapRegionChange?: DirectEventHandler<
    Readonly<{ latitude: Double; longitude: Double; distance: Double; eventCount: Int32 }>
  >
}
export default codegenNativeComponent<NativeProps>('OneNativeMap')
