// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type { Double } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

interface NativeProps extends ViewProps {
  label: string
  disabled: boolean
  value: Double
  minimumValue: Double
  maximumValue: Double
  currentValueLabel: string
  minimumValueLabel: string
  maximumValueLabel: string
  gaugeStyle: string
}
export default codegenNativeComponent<NativeProps>('OneNativeGauge', {
  interfaceOnly: true,
})
