// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ColorValue, ViewProps } from 'react-native'
import type {
  DirectEventHandler,
  Int32,
  Double,
  WithDefault,
} from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

type OneNativeStyleNative = Readonly<{
  fontSize?: WithDefault<Double, -1>
  fontWeight?: string
  fontDesign?: string
  textStyle?: string
  foregroundStyle?: ColorValue
  tint?: ColorValue
  background?: ColorValue
  padding?: WithDefault<Double, -1>
  paddingTop?: WithDefault<Double, -1>
  paddingLeading?: WithDefault<Double, -1>
  paddingBottom?: WithDefault<Double, -1>
  paddingTrailing?: WithDefault<Double, -1>
  width?: WithDefault<Double, -1>
  height?: WithDefault<Double, -1>
  minWidth?: WithDefault<Double, -1>
  idealWidth?: WithDefault<Double, -1>
  maxWidth?: WithDefault<Double, -1>
  minHeight?: WithDefault<Double, -1>
  idealHeight?: WithDefault<Double, -1>
  maxHeight?: WithDefault<Double, -1>
  cornerRadius?: WithDefault<Double, -1>
  opacity?: WithDefault<Double, -1>
  borderColor?: ColorValue
  borderWidth?: WithDefault<Double, -1>
}>
interface NativeProps extends ViewProps {
  value: boolean
  acknowledgedEvent: Int32
  revision: Int32
  url: string
  swiftStyle?: OneNativeStyleNative
  onNativeQuickLookValueChange?: DirectEventHandler<
    Readonly<{ value: boolean; eventCount: Int32; revision: Int32 }>
  >
}
export default codegenNativeComponent<NativeProps>('OneNativeQuickLook')
