// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
type DialogAction = Readonly<{ id: string; label: string; role?: string }>
interface NativeProps extends ViewProps {
  value: boolean
  acknowledgedEvent: Int32
  revision: Int32
  title: string
  message: string
  actions: ReadonlyArray<DialogAction>
  onNativeAlertValueChange?: DirectEventHandler<
    Readonly<{ value: boolean; eventCount: Int32; revision: Int32 }>
  >
  onNativeAlertAction?: DirectEventHandler<Readonly<{ id: string; eventCount: Int32 }>>
}
export default codegenNativeComponent<NativeProps>('OneNativeAlert')
