// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

interface NativeProps extends ViewProps {
  value: string
  acknowledgedEvent: Int32
  revision: Int32
  label: string
  disabled: boolean
  prompt: string
  textFieldStyle: string
  submitLabel: string
  textInputAutocapitalization: string
  autocorrectionDisabled: boolean
  axis: string
  onNativeTextFieldValueChange?: DirectEventHandler<
    Readonly<{ value: string; eventCount: Int32; revision: Int32 }>
  >
  onNativeTextFieldSubmit?: DirectEventHandler<Readonly<{ eventCount: Int32 }>>
}
export default codegenNativeComponent<NativeProps>('OneNativeTextField', {
  interfaceOnly: true,
})
