// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ColorValue, ViewProps } from 'react-native'
import type {
  DirectEventHandler,
  Int32,
  Double,
} from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

type OneNativeStyleNative = Readonly<{
  fontSize?: Double
  fontWeight?: string
  fontDesign?: string
  textStyle?: string
  foregroundStyle?: ColorValue
  tint?: ColorValue
  background?: ColorValue
  padding?: Double
  paddingTop?: Double
  paddingLeading?: Double
  paddingBottom?: Double
  paddingTrailing?: Double
  width?: Double
  height?: Double
  minWidth?: Double
  idealWidth?: Double
  maxWidth?: Double
  minHeight?: Double
  idealHeight?: Double
  maxHeight?: Double
  cornerRadius?: Double
  opacity?: Double
  borderColor?: ColorValue
  borderWidth?: Double
}>
interface NativeProps extends ViewProps {
  label: string
  disabled: boolean
  systemImage: string
  buttonRole: string
  buttonStyle: string
  swiftStyle?: OneNativeStyleNative
  onNativeButtonPress?: DirectEventHandler<Readonly<{ eventCount: Int32 }>>
}
export default codegenNativeComponent<NativeProps>('OneNativeButton', {
  interfaceOnly: true,
})
