// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

interface NativeProps extends ViewProps {
  value: boolean
  acknowledgedEvent: Int32
  revision: Int32
  label: string
  disabled: boolean
  toggleStyle: string
  onNativeToggleValueChange?: DirectEventHandler<
    Readonly<{ value: boolean; eventCount: Int32; revision: Int32 }>
  >
}
export default codegenNativeComponent<NativeProps>('OneNativeToggle', {
  interfaceOnly: true,
})
