// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

interface NativeProps extends ViewProps {
  label: string
  disabled: boolean
  systemImage: string
  buttonRole: string
  buttonStyle: string
  onNativeButtonPress?: DirectEventHandler<Readonly<{ eventCount: Int32 }>>
}
export default codegenNativeComponent<NativeProps>('OneNativeButton', {
  interfaceOnly: true,
})
