import { useState } from 'react'
import { Pressable, StyleSheet, Text, View } from 'react-native'
import { One } from 'one'

// one-page PDF with visible text and a blue bar, generated by the probe builder.
const pdfBase64 = 'JVBERi0xLjQKJeLjz9MKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2JqCjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIgNzkyXSAvUmVzb3VyY2VzIDw8IC9Gb250IDw8IC9GMSA0IDAgUiA+PiA+PiAvQ29udGVudHMgNSAwIFIgPj4KZW5kb2JqCjQgMCBvYmoKPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iago1IDAgb2JqCjw8IC9MZW5ndGggODMgPj4Kc3RyZWFtCkJUIC9GMSAyNCBUZiA3MiA3MDAgVGQgKE9uZSBQcmludCBGaXh0dXJlKSBUaiBFVAowIDAuNDUgMC45IHJnIDcyIDUyMCA0NjggMTEwIHJlIGYKZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwMDA2NCAwMDAwMCBuIAowMDAwMDAwMTIxIDAwMDAwIG4gCjAwMDAwMDAyNDcgMDAwMDAgbiAKMDAwMDAwMDMxNyAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDYgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjQ0OQolJUVPRgo='

function message(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

async function failure(operation: () => Promise<unknown>): Promise<string> {
  try {
    await operation()
    return 'accepted'
  } catch (error) {
    return error && typeof error === 'object' && 'code' in error
      ? String(error.code)
      : message(error)
  }
}

export default function OneNativePrint() {
  const [status, setStatus] = useState('idle')
  const [results, setResults] = useState<[string, string][]>([])

  const report = (name: string, value: string) => {
    setResults((current) => [...current, [name, value]])
  }

  async function run() {
    setResults([])
    setStatus('running')
    const fs = One.FileSystem
    const print = One.Print
    const cache = fs.getDirectories().cache
    const pdfUri = new URL('one-native-print-proof.pdf', cache).href
    const badUri = new URL('one-native-print-bad.pdf', cache).href
    let outcome = 'done'
    try {
      const available = await print.isAvailable()
      report('Available', String(available))
      if (!available) throw new Error('system printing is unavailable')
      await fs.writeFile(pdfUri, pdfBase64, 'base64')
      const info = await fs.getInfo(pdfUri)
      report('PdfBytes', String(info.size))
      setStatus('presenting')
      const pending = print.printPdf(pdfUri, 'One Print Fixture')
      report('Busy', await failure(() => print.printPdf(pdfUri)))
      const result = await pending
      report('Completed', String(result.completed))
      setStatus('checking')
      report('RemoteURI', await failure(() => print.printPdf('https://example.com/file.pdf')))
      report('Missing', await failure(() => print.printPdf(new URL('missing.pdf', cache).href)))
      await fs.writeFile(badUri, 'not a PDF')
      report('BadPDF', await failure(() => print.printPdf(badUri)))
      report('InvalidType', await failure(() => Reflect.apply(print.printPdf, undefined, [42])))
      report('InvalidName', await failure(() => print.printPdf(pdfUri, '')))
    } catch (error) {
      outcome = `failed ${message(error)}`
    }
    try {
      for (const uri of [pdfUri, badUri]) {
        if ((await fs.getInfo(uri)).exists) await fs.delete(uri)
      }
    } catch (error) {
      outcome = `failed cleanup ${message(error)}`
    }
    setStatus(outcome)
  }

  return (
    <View style={styles.screen}>
      <Text>{`Status: ${status}`}</Text>
      {results.map(([name, value]) => <Text key={name}>{`${name}: ${value}`}</Text>)}
      <Pressable testID="one-native-print-run" style={styles.chip} onPress={run}>
        <Text>Run print checks</Text>
      </Pressable>
    </View>
  )
}

const styles = StyleSheet.create({
  screen: { flex: 1, padding: 16, gap: 6, backgroundColor: '#fff' },
  chip: { padding: 10, borderRadius: 8, backgroundColor: '#e5e7eb', alignSelf: 'flex-start' },
})
