// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ColorValue, ViewProps } from 'react-native'
import type { Double } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
interface NativeProps extends ViewProps {
  material?: string
  glassEffect?: string
  interactive?: boolean
  shape?: string
  cornerRadius?: Double
  tint?: ColorValue
}
export default codegenNativeComponent<NativeProps>('OneNativeGlass')
