// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ComponentProps } from 'react'
import { type HostComponent, NativeComponentRegistry } from 'react-native'

type NativeProps = ComponentProps<
  typeof import('./OneNativeTabsNativeComponent').default
>

const TabsNative: HostComponent<NativeProps> =
  NativeComponentRegistry.get<NativeProps>('OneNativeTabs', () => ({
    uiViewClassName: 'OneNativeTabs',
    directEventTypes: {
      topNativeTabsSelectionChange: {
        registrationName: 'onNativeTabsSelectionChange',
      },
      topNativeTabsAction: { registrationName: 'onNativeTabsAction' },
    },
    validAttributes: {
      selection: true,
      sidebarAdaptable: true,
      tabBarMinimizeBehavior: true,
      acknowledgedEvent: true,
      revision: true,
      onNativeTabsSelectionChange: true,
      onNativeTabsAction: true,
    },
  }))

export default TabsNative
