// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ColorValue, ViewProps } from 'react-native'
import type { Double } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
interface NativeProps extends ViewProps {
  axis: string
  spacing: Double
  alignment: string
  colorScheme: string
  dynamicTypeSize: string
  locale: string
  tint?: ColorValue
  isEnabled: string
}
export default codegenNativeComponent<NativeProps>('OneNativeHost', {
  interfaceOnly: true,
})
