// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ComponentProps } from 'react'
import { type HostComponent, NativeComponentRegistry } from 'react-native'

type NativeProps = ComponentProps<
  typeof import('./OneNativeTabNativeComponent').default
>

const OneNativeTab: HostComponent<NativeProps> =
  NativeComponentRegistry.get<NativeProps>('OneNativeTab', () => ({
    uiViewClassName: 'OneNativeTab',
    validAttributes: {
      tabId: true,
      title: true,
      systemImage: true,
      badge: true,
      tabRole: true,
      action: true,
    },
  }))

export default OneNativeTab
