// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ComponentProps } from 'react'
import { type HostComponent, NativeComponentRegistry } from 'react-native'

type NativeProps = ComponentProps<
  typeof import('./OneNativeMenuNativeComponent').default
>

const MenuNative: HostComponent<NativeProps> =
  NativeComponentRegistry.get<NativeProps>('OneNativeMenu', () => ({
    uiViewClassName: 'OneNativeMenu',
    directEventTypes: {
      topNativeMenuAction: { registrationName: 'onNativeMenuAction' },
      topNativeMenuValueChange: {
        registrationName: 'onNativeMenuValueChange',
      },
    },
    validAttributes: {
      items: true,
      triggerLabel: true,
      disabled: true,
      menuOrder: true,
      menuActionDismissBehavior: true,
      presentation: true,
      acknowledgedEvent: true,
      revision: true,
      onNativeMenuAction: true,
      onNativeMenuValueChange: true,
    },
  }))

export default MenuNative
