// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type {
  DirectEventHandler,
  Int32,
  Double,
} from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'

interface NativeProps extends ViewProps {
  listStyle: string
  listRowSeparator: string
  listRowSeparatorEdges: string
  listRowInsetsTop: Double
  listRowInsetsLeading: Double
  listRowInsetsBottom: Double
  listRowInsetsTrailing: Double
  listSectionSpacing: string
  listSectionSpacingValue: Double
  listSectionMarginsLength: Double
  listSectionMarginsEdges: string
  headerProminence: string
}
export default codegenNativeComponent<NativeProps>('OneNativeList')
