// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import SwiftUI
import UIKit
import PassKit
import StoreKit

public struct OneNativeStyle: Equatable {
  public var fontSize: CGFloat?
  public var fontWeight: String?
  public var fontDesign: String?
  public var textStyle: String?
  public var foregroundStyle: UIColor?
  public var tint: UIColor?
  public var background: UIColor?
  public var padding: CGFloat?
  public var paddingTop: CGFloat?
  public var paddingLeading: CGFloat?
  public var paddingBottom: CGFloat?
  public var paddingTrailing: CGFloat?
  public var width: CGFloat?
  public var height: CGFloat?
  public var minWidth: CGFloat?
  public var idealWidth: CGFloat?
  public var maxWidth: CGFloat?
  public var minHeight: CGFloat?
  public var idealHeight: CGFloat?
  public var maxHeight: CGFloat?
  public var cornerRadius: CGFloat?
  public var opacity: CGFloat?
  public var borderColor: UIColor?
  public var borderWidth: CGFloat?
  public var glassEffect: String?
  public var glassEffectInteractive: Bool?
  public var glassEffectTint: UIColor?
  public var glassEffectShape: String?
  public var material: String?
  public var sdkModifiers: [[String]] = []

  public init() {}

  public init(dictionary: [String: Any]) {
    if let v = dictionary["fontSize"] as? Double { self.fontSize = CGFloat(v) }
    if let v = dictionary["fontWeight"] as? String, !v.isEmpty { self.fontWeight = v }
    if let v = dictionary["fontDesign"] as? String, !v.isEmpty { self.fontDesign = v }
    if let v = dictionary["textStyle"] as? String, !v.isEmpty { self.textStyle = v }
    if let v = dictionary["foregroundStyle"] as? UIColor { self.foregroundStyle = v }
    if let v = dictionary["tint"] as? UIColor { self.tint = v }
    if let v = dictionary["background"] as? UIColor { self.background = v }
    if let v = dictionary["padding"] as? Double { self.padding = CGFloat(v) }
    if let v = dictionary["paddingTop"] as? Double { self.paddingTop = CGFloat(v) }
    if let v = dictionary["paddingLeading"] as? Double { self.paddingLeading = CGFloat(v) }
    if let v = dictionary["paddingBottom"] as? Double { self.paddingBottom = CGFloat(v) }
    if let v = dictionary["paddingTrailing"] as? Double { self.paddingTrailing = CGFloat(v) }
    if let v = dictionary["width"] as? Double { self.width = CGFloat(v) }
    if let v = dictionary["height"] as? Double { self.height = CGFloat(v) }
    if let v = dictionary["minWidth"] as? Double { self.minWidth = CGFloat(v) }
    if let v = dictionary["idealWidth"] as? Double { self.idealWidth = CGFloat(v) }
    if let v = dictionary["maxWidth"] as? Double { self.maxWidth = CGFloat(v) }
    if let v = dictionary["minHeight"] as? Double { self.minHeight = CGFloat(v) }
    if let v = dictionary["idealHeight"] as? Double { self.idealHeight = CGFloat(v) }
    if let v = dictionary["maxHeight"] as? Double { self.maxHeight = CGFloat(v) }
    if let v = dictionary["cornerRadius"] as? Double { self.cornerRadius = CGFloat(v) }
    if let v = dictionary["opacity"] as? Double { self.opacity = CGFloat(v) }
    if let v = dictionary["borderColor"] as? UIColor { self.borderColor = v }
    if let v = dictionary["borderWidth"] as? Double { self.borderWidth = CGFloat(v) }
    if let v = dictionary["glassEffect"] as? String, !v.isEmpty { self.glassEffect = v }
    if let v = dictionary["glassEffectInteractive"] as? Bool { self.glassEffectInteractive = v }
    if let v = dictionary["glassEffectTint"] as? UIColor { self.glassEffectTint = v }
    if let v = dictionary["glassEffectShape"] as? String, !v.isEmpty { self.glassEffectShape = v }
    if let v = dictionary["material"] as? String, !v.isEmpty { self.material = v }
    if let json = dictionary["sdkModifiers"] as? String {
      guard let data = json.data(using: .utf8),
        let pairs = try? JSONDecoder().decode([[String]].self, from: data),
        pairs.allSatisfy({ $0.count == 2 }) else {
        preconditionFailure("invalid sdk modifiers")
      }
      sdkModifiers = pairs
    }
  }
}

extension View {
  public func oneNativeStyle(_ style: OneNativeStyle, emit: @escaping (String, String) -> Void = { _, _ in }) -> some View {
    var view = AnyView(self
      .oneNativeFont(style)
      .oneNativeForegroundStyle(style.foregroundStyle)
      .oneNativeTint(style.tint)
      .oneNativePadding(style)
      .oneNativeFrame(style)
      .oneNativeBackground(style.background)
      .oneNativeGlassEffect(style)
      .oneNativeCornerRadius(style.cornerRadius)
      .oneNativeOpacity(style.opacity)
      .oneNativeBorder(color: style.borderColor, width: style.borderWidth))
    for pair in style.sdkModifiers {
      let name = pair[0]
      let value = pair[1]
      switch name {
      case "accessibilityShowsLargeContentViewer": view = AnyView(view.oneNativeSDKAccessibilityShowsLargeContentViewer(value, emit: emit))
      case "allowsHitTesting": view = AnyView(view.oneNativeSDKAllowsHitTesting(value, emit: emit))
      case "allowsTightening": view = AnyView(view.oneNativeSDKAllowsTightening(value, emit: emit))
      case "allowsWindowActivationEvents": view = AnyView(view.oneNativeSDKAllowsWindowActivationEvents(value, emit: emit))
      case "autocorrectionDisabled": view = AnyView(view.oneNativeSDKAutocorrectionDisabled(value, emit: emit))
      case "backgroundExtensionEffect": view = AnyView(view.oneNativeSDKBackgroundExtensionEffect(value, emit: emit))
      case "badge": view = AnyView(view.oneNativeSDKBadge(value, emit: emit))
      case "badgeProminence": view = AnyView(view.oneNativeSDKBadgeProminence(value, emit: emit))
      case "baselineOffset": view = AnyView(view.oneNativeSDKBaselineOffset(value, emit: emit))
      case "blendMode": view = AnyView(view.oneNativeSDKBlendMode(value, emit: emit))
      case "bold": view = AnyView(view.oneNativeSDKBold(value, emit: emit))
      case "brightness": view = AnyView(view.oneNativeSDKBrightness(value, emit: emit))
      case "buttonBorderShape": view = AnyView(view.oneNativeSDKButtonBorderShape(value, emit: emit))
      case "buttonRepeatBehavior": view = AnyView(view.oneNativeSDKButtonRepeatBehavior(value, emit: emit))
      case "buttonSizing": view = AnyView(view.oneNativeSDKButtonSizing(value, emit: emit))
      case "colorInvert": view = AnyView(view.oneNativeSDKColorInvert(value, emit: emit))
      case "colorMultiply": view = AnyView(view.oneNativeSDKColorMultiply(value, emit: emit))
      case "colorScheme": view = AnyView(view.oneNativeSDKColorScheme(value, emit: emit))
      case "compositingGroup": view = AnyView(view.oneNativeSDKCompositingGroup(value, emit: emit))
      case "contentTransition": view = AnyView(view.oneNativeSDKContentTransition(value, emit: emit))
      case "contrast": view = AnyView(view.oneNativeSDKContrast(value, emit: emit))
      case "controlSize": view = AnyView(view.oneNativeSDKControlSize(value, emit: emit))
      case "defaultAdaptableTabBarPlacement": view = AnyView(view.oneNativeSDKDefaultAdaptableTabBarPlacement(value, emit: emit))
      case "defaultTabBarPlacement": view = AnyView(view.oneNativeSDKDefaultTabBarPlacement(value, emit: emit))
      case "deleteDisabled": view = AnyView(view.oneNativeSDKDeleteDisabled(value, emit: emit))
      case "dialogSuppressionToggle": view = AnyView(view.oneNativeSDKDialogSuppressionToggle(value, emit: emit))
      case "disabled": view = AnyView(view.oneNativeSDKDisabled(value, emit: emit))
      case "dynamicTypeSize": view = AnyView(view.oneNativeSDKDynamicTypeSize(value, emit: emit))
      case "edgesIgnoringSafeArea": view = AnyView(view.oneNativeSDKEdgesIgnoringSafeArea(value, emit: emit))
      case "fileDialogBrowserOptions": view = AnyView(view.oneNativeSDKFileDialogBrowserOptions(value, emit: emit))
      case "fileDialogCustomizationID": view = AnyView(view.oneNativeSDKFileDialogCustomizationID(value, emit: emit))
      case "fileDialogImportsUnresolvedAliases": view = AnyView(view.oneNativeSDKFileDialogImportsUnresolvedAliases(value, emit: emit))
      case "findDisabled": view = AnyView(view.oneNativeSDKFindDisabled(value, emit: emit))
      case "findNavigator": view = AnyView(view.oneNativeSDKFindNavigator(value, emit: emit))
      case "fixedSize": view = AnyView(view.oneNativeSDKFixedSize(value, emit: emit))
      case "flipsForRightToLeftLayoutDirection": view = AnyView(view.oneNativeSDKFlipsForRightToLeftLayoutDirection(value, emit: emit))
      case "focusable": view = AnyView(view.oneNativeSDKFocusable(value, emit: emit))
      case "focusEffectDisabled": view = AnyView(view.oneNativeSDKFocusEffectDisabled(value, emit: emit))
      case "geometryGroup": view = AnyView(view.oneNativeSDKGeometryGroup(value, emit: emit))
      case "glassEffectTransition": view = AnyView(view.oneNativeSDKGlassEffectTransition(value, emit: emit))
      case "grayscale": view = AnyView(view.oneNativeSDKGrayscale(value, emit: emit))
      case "gridCellAnchor": view = AnyView(view.oneNativeSDKGridCellAnchor(value, emit: emit))
      case "gridCellColumns": view = AnyView(view.oneNativeSDKGridCellColumns(value, emit: emit))
      case "gridCellUnsizedAxes": view = AnyView(view.oneNativeSDKGridCellUnsizedAxes(value, emit: emit))
      case "gridColumnAlignment": view = AnyView(view.oneNativeSDKGridColumnAlignment(value, emit: emit))
      case "headerProminence": view = AnyView(view.oneNativeSDKHeaderProminence(value, emit: emit))
      case "hidden": view = AnyView(view.oneNativeSDKHidden(value, emit: emit))
      case "hoverEffect": view = AnyView(view.oneNativeSDKHoverEffect(value, emit: emit))
      case "hoverEffectDisabled": view = AnyView(view.oneNativeSDKHoverEffectDisabled(value, emit: emit))
      case "hueRotation": view = AnyView(view.oneNativeSDKHueRotation(value, emit: emit))
      case "inspectorColumnWidth": view = AnyView(view.oneNativeSDKInspectorColumnWidth(value, emit: emit))
      case "interactionActivityTrackingTag": view = AnyView(view.oneNativeSDKInteractionActivityTrackingTag(value, emit: emit))
      case "interactiveDismissDisabled": view = AnyView(view.oneNativeSDKInteractiveDismissDisabled(value, emit: emit))
      case "invalidatableContent": view = AnyView(view.oneNativeSDKInvalidatableContent(value, emit: emit))
      case "italic": view = AnyView(view.oneNativeSDKItalic(value, emit: emit))
      case "kerning": view = AnyView(view.oneNativeSDKKerning(value, emit: emit))
      case "keyboardShortcut": view = AnyView(view.oneNativeSDKKeyboardShortcut(value, emit: emit))
      case "labelIconToTitleSpacing": view = AnyView(view.oneNativeSDKLabelIconToTitleSpacing(value, emit: emit))
      case "labelReservedIconWidth": view = AnyView(view.oneNativeSDKLabelReservedIconWidth(value, emit: emit))
      case "labelsHidden": view = AnyView(view.oneNativeSDKLabelsHidden(value, emit: emit))
      case "labelsVisibility": view = AnyView(view.oneNativeSDKLabelsVisibility(value, emit: emit))
      case "layoutDirectionBehavior": view = AnyView(view.oneNativeSDKLayoutDirectionBehavior(value, emit: emit))
      case "layoutPriority": view = AnyView(view.oneNativeSDKLayoutPriority(value, emit: emit))
      case "lineSpacing": view = AnyView(view.oneNativeSDKLineSpacing(value, emit: emit))
      case "listSectionIndexVisibility": view = AnyView(view.oneNativeSDKListSectionIndexVisibility(value, emit: emit))
      case "luminanceToAlpha": view = AnyView(view.oneNativeSDKLuminanceToAlpha(value, emit: emit))
      case "materialActiveAppearance": view = AnyView(view.oneNativeSDKMaterialActiveAppearance(value, emit: emit))
      case "menuActionDismissBehavior": view = AnyView(view.oneNativeSDKMenuActionDismissBehavior(value, emit: emit))
      case "menuIndicator": view = AnyView(view.oneNativeSDKMenuIndicator(value, emit: emit))
      case "menuOrder": view = AnyView(view.oneNativeSDKMenuOrder(value, emit: emit))
      case "minimumScaleFactor": view = AnyView(view.oneNativeSDKMinimumScaleFactor(value, emit: emit))
      case "monospaced": view = AnyView(view.oneNativeSDKMonospaced(value, emit: emit))
      case "monospacedDigit": view = AnyView(view.oneNativeSDKMonospacedDigit(value, emit: emit))
      case "moveDisabled": view = AnyView(view.oneNativeSDKMoveDisabled(value, emit: emit))
      case "multilineTextAlignment": view = AnyView(view.oneNativeSDKMultilineTextAlignment(value, emit: emit))
      case "navigationBarBackButtonHidden": view = AnyView(view.oneNativeSDKNavigationBarBackButtonHidden(value, emit: emit))
      case "navigationBarHidden": view = AnyView(view.oneNativeSDKNavigationBarHidden(value, emit: emit))
      case "navigationLinkIndicatorVisibility": view = AnyView(view.oneNativeSDKNavigationLinkIndicatorVisibility(value, emit: emit))
      case "navigationSplitViewColumnWidth": view = AnyView(view.oneNativeSDKNavigationSplitViewColumnWidth(value, emit: emit))
      case "navigationTitle": view = AnyView(view.oneNativeSDKNavigationTitle(value, emit: emit))
      case "onAppear": view = AnyView(view.oneNativeSDKOnAppear(value, emit: emit))
      case "onDisappear": view = AnyView(view.oneNativeSDKOnDisappear(value, emit: emit))
      case "onSubmit": view = AnyView(view.oneNativeSDKOnSubmit(value, emit: emit))
      case "onTapGesture": view = AnyView(view.oneNativeSDKOnTapGesture(value, emit: emit))
      case "paletteSelectionEffect": view = AnyView(view.oneNativeSDKPaletteSelectionEffect(value, emit: emit))
      case "payWithApplePayButtonDisableCardArt": view = AnyView(view.oneNativeSDKPayWithApplePayButtonDisableCardArt(value, emit: emit))
      case "persistentSystemOverlays": view = AnyView(view.oneNativeSDKPersistentSystemOverlays(value, emit: emit))
      case "presentationBackgroundInteraction": view = AnyView(view.oneNativeSDKPresentationBackgroundInteraction(value, emit: emit))
      case "presentationCompactAdaptation": view = AnyView(view.oneNativeSDKPresentationCompactAdaptation(value, emit: emit))
      case "presentationContentInteraction": view = AnyView(view.oneNativeSDKPresentationContentInteraction(value, emit: emit))
      case "presentationDragIndicator": view = AnyView(view.oneNativeSDKPresentationDragIndicator(value, emit: emit))
      case "presentationPlacement": view = AnyView(view.oneNativeSDKPresentationPlacement(value, emit: emit))
      case "previewInterfaceOrientation": view = AnyView(view.oneNativeSDKPreviewInterfaceOrientation(value, emit: emit))
      case "privacySensitive": view = AnyView(view.oneNativeSDKPrivacySensitive(value, emit: emit))
      case "productIconBorder": view = AnyView(view.oneNativeSDKProductIconBorder(value, emit: emit))
      case "renameAction": view = AnyView(view.oneNativeSDKRenameAction(value, emit: emit))
      case "replaceDisabled": view = AnyView(view.oneNativeSDKReplaceDisabled(value, emit: emit))
      case "safeAreaPadding": view = AnyView(view.oneNativeSDKSafeAreaPadding(value, emit: emit))
      case "saturation": view = AnyView(view.oneNativeSDKSaturation(value, emit: emit))
      case "scaledToFill": view = AnyView(view.oneNativeSDKScaledToFill(value, emit: emit))
      case "scaledToFit": view = AnyView(view.oneNativeSDKScaledToFit(value, emit: emit))
      case "scenePadding": view = AnyView(view.oneNativeSDKScenePadding(value, emit: emit))
      case "scrollClipDisabled": view = AnyView(view.oneNativeSDKScrollClipDisabled(value, emit: emit))
      case "scrollContentBackground": view = AnyView(view.oneNativeSDKScrollContentBackground(value, emit: emit))
      case "scrollDisabled": view = AnyView(view.oneNativeSDKScrollDisabled(value, emit: emit))
      case "scrollDismissesKeyboard": view = AnyView(view.oneNativeSDKScrollDismissesKeyboard(value, emit: emit))
      case "searchable": view = AnyView(view.oneNativeSDKSearchable(value, emit: emit))
      case "searchCompletion": view = AnyView(view.oneNativeSDKSearchCompletion(value, emit: emit))
      case "searchDictationBehavior": view = AnyView(view.oneNativeSDKSearchDictationBehavior(value, emit: emit))
      case "searchPresentationToolbarBehavior": view = AnyView(view.oneNativeSDKSearchPresentationToolbarBehavior(value, emit: emit))
      case "searchToolbarBehavior": view = AnyView(view.oneNativeSDKSearchToolbarBehavior(value, emit: emit))
      case "selectionDisabled": view = AnyView(view.oneNativeSDKSelectionDisabled(value, emit: emit))
      case "sliderThumbVisibility": view = AnyView(view.oneNativeSDKSliderThumbVisibility(value, emit: emit))
      case "speechAdjustedPitch": view = AnyView(view.oneNativeSDKSpeechAdjustedPitch(value, emit: emit))
      case "speechAlwaysIncludesPunctuation": view = AnyView(view.oneNativeSDKSpeechAlwaysIncludesPunctuation(value, emit: emit))
      case "speechAnnouncementsQueued": view = AnyView(view.oneNativeSDKSpeechAnnouncementsQueued(value, emit: emit))
      case "speechSpellsOutCharacters": view = AnyView(view.oneNativeSDKSpeechSpellsOutCharacters(value, emit: emit))
      case "springLoadingBehavior": view = AnyView(view.oneNativeSDKSpringLoadingBehavior(value, emit: emit))
      case "statusBarHidden": view = AnyView(view.oneNativeSDKStatusBarHidden(value, emit: emit))
      case "submitLabel": view = AnyView(view.oneNativeSDKSubmitLabel(value, emit: emit))
      case "submitScope": view = AnyView(view.oneNativeSDKSubmitScope(value, emit: emit))
      case "swipeActionsContainer": view = AnyView(view.oneNativeSDKSwipeActionsContainer(value, emit: emit))
      case "symbolEffectsRemoved": view = AnyView(view.oneNativeSDKSymbolEffectsRemoved(value, emit: emit))
      case "symbolVariant": view = AnyView(view.oneNativeSDKSymbolVariant(value, emit: emit))
      case "tabBarMinimizeBehavior": view = AnyView(view.oneNativeSDKTabBarMinimizeBehavior(value, emit: emit))
      case "tableColumnHeaders": view = AnyView(view.oneNativeSDKTableColumnHeaders(value, emit: emit))
      case "tabViewSearchActivation": view = AnyView(view.oneNativeSDKTabViewSearchActivation(value, emit: emit))
      case "textInputBorderShape": view = AnyView(view.oneNativeSDKTextInputBorderShape(value, emit: emit))
      case "textSelectionAffinity": view = AnyView(view.oneNativeSDKTextSelectionAffinity(value, emit: emit))
      case "toolbarRole": view = AnyView(view.oneNativeSDKToolbarRole(value, emit: emit))
      case "toolbarTitleDisplayMode": view = AnyView(view.oneNativeSDKToolbarTitleDisplayMode(value, emit: emit))
      case "tracking": view = AnyView(view.oneNativeSDKTracking(value, emit: emit))
      case "transition": view = AnyView(view.oneNativeSDKTransition(value, emit: emit))
      case "unredacted": view = AnyView(view.oneNativeSDKUnredacted(value, emit: emit))
      case "windowToolbarFullScreenVisibility": view = AnyView(view.oneNativeSDKWindowToolbarFullScreenVisibility(value, emit: emit))
      case "writingToolsAffordanceVisibility": view = AnyView(view.oneNativeSDKWritingToolsAffordanceVisibility(value, emit: emit))
      case "writingToolsBehavior": view = AnyView(view.oneNativeSDKWritingToolsBehavior(value, emit: emit))
      case "zIndex": view = AnyView(view.oneNativeSDKZIndex(value, emit: emit))
      default: preconditionFailure("unknown sdk modifier: \(name)")
      }
    }
    return view
  }

  @ViewBuilder fileprivate func oneNativeFont(_ style: OneNativeStyle) -> some View {
    if let font = style.resolveFont() {
      self.font(font)
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeForegroundStyle(_ color: UIColor?) -> some View {
    if let color = color {
      self.foregroundStyle(Color(uiColor: color))
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeTint(_ color: UIColor?) -> some View {
    if let color = color {
      self.tint(Color(uiColor: color))
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativePadding(_ style: OneNativeStyle) -> some View {
    if let p = style.padding {
      if p < 0 {
        preconditionFailure("invalid padding: \(p)")
      }
      self.padding(p)
    } else if style.paddingTop != nil || style.paddingLeading != nil || style.paddingBottom != nil || style.paddingTrailing != nil {
      let top = style.paddingTop ?? 0
      let leading = style.paddingLeading ?? 0
      let bottom = style.paddingBottom ?? 0
      let trailing = style.paddingTrailing ?? 0
      if top < 0 || leading < 0 || bottom < 0 || trailing < 0 {
        preconditionFailure("invalid padding insets: (\(top), \(leading), \(bottom), \(trailing))")
      }
      self.padding(EdgeInsets(top: top, leading: leading, bottom: bottom, trailing: trailing))
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeFrame(_ style: OneNativeStyle) -> some View {
    let hasExact = style.width != nil || style.height != nil
    let hasFlexible = style.minWidth != nil || style.idealWidth != nil || style.maxWidth != nil ||
                      style.minHeight != nil || style.idealHeight != nil || style.maxHeight != nil
    if hasExact && hasFlexible {
      self.frame(
        minWidth: style.minWidth,
        idealWidth: style.idealWidth,
        maxWidth: style.maxWidth,
        minHeight: style.minHeight,
        idealHeight: style.idealHeight,
        maxHeight: style.maxHeight
      ).frame(width: style.width, height: style.height)
    } else if hasExact {
      self.frame(width: style.width, height: style.height)
    } else if hasFlexible {
      self.frame(
        minWidth: style.minWidth,
        idealWidth: style.idealWidth,
        maxWidth: style.maxWidth,
        minHeight: style.minHeight,
        idealHeight: style.idealHeight,
        maxHeight: style.maxHeight
      )
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeBackground(_ color: UIColor?) -> some View {
    if let color = color {
      self.background(Color(uiColor: color))
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeCornerRadius(_ radius: CGFloat?) -> some View {
    if let radius = radius {
      if radius < 0 {
        preconditionFailure("invalid cornerRadius: \(radius)")
      }
      self.clipShape(RoundedRectangle(cornerRadius: radius))
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeOpacity(_ opacity: CGFloat?) -> some View {
    if let opacity = opacity {
      if opacity < 0.0 || opacity > 1.0 {
        preconditionFailure("invalid opacity: \(opacity)")
      }
      self.opacity(Double(opacity))
    } else {
      self
    }
  }

  @ViewBuilder fileprivate func oneNativeBorder(color: UIColor?, width: CGFloat?) -> some View {
    if let color = color {
      let w = width ?? 1
      if w < 0 {
        preconditionFailure("invalid borderWidth: \(w)")
      }
      self.border(Color(uiColor: color), width: w)
    } else if let width = width {
      if width < 0 {
        preconditionFailure("invalid borderWidth: \(width)")
      }
      self
    } else {
      self
    }
  }
}

extension OneNativeStyle {
  func resolveFont() -> Font? {
    let weight = fontWeight.map(OneNativeStyle.resolveWeight)
    let design = fontDesign.map(OneNativeStyle.resolveDesign)

    if let size = fontSize {
      if size <= 0 {
        preconditionFailure("invalid fontSize: \(size)")
      }
      return Font.system(size: size, weight: weight, design: design)
    }
    if let textStyleStr = textStyle {
      let textStyle = OneNativeStyle.resolveTextStyle(textStyleStr)
      return Font.system(textStyle, design: design, weight: weight)
    }
    if weight != nil || design != nil {
      return Font.system(size: UIFont.buttonFontSize, weight: weight, design: design)
    }
    return nil
  }

  static func resolveWeight(_ string: String) -> Font.Weight {
    switch string.lowercased() {
    case "ultralight": return .ultraLight
    case "thin": return .thin
    case "light": return .light
    case "regular": return .regular
    case "medium": return .medium
    case "semibold": return .semibold
    case "bold": return .bold
    case "heavy": return .heavy
    case "black": return .black
    default: preconditionFailure("invalid FontWeight: \(string)")
    }
  }

  static func resolveDesign(_ string: String) -> Font.Design {
    switch string.lowercased() {
    case "default": return .default
    case "serif": return .serif
    case "rounded": return .rounded
    case "monospaced": return .monospaced
    default: preconditionFailure("invalid FontDesign: \(string)")
    }
  }

  static func resolveTextStyle(_ string: String) -> Font.TextStyle {
    switch string.lowercased() {
    case "largetitle": return .largeTitle
    case "title": return .title
    case "title2": return .title2
    case "title3": return .title3
    case "headline": return .headline
    case "subheadline": return .subheadline
    case "body": return .body
    case "callout": return .callout
    case "footnote": return .footnote
    case "caption": return .caption
    case "caption2": return .caption2
    default: preconditionFailure("invalid TextStyle: \(string)")
    }
  }
}

extension View {
  @ViewBuilder fileprivate func oneNativeSDKAccessibilityShowsLargeContentViewer(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid accessibilityShowsLargeContentViewer: \(value)")
    if value == "true" { self.accessibilityShowsLargeContentViewer() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKAllowsHitTesting(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid allowsHitTesting: \(value)")
      self.allowsHitTesting(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKAllowsTightening(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid allowsTightening: \(value)")
      self.allowsTightening(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKAllowsWindowActivationEvents(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid allowsWindowActivationEvents: \(value)")
    if value == "true" { if #available(iOS 18, *) { self.allowsWindowActivationEvents() } else { self } } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKAutocorrectionDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid autocorrectionDisabled: \(value)")
      self.autocorrectionDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKBackgroundExtensionEffect(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid backgroundExtensionEffect: \(value)")
    if value == "true" { if #available(iOS 26, *) { self.backgroundExtensionEffect() } else { self } } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKBadge(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.badge(Int(number))
      } else { preconditionFailure("invalid badge: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKBadgeProminence(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "decreased": self.badgeProminence(.decreased)
      case "standard": self.badgeProminence(.standard)
      case "increased": self.badgeProminence(.increased)
    default: preconditionFailure("invalid badgeProminence: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKBaselineOffset(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.baselineOffset(CGFloat(number))
      } else { preconditionFailure("invalid baselineOffset: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKBlendMode(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "normal": self.blendMode(.normal)
      case "multiply": self.blendMode(.multiply)
      case "screen": self.blendMode(.screen)
      case "overlay": self.blendMode(.overlay)
      case "darken": self.blendMode(.darken)
      case "lighten": self.blendMode(.lighten)
      case "colorDodge": self.blendMode(.colorDodge)
      case "colorBurn": self.blendMode(.colorBurn)
      case "softLight": self.blendMode(.softLight)
      case "hardLight": self.blendMode(.hardLight)
      case "difference": self.blendMode(.difference)
      case "exclusion": self.blendMode(.exclusion)
      case "hue": self.blendMode(.hue)
      case "saturation": self.blendMode(.saturation)
      case "color": self.blendMode(.color)
      case "luminosity": self.blendMode(.luminosity)
      case "sourceAtop": self.blendMode(.sourceAtop)
      case "destinationOver": self.blendMode(.destinationOver)
      case "destinationOut": self.blendMode(.destinationOut)
      case "plusDarker": self.blendMode(.plusDarker)
      case "plusLighter": self.blendMode(.plusLighter)
    default: preconditionFailure("invalid blendMode: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKBold(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid bold: \(value)")
      self.bold(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKBrightness(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.brightness(number)
      } else { preconditionFailure("invalid brightness: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKButtonBorderShape(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.buttonBorderShape(.automatic)
      case "capsule": self.buttonBorderShape(.capsule)
      case "roundedRectangle": self.buttonBorderShape(.roundedRectangle)
      case "circle": self.buttonBorderShape(.circle)
    default: preconditionFailure("invalid buttonBorderShape: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKButtonRepeatBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.buttonRepeatBehavior(.automatic)
      case "enabled": self.buttonRepeatBehavior(.enabled)
      case "disabled": self.buttonRepeatBehavior(.disabled)
    default: preconditionFailure("invalid buttonRepeatBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKButtonSizing(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 26, *) { self.buttonSizing(.automatic) } else { self }
      case "flexible": if #available(iOS 26, *) { self.buttonSizing(.flexible) } else { self }
      case "fitted": if #available(iOS 26, *) { self.buttonSizing(.fitted) } else { self }
    default: preconditionFailure("invalid buttonSizing: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKColorInvert(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid colorInvert: \(value)")
    if value == "true" { self.colorInvert() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKColorMultiply(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "accentColor": self.colorMultiply(.accentColor)
      case "red": self.colorMultiply(.red)
      case "orange": self.colorMultiply(.orange)
      case "yellow": self.colorMultiply(.yellow)
      case "green": self.colorMultiply(.green)
      case "mint": self.colorMultiply(.mint)
      case "teal": self.colorMultiply(.teal)
      case "cyan": self.colorMultiply(.cyan)
      case "blue": self.colorMultiply(.blue)
      case "indigo": self.colorMultiply(.indigo)
      case "purple": self.colorMultiply(.purple)
      case "pink": self.colorMultiply(.pink)
      case "brown": self.colorMultiply(.brown)
      case "white": self.colorMultiply(.white)
      case "gray": self.colorMultiply(.gray)
      case "black": self.colorMultiply(.black)
      case "clear": self.colorMultiply(.clear)
      case "primary": self.colorMultiply(.primary)
      case "secondary": self.colorMultiply(.secondary)
    default: preconditionFailure("invalid colorMultiply: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKColorScheme(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "light": self.colorScheme(.light)
      case "dark": self.colorScheme(.dark)
    default: preconditionFailure("invalid colorScheme: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKCompositingGroup(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid compositingGroup: \(value)")
    if value == "true" { self.compositingGroup() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKContentTransition(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "symbolEffect": self.contentTransition(.symbolEffect)
      case "identity": self.contentTransition(.identity)
      case "opacity": self.contentTransition(.opacity)
      case "interpolate": self.contentTransition(.interpolate)
    default: preconditionFailure("invalid contentTransition: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKContrast(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.contrast(number)
      } else { preconditionFailure("invalid contrast: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKControlSize(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "mini": self.controlSize(.mini)
      case "small": self.controlSize(.small)
      case "regular": self.controlSize(.regular)
      case "large": self.controlSize(.large)
      case "extraLarge": self.controlSize(.extraLarge)
    default: preconditionFailure("invalid controlSize: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKDefaultAdaptableTabBarPlacement(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18, *) { self.defaultAdaptableTabBarPlacement(.automatic) } else { self }
      case "tabBar": if #available(iOS 18, *) { self.defaultAdaptableTabBarPlacement(.tabBar) } else { self }
      case "sidebar": if #available(iOS 18, *) { self.defaultAdaptableTabBarPlacement(.sidebar) } else { self }
    default: preconditionFailure("invalid defaultAdaptableTabBarPlacement: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKDefaultTabBarPlacement(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 27, *) { self.defaultTabBarPlacement(.automatic) } else { self }
      case "tabBar": if #available(iOS 27, *) { self.defaultTabBarPlacement(.tabBar) } else { self }
      case "sidebar": if #available(iOS 27, *) { self.defaultTabBarPlacement(.sidebar) } else { self }
    default: preconditionFailure("invalid defaultTabBarPlacement: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKDeleteDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid deleteDisabled: \(value)")
      self.deleteDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKDialogSuppressionToggle(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid dialogSuppressionToggle: \(value)")
    self.dialogSuppressionToggle(isSuppressed: Binding(get: { value == "true" }, set: { emit("dialogSuppressionToggle", String($0)) }))
  }

  @ViewBuilder fileprivate func oneNativeSDKDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid disabled: \(value)")
      self.disabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKDynamicTypeSize(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "xSmall": self.dynamicTypeSize(.xSmall)
      case "small": self.dynamicTypeSize(.small)
      case "medium": self.dynamicTypeSize(.medium)
      case "large": self.dynamicTypeSize(.large)
      case "xLarge": self.dynamicTypeSize(.xLarge)
      case "xxLarge": self.dynamicTypeSize(.xxLarge)
      case "xxxLarge": self.dynamicTypeSize(.xxxLarge)
      case "accessibility1": self.dynamicTypeSize(.accessibility1)
      case "accessibility2": self.dynamicTypeSize(.accessibility2)
      case "accessibility3": self.dynamicTypeSize(.accessibility3)
      case "accessibility4": self.dynamicTypeSize(.accessibility4)
      case "accessibility5": self.dynamicTypeSize(.accessibility5)
    default: preconditionFailure("invalid dynamicTypeSize: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKEdgesIgnoringSafeArea(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "top": self.edgesIgnoringSafeArea(.top)
      case "leading": self.edgesIgnoringSafeArea(.leading)
      case "bottom": self.edgesIgnoringSafeArea(.bottom)
      case "trailing": self.edgesIgnoringSafeArea(.trailing)
      case "all": self.edgesIgnoringSafeArea(.all)
      case "horizontal": self.edgesIgnoringSafeArea(.horizontal)
      case "vertical": self.edgesIgnoringSafeArea(.vertical)
    default: preconditionFailure("invalid edgesIgnoringSafeArea: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKFileDialogBrowserOptions(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "enumeratePackages": self.fileDialogBrowserOptions(.enumeratePackages)
      case "includeHiddenFiles": self.fileDialogBrowserOptions(.includeHiddenFiles)
      case "displayFileExtensions": self.fileDialogBrowserOptions(.displayFileExtensions)
    default: preconditionFailure("invalid fileDialogBrowserOptions: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKFileDialogCustomizationID(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      self.fileDialogCustomizationID(value)
  }

  @ViewBuilder fileprivate func oneNativeSDKFileDialogImportsUnresolvedAliases(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid fileDialogImportsUnresolvedAliases: \(value)")
      self.fileDialogImportsUnresolvedAliases(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKFindDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid findDisabled: \(value)")
      self.findDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKFindNavigator(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid findNavigator: \(value)")
    self.findNavigator(isPresented: Binding(get: { value == "true" }, set: { emit("findNavigator", String($0)) }))
  }

  @ViewBuilder fileprivate func oneNativeSDKFixedSize(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid fixedSize: \(value)")
    if value == "true" { self.fixedSize() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKFlipsForRightToLeftLayoutDirection(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid flipsForRightToLeftLayoutDirection: \(value)")
      self.flipsForRightToLeftLayoutDirection(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKFocusable(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid focusable: \(value)")
      self.focusable(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKFocusEffectDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid focusEffectDisabled: \(value)")
      self.focusEffectDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKGeometryGroup(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid geometryGroup: \(value)")
    if value == "true" { self.geometryGroup() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKGlassEffectTransition(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "matchedGeometry": if #available(iOS 26, *) { self.glassEffectTransition(.matchedGeometry) } else { self }
      case "materialize": if #available(iOS 26, *) { self.glassEffectTransition(.materialize) } else { self }
      case "identity": if #available(iOS 26, *) { self.glassEffectTransition(.identity) } else { self }
    default: preconditionFailure("invalid glassEffectTransition: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKGrayscale(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.grayscale(number)
      } else { preconditionFailure("invalid grayscale: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKGridCellAnchor(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "zero": self.gridCellAnchor(.zero)
      case "center": self.gridCellAnchor(.center)
      case "leading": self.gridCellAnchor(.leading)
      case "trailing": self.gridCellAnchor(.trailing)
      case "top": self.gridCellAnchor(.top)
      case "bottom": self.gridCellAnchor(.bottom)
      case "topLeading": self.gridCellAnchor(.topLeading)
      case "topTrailing": self.gridCellAnchor(.topTrailing)
      case "bottomLeading": self.gridCellAnchor(.bottomLeading)
      case "bottomTrailing": self.gridCellAnchor(.bottomTrailing)
    default: preconditionFailure("invalid gridCellAnchor: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKGridCellColumns(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.gridCellColumns(Int(number))
      } else { preconditionFailure("invalid gridCellColumns: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKGridCellUnsizedAxes(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "horizontal": self.gridCellUnsizedAxes(.horizontal)
      case "vertical": self.gridCellUnsizedAxes(.vertical)
    default: preconditionFailure("invalid gridCellUnsizedAxes: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKGridColumnAlignment(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "leading": self.gridColumnAlignment(.leading)
      case "center": self.gridColumnAlignment(.center)
      case "trailing": self.gridColumnAlignment(.trailing)
      case "listRowSeparatorLeading": self.gridColumnAlignment(.listRowSeparatorLeading)
      case "listRowSeparatorTrailing": self.gridColumnAlignment(.listRowSeparatorTrailing)
    default: preconditionFailure("invalid gridColumnAlignment: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKHeaderProminence(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "standard": self.headerProminence(.standard)
      case "increased": self.headerProminence(.increased)
    default: preconditionFailure("invalid headerProminence: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKHidden(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid hidden: \(value)")
    if value == "true" { self.hidden() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKHoverEffect(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.hoverEffect(.automatic)
      case "highlight": self.hoverEffect(.highlight)
      case "lift": self.hoverEffect(.lift)
    default: preconditionFailure("invalid hoverEffect: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKHoverEffectDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid hoverEffectDisabled: \(value)")
      self.hoverEffectDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKHueRotation(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "zero": self.hueRotation(.zero)
    default: preconditionFailure("invalid hueRotation: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKInspectorColumnWidth(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.inspectorColumnWidth(CGFloat(number))
      } else { preconditionFailure("invalid inspectorColumnWidth: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKInteractionActivityTrackingTag(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      self.interactionActivityTrackingTag(value)
  }

  @ViewBuilder fileprivate func oneNativeSDKInteractiveDismissDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid interactiveDismissDisabled: \(value)")
      self.interactiveDismissDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKInvalidatableContent(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid invalidatableContent: \(value)")
      self.invalidatableContent(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKItalic(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid italic: \(value)")
      self.italic(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKKerning(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.kerning(CGFloat(number))
      } else { preconditionFailure("invalid kerning: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKKeyboardShortcut(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "defaultAction": self.keyboardShortcut(.defaultAction)
      case "cancelAction": self.keyboardShortcut(.cancelAction)
    default: preconditionFailure("invalid keyboardShortcut: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKLabelIconToTitleSpacing(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        if #available(iOS 26, *) { self.labelIconToTitleSpacing(CGFloat(number)) } else { self }
      } else { preconditionFailure("invalid labelIconToTitleSpacing: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKLabelReservedIconWidth(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        if #available(iOS 26, *) { self.labelReservedIconWidth(CGFloat(number)) } else { self }
      } else { preconditionFailure("invalid labelReservedIconWidth: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKLabelsHidden(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid labelsHidden: \(value)")
    if value == "true" { self.labelsHidden() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKLabelsVisibility(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18, *) { self.labelsVisibility(.automatic) } else { self }
      case "visible": if #available(iOS 18, *) { self.labelsVisibility(.visible) } else { self }
      case "hidden": if #available(iOS 18, *) { self.labelsVisibility(.hidden) } else { self }
    default: preconditionFailure("invalid labelsVisibility: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKLayoutDirectionBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "fixed": self.layoutDirectionBehavior(.fixed)
      case "mirrors": self.layoutDirectionBehavior(.mirrors)
    default: preconditionFailure("invalid layoutDirectionBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKLayoutPriority(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.layoutPriority(number)
      } else { preconditionFailure("invalid layoutPriority: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKLineSpacing(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.lineSpacing(CGFloat(number))
      } else { preconditionFailure("invalid lineSpacing: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKListSectionIndexVisibility(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 26, *) { self.listSectionIndexVisibility(.automatic) } else { self }
      case "visible": if #available(iOS 26, *) { self.listSectionIndexVisibility(.visible) } else { self }
      case "hidden": if #available(iOS 26, *) { self.listSectionIndexVisibility(.hidden) } else { self }
    default: preconditionFailure("invalid listSectionIndexVisibility: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKLuminanceToAlpha(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid luminanceToAlpha: \(value)")
    if value == "true" { self.luminanceToAlpha() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKMaterialActiveAppearance(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18, *) { self.materialActiveAppearance(.automatic) } else { self }
      case "active": if #available(iOS 18, *) { self.materialActiveAppearance(.active) } else { self }
      case "matchWindow": if #available(iOS 18, *) { self.materialActiveAppearance(.matchWindow) } else { self }
    default: preconditionFailure("invalid materialActiveAppearance: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKMenuActionDismissBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.menuActionDismissBehavior(.automatic)
      case "enabled": self.menuActionDismissBehavior(.enabled)
      case "disabled": self.menuActionDismissBehavior(.disabled)
    default: preconditionFailure("invalid menuActionDismissBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKMenuIndicator(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.menuIndicator(.automatic)
      case "visible": self.menuIndicator(.visible)
      case "hidden": self.menuIndicator(.hidden)
    default: preconditionFailure("invalid menuIndicator: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKMenuOrder(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.menuOrder(.automatic)
      case "priority": self.menuOrder(.priority)
      case "fixed": self.menuOrder(.fixed)
    default: preconditionFailure("invalid menuOrder: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKMinimumScaleFactor(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.minimumScaleFactor(CGFloat(number))
      } else { preconditionFailure("invalid minimumScaleFactor: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKMonospaced(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid monospaced: \(value)")
      self.monospaced(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKMonospacedDigit(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid monospacedDigit: \(value)")
    if value == "true" { self.monospacedDigit() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKMoveDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid moveDisabled: \(value)")
      self.moveDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKMultilineTextAlignment(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "leading": self.multilineTextAlignment(.leading)
      case "center": self.multilineTextAlignment(.center)
      case "trailing": self.multilineTextAlignment(.trailing)
    default: preconditionFailure("invalid multilineTextAlignment: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKNavigationBarBackButtonHidden(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid navigationBarBackButtonHidden: \(value)")
      self.navigationBarBackButtonHidden(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKNavigationBarHidden(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid navigationBarHidden: \(value)")
      self.navigationBarHidden(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKNavigationLinkIndicatorVisibility(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.navigationLinkIndicatorVisibility(.automatic)
      case "visible": self.navigationLinkIndicatorVisibility(.visible)
      case "hidden": self.navigationLinkIndicatorVisibility(.hidden)
    default: preconditionFailure("invalid navigationLinkIndicatorVisibility: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKNavigationSplitViewColumnWidth(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.navigationSplitViewColumnWidth(CGFloat(number))
      } else { preconditionFailure("invalid navigationSplitViewColumnWidth: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKNavigationTitle(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.navigationTitle(Binding(get: { value }, set: { emit("navigationTitle", String($0)) }))
  }

  @ViewBuilder fileprivate func oneNativeSDKOnAppear(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.onAppear(perform: { emit("onAppear", "") })
  }

  @ViewBuilder fileprivate func oneNativeSDKOnDisappear(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.onDisappear(perform: { emit("onDisappear", "") })
  }

  @ViewBuilder fileprivate func oneNativeSDKOnSubmit(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.onSubmit({ emit("onSubmit", "") })
  }

  @ViewBuilder fileprivate func oneNativeSDKOnTapGesture(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.onTapGesture(perform: { emit("onTapGesture", "") })
  }

  @ViewBuilder fileprivate func oneNativeSDKPaletteSelectionEffect(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.paletteSelectionEffect(.automatic)
      case "custom": self.paletteSelectionEffect(.custom)
    default: preconditionFailure("invalid paletteSelectionEffect: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPayWithApplePayButtonDisableCardArt(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid payWithApplePayButtonDisableCardArt: \(value)")
    if value == "true" { if #available(iOS 26, *) { self.payWithApplePayButtonDisableCardArt() } else { self } } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKPersistentSystemOverlays(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.persistentSystemOverlays(.automatic)
      case "visible": self.persistentSystemOverlays(.visible)
      case "hidden": self.persistentSystemOverlays(.hidden)
    default: preconditionFailure("invalid persistentSystemOverlays: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPresentationBackgroundInteraction(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.presentationBackgroundInteraction(.automatic)
      case "enabled": self.presentationBackgroundInteraction(.enabled)
      case "disabled": self.presentationBackgroundInteraction(.disabled)
    default: preconditionFailure("invalid presentationBackgroundInteraction: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPresentationCompactAdaptation(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.presentationCompactAdaptation(.automatic)
      case "none": self.presentationCompactAdaptation(.none)
      case "popover": self.presentationCompactAdaptation(.popover)
      case "sheet": self.presentationCompactAdaptation(.sheet)
      case "fullScreenCover": self.presentationCompactAdaptation(.fullScreenCover)
    default: preconditionFailure("invalid presentationCompactAdaptation: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPresentationContentInteraction(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.presentationContentInteraction(.automatic)
      case "resizes": self.presentationContentInteraction(.resizes)
      case "scrolls": self.presentationContentInteraction(.scrolls)
    default: preconditionFailure("invalid presentationContentInteraction: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPresentationDragIndicator(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.presentationDragIndicator(.automatic)
      case "visible": self.presentationDragIndicator(.visible)
      case "hidden": self.presentationDragIndicator(.hidden)
    default: preconditionFailure("invalid presentationDragIndicator: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPresentationPlacement(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 27, *) { self.presentationPlacement(.automatic) } else { self }
      case "leading": if #available(iOS 27, *) { self.presentationPlacement(.leading) } else { self }
      case "center": if #available(iOS 27, *) { self.presentationPlacement(.center) } else { self }
      case "trailing": if #available(iOS 27, *) { self.presentationPlacement(.trailing) } else { self }
    default: preconditionFailure("invalid presentationPlacement: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPreviewInterfaceOrientation(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "portrait": self.previewInterfaceOrientation(.portrait)
      case "portraitUpsideDown": self.previewInterfaceOrientation(.portraitUpsideDown)
      case "landscapeLeft": self.previewInterfaceOrientation(.landscapeLeft)
      case "landscapeRight": self.previewInterfaceOrientation(.landscapeRight)
    default: preconditionFailure("invalid previewInterfaceOrientation: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKPrivacySensitive(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid privacySensitive: \(value)")
      self.privacySensitive(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKProductIconBorder(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid productIconBorder: \(value)")
    if value == "true" { self.productIconBorder() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKRenameAction(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.renameAction({ emit("renameAction", "") })
  }

  @ViewBuilder fileprivate func oneNativeSDKReplaceDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid replaceDisabled: \(value)")
      self.replaceDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSafeAreaPadding(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.safeAreaPadding(CGFloat(number))
      } else { preconditionFailure("invalid safeAreaPadding: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKSaturation(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.saturation(number)
      } else { preconditionFailure("invalid saturation: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKScaledToFill(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid scaledToFill: \(value)")
    if value == "true" { self.scaledToFill() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKScaledToFit(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid scaledToFit: \(value)")
    if value == "true" { self.scaledToFit() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKScenePadding(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "top": self.scenePadding(.top)
      case "leading": self.scenePadding(.leading)
      case "bottom": self.scenePadding(.bottom)
      case "trailing": self.scenePadding(.trailing)
      case "all": self.scenePadding(.all)
      case "horizontal": self.scenePadding(.horizontal)
      case "vertical": self.scenePadding(.vertical)
    default: preconditionFailure("invalid scenePadding: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKScrollClipDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid scrollClipDisabled: \(value)")
      self.scrollClipDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKScrollContentBackground(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.scrollContentBackground(.automatic)
      case "visible": self.scrollContentBackground(.visible)
      case "hidden": self.scrollContentBackground(.hidden)
    default: preconditionFailure("invalid scrollContentBackground: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKScrollDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid scrollDisabled: \(value)")
      self.scrollDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKScrollDismissesKeyboard(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.scrollDismissesKeyboard(.automatic)
      case "immediately": self.scrollDismissesKeyboard(.immediately)
      case "interactively": self.scrollDismissesKeyboard(.interactively)
      case "never": self.scrollDismissesKeyboard(.never)
    default: preconditionFailure("invalid scrollDismissesKeyboard: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKSearchable(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    self.searchable(text: Binding(get: { value }, set: { emit("searchable", String($0)) }))
  }

  @ViewBuilder fileprivate func oneNativeSDKSearchCompletion(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      self.searchCompletion(value)
  }

  @ViewBuilder fileprivate func oneNativeSDKSearchDictationBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.searchDictationBehavior(.automatic)
    default: preconditionFailure("invalid searchDictationBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKSearchPresentationToolbarBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 17.1, *) { self.searchPresentationToolbarBehavior(.automatic) } else { self }
      case "avoidHidingContent": if #available(iOS 17.1, *) { self.searchPresentationToolbarBehavior(.avoidHidingContent) } else { self }
    default: preconditionFailure("invalid searchPresentationToolbarBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKSearchToolbarBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 26, *) { self.searchToolbarBehavior(.automatic) } else { self }
      case "minimize": if #available(iOS 26, *) { self.searchToolbarBehavior(.minimize) } else { self }
    default: preconditionFailure("invalid searchToolbarBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKSelectionDisabled(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid selectionDisabled: \(value)")
      self.selectionDisabled(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSliderThumbVisibility(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 26, *) { self.sliderThumbVisibility(.automatic) } else { self }
      case "visible": if #available(iOS 26, *) { self.sliderThumbVisibility(.visible) } else { self }
      case "hidden": if #available(iOS 26, *) { self.sliderThumbVisibility(.hidden) } else { self }
    default: preconditionFailure("invalid sliderThumbVisibility: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKSpeechAdjustedPitch(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.speechAdjustedPitch(number)
      } else { preconditionFailure("invalid speechAdjustedPitch: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKSpeechAlwaysIncludesPunctuation(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid speechAlwaysIncludesPunctuation: \(value)")
      self.speechAlwaysIncludesPunctuation(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSpeechAnnouncementsQueued(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid speechAnnouncementsQueued: \(value)")
      self.speechAnnouncementsQueued(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSpeechSpellsOutCharacters(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid speechSpellsOutCharacters: \(value)")
      self.speechSpellsOutCharacters(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSpringLoadingBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.springLoadingBehavior(.automatic)
      case "enabled": self.springLoadingBehavior(.enabled)
      case "disabled": self.springLoadingBehavior(.disabled)
    default: preconditionFailure("invalid springLoadingBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKStatusBarHidden(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid statusBarHidden: \(value)")
      self.statusBarHidden(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSubmitLabel(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "done": self.submitLabel(.done)
      case "go": self.submitLabel(.go)
      case "send": self.submitLabel(.send)
      case "join": self.submitLabel(.join)
      case "route": self.submitLabel(.route)
      case "search": self.submitLabel(.search)
      case "return": self.submitLabel(.return)
      case "next": self.submitLabel(.next)
      case "continue": self.submitLabel(.continue)
    default: preconditionFailure("invalid submitLabel: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKSubmitScope(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid submitScope: \(value)")
      self.submitScope(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSwipeActionsContainer(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid swipeActionsContainer: \(value)")
    if value == "true" { if #available(iOS 27, *) { self.swipeActionsContainer() } else { self } } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKSymbolEffectsRemoved(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      let _ = precondition(value == "true" || value == "false", "invalid symbolEffectsRemoved: \(value)")
      self.symbolEffectsRemoved(value == "true")
  }

  @ViewBuilder fileprivate func oneNativeSDKSymbolVariant(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "none": self.symbolVariant(.none)
      case "circle": self.symbolVariant(.circle)
      case "square": self.symbolVariant(.square)
      case "rectangle": self.symbolVariant(.rectangle)
      case "fill": self.symbolVariant(.fill)
      case "slash": self.symbolVariant(.slash)
    default: preconditionFailure("invalid symbolVariant: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKTabBarMinimizeBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 26, *) { self.tabBarMinimizeBehavior(.automatic) } else { self }
      case "onScrollDown": if #available(iOS 26, *) { self.tabBarMinimizeBehavior(.onScrollDown) } else { self }
      case "onScrollUp": if #available(iOS 26, *) { self.tabBarMinimizeBehavior(.onScrollUp) } else { self }
      case "never": if #available(iOS 26, *) { self.tabBarMinimizeBehavior(.never) } else { self }
    default: preconditionFailure("invalid tabBarMinimizeBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKTableColumnHeaders(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.tableColumnHeaders(.automatic)
      case "visible": self.tableColumnHeaders(.visible)
      case "hidden": self.tableColumnHeaders(.hidden)
    default: preconditionFailure("invalid tableColumnHeaders: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKTabViewSearchActivation(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 26, *) { self.tabViewSearchActivation(.automatic) } else { self }
      case "searchTabSelection": if #available(iOS 26, *) { self.tabViewSearchActivation(.searchTabSelection) } else { self }
    default: preconditionFailure("invalid tabViewSearchActivation: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKTextInputBorderShape(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 27, *) { self.textInputBorderShape(.automatic) } else { self }
      case "capsule": if #available(iOS 27, *) { self.textInputBorderShape(.capsule) } else { self }
      case "roundedRectangle": if #available(iOS 27, *) { self.textInputBorderShape(.roundedRectangle) } else { self }
    default: preconditionFailure("invalid textInputBorderShape: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKTextSelectionAffinity(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18, *) { self.textSelectionAffinity(.automatic) } else { self }
      case "upstream": if #available(iOS 18, *) { self.textSelectionAffinity(.upstream) } else { self }
      case "downstream": if #available(iOS 18, *) { self.textSelectionAffinity(.downstream) } else { self }
    default: preconditionFailure("invalid textSelectionAffinity: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKToolbarRole(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.toolbarRole(.automatic)
      case "navigationStack": self.toolbarRole(.navigationStack)
      case "browser": self.toolbarRole(.browser)
      case "editor": self.toolbarRole(.editor)
    default: preconditionFailure("invalid toolbarRole: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKToolbarTitleDisplayMode(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": self.toolbarTitleDisplayMode(.automatic)
      case "large": self.toolbarTitleDisplayMode(.large)
      case "inlineLarge": self.toolbarTitleDisplayMode(.inlineLarge)
      case "inline": self.toolbarTitleDisplayMode(.inline)
    default: preconditionFailure("invalid toolbarTitleDisplayMode: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKTracking(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.tracking(CGFloat(number))
      } else { preconditionFailure("invalid tracking: \(value)") }
  }

  @ViewBuilder fileprivate func oneNativeSDKTransition(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "opacity": self.transition(.opacity)
      case "slide": self.transition(.slide)
      case "identity": self.transition(.identity)
      case "scale": self.transition(.scale)
    default: preconditionFailure("invalid transition: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKUnredacted(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    let _ = precondition(value == "true" || value == "false", "invalid unredacted: \(value)")
    if value == "true" { self.unredacted() } else { self }
  }

  @ViewBuilder fileprivate func oneNativeSDKWindowToolbarFullScreenVisibility(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18, *) { self.windowToolbarFullScreenVisibility(.automatic) } else { self }
    default: preconditionFailure("invalid windowToolbarFullScreenVisibility: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKWritingToolsAffordanceVisibility(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18.4, *) { self.writingToolsAffordanceVisibility(.automatic) } else { self }
      case "visible": if #available(iOS 18.4, *) { self.writingToolsAffordanceVisibility(.visible) } else { self }
      case "hidden": if #available(iOS 18.4, *) { self.writingToolsAffordanceVisibility(.hidden) } else { self }
    default: preconditionFailure("invalid writingToolsAffordanceVisibility: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKWritingToolsBehavior(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
    switch value {
      case "automatic": if #available(iOS 18, *) { self.writingToolsBehavior(.automatic) } else { self }
      case "complete": if #available(iOS 18, *) { self.writingToolsBehavior(.complete) } else { self }
      case "limited": if #available(iOS 18, *) { self.writingToolsBehavior(.limited) } else { self }
      case "disabled": if #available(iOS 18, *) { self.writingToolsBehavior(.disabled) } else { self }
    default: preconditionFailure("invalid writingToolsBehavior: \(value)")
    }
  }

  @ViewBuilder fileprivate func oneNativeSDKZIndex(_ value: String, emit: @escaping (String, String) -> Void) -> some View {
      if let number = Double(value), number.isFinite {
        self.zIndex(number)
      } else { preconditionFailure("invalid zIndex: \(value)") }
  }
}
