import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { constructors, enumTypes, fields, modifiers, nodes } from './catalog'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cache = join(root, '.codegen-cache')
mkdirSync(cache, { recursive: true })
const run = (file: string, args: string[]) =>
  execFileSync(file, args, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 }).trim()
const sdk = run('xcrun', ['--sdk', 'iphonesimulator', '--show-sdk-path'])
const swiftc = run('xcrun', ['--find', 'swiftc'])
const host = resolve(dirname(swiftc), '../lib/swift/host')
const binary = join(cache, 'extract')
run(swiftc, [
  '-sdk',
  run('xcrun', ['--sdk', 'macosx', '--show-sdk-path']),
  '-I',
  host,
  '-L',
  host,
  '-Xlinker',
  '-rpath',
  '-Xlinker',
  host,
  join(root, 'codegen/Extract.swift'),
  '-o',
  binary,
])
const paths = ['SwiftUI', 'SwiftUICore'].map((module) =>
  join(
    sdk,
    `System/Library/Frameworks/${module}.framework/Modules/${module}.swiftmodule/arm64-apple-ios-simulator.swiftinterface`
  )
)
type Declaration = {
  module: string
  owner: string
  kind: string
  name: string
  attributes: string[]
  parameters: { label: string; name: string; type: string; defaultValue?: string }[]
  type?: string
  line: number
}
const inventory: Declaration[] = JSON.parse(run(binary, paths))
const available = (d: Declaration) =>
  !d.attributes.some((a) => /@available\((?:iOS|\*)\s*,\s*unavailable/.test(a)) &&
  !d.attributes.some((a) => a.startsWith('@_spi'))
const ios = (d: Declaration) =>
  Math.max(
    0,
    ...d.attributes.flatMap((a) =>
      [...a.matchAll(/\biOS\s+(?:introduced:\s*)?(\d+(?:\.\d+)?)/g)].map((m) =>
        Number(m[1])
      )
    )
  )
const shortOwner = (d: Declaration) => d.owner.split('.').at(-1)
const selected: Declaration[] = []
const enums = Object.fromEntries(
  enumTypes.map((type) => {
    const cases = inventory.filter(
      (d) =>
        shortOwner(d) === type &&
        d.kind === 'static' &&
        (type === 'ControlGroupStyle' || d.type?.split('.').at(-1) === type) &&
        available(d)
    )
    if (!cases.length) throw new Error(`no SDK cases for ${type}`)
    selected.push(...cases)
    return [type, Object.fromEntries(cases.map((d) => [d.name, ios(d)]))]
  })
) as Record<string, Record<string, number>>
const methods = modifiers.map((modifier) => {
  const method = inventory.find(
    (d) =>
      d.kind === 'func' &&
      d.name === modifier.name &&
      shortOwner(d) === 'View' &&
      d.parameters.length === 1 &&
      (d.parameters[0].type === `SwiftUI.${modifier.type}` ||
        (modifier.type === 'ControlGroupStyle' && d.parameters[0].type === 'S')) &&
      available(d)
  )
  if (!method) throw new Error(`SDK modifier signature changed: ${modifier.name}`)
  selected.push(method)
  return { ...modifier, ios: ios(method) }
})
for (const constructor of constructors) {
  const candidates = inventory.filter(
    (d) =>
      d.kind === 'init' &&
      shortOwner(d) === constructor.type &&
      available(d) &&
      JSON.stringify(d.parameters.map((p) => p.label)) ===
        JSON.stringify(constructor.labels)
  )
  const declaration = candidates.sort((a, b) => ios(a) - ios(b))[0]
  if (!declaration)
    throw new Error(
      `SDK constructor signature changed: ${constructor.type}(${constructor.labels.join(':')})`
    )
  selected.push(declaration)
}
const header =
  '// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.\n// edit the generator or catalog, then regenerate.\n'
const outputs = new Map<string, string>()
outputs.set(
  'src/generated/swiftui.ts',
  header +
    Object.entries(enums)
      .map(
        ([name, cases]) =>
          `export type ${name} = ${Object.keys(cases)
            .map((c) => JSON.stringify(c))
            .join(' | ')}`
      )
      .join('\n') +
    `
export const swiftUIValues = ${JSON.stringify(enums, null, 2)} as const
export function assertSwiftUIValue(type: keyof typeof swiftUIValues, value: string, iosVersion: number) {
  const values: Record<string, number> = swiftUIValues[type]
  if (!Object.hasOwn(values, value)) throw new Error('Unknown SwiftUI ' + type + ': ' + value)
  if (iosVersion < values[value]) throw new Error(type + '.' + value + ' requires iOS ' + values[value])
}
`
)
const fieldType = (type: string, publicType = false) =>
  type === 'boolean[]'
    ? publicType
      ? 'readonly boolean[]'
      : 'ReadonlyArray<boolean>'
    : enumTypes.includes(type)
      ? publicType
        ? type
        : 'string'
      : type
outputs.set(
  'src/generated/types.ts',
  header +
    `import type { ReactNode } from 'react'
import type { ViewProps } from 'react-native'
import type { ${enumTypes.join(', ')} } from './swiftui'
export type { ${enumTypes.join(', ')} } from './swiftui'
` +
    nodes
      .map(
        (node) => `export interface ${node.name} {
  type: '${node.kind}'
${node.fields.map((name) => `  ${name}${(node.required as readonly string[]).includes(name) ? '' : '?'}: ${fieldType(fields[name as keyof typeof fields].type, true)}`).join('\n')}
${node.children ? '  children: readonly MenuItem[]\n' : ''}}
`
      )
      .join('\n') +
    `
export type MenuItem = ${nodes.map((node) => node.name).join(' | ')}
export interface MenuProps extends ViewProps {
  items: readonly MenuItem[]
  onAction: (id: string) => void
  onValueChange?: (id: string, value: boolean, sourceIndex: number) => void
  accessibilityLabel: string
  disabled?: boolean
  menuOrder?: MenuOrder
  menuActionDismissBehavior?: MenuActionDismissBehavior
  children: ReactNode
}
export interface TabProps {
  id: string
  title: string
  systemImage?: string
  badge?: string
  role?: TabRole
  testID?: string
  children: ReactNode
}
export interface TabsProps extends ViewProps {
  selection: string
  onSelectionChange: (id: string) => void
  sidebarAdaptable?: boolean
  tabBarMinimizeBehavior?: TabBarMinimizeBehavior
}
`
)
const nativeFields = { parentId: { type: 'string' }, type: { type: 'string' }, ...fields }
const nativeItem = `export type NativeMenuItem = Readonly<{\n${Object.entries(
  nativeFields
)
  .map(([name, field]) => `  ${name}: ${fieldType(field.type)}`)
  .join('\n')}\n}>`
outputs.set(
  'src/specs/OneNativeMenuNativeComponent.ts',
  header +
    `import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
${nativeItem}
interface NativeProps extends ViewProps {
  items: ReadonlyArray<NativeMenuItem>
  triggerLabel: string
  disabled: boolean
  menuOrder: string
  menuActionDismissBehavior: string
  onAction?: DirectEventHandler<Readonly<{ id: string }>>
  onValueChange?: DirectEventHandler<Readonly<{ id: string; value: boolean; sourceIndex: Int32 }>>
}
export default codegenNativeComponent<NativeProps>('OneNativeMenu')
`
)
outputs.set(
  'src/specs/OneNativeTabNativeComponent.ts',
  header +
    `import type { ViewProps } from 'react-native'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
interface NativeProps extends ViewProps {
  tabId: string
  title: string
  systemImage: string
  badge: string
  tabRole: string
}
export default codegenNativeComponent<NativeProps>('OneNativeTab', { interfaceOnly: true })
`
)
outputs.set(
  'src/specs/OneNativeTabsNativeComponent.ts',
  header +
    `import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
interface NativeProps extends ViewProps {
  selection: string
  acknowledgedEvent: Int32
  sidebarAdaptable: boolean
  tabBarMinimizeBehavior: string
  onSelectionChange?: DirectEventHandler<Readonly<{ selection: string; eventCount: Int32 }>>
}
export default codegenNativeComponent<NativeProps>('OneNativeTabs')
`
)
const definitions = Object.fromEntries(
  nodes.map((node) => [
    node.kind,
    {
      fields: Object.fromEntries(
        node.fields.map((name) => [
          name,
          {
            ...fields[name as keyof typeof fields],
            required: (node.required as readonly string[]).includes(name),
          },
        ])
      ),
      children: node.children,
    },
  ])
)
outputs.set(
  'src/menuItems.ts',
  header +
    `import type { NativeMenuItem } from './specs/OneNativeMenuNativeComponent'
import type { MenuItem } from './types'
import { assertSwiftUIValue, swiftUIValues } from './generated/swiftui'
const definitions: Record<string, { fields: Record<string, { type: string; default: unknown; required: boolean }>; children: boolean }> = ${JSON.stringify(definitions, null, 2)}
const defaults = ${JSON.stringify(Object.fromEntries(Object.entries(fields).map(([k, v]) => [k, v.default])))}
export function flattenMenuItems(items: readonly MenuItem[], iosVersion = 18): NativeMenuItem[] {
  const result: NativeMenuItem[] = []
  const ids = new Set<string>()
  const append = (items: readonly MenuItem[], parentId: string, disabled: boolean, hidden: boolean) => {
    for (const item of items) {
      const definition = definitions[item.type]
      if (!definition) throw new Error('Unknown Swift.Menu item type: ' + item.type)
      const input = item as unknown as Record<string, unknown>
      for (const name of Object.keys(input)) {
        if (name !== 'type' && !(name === 'children' && definition.children) && !Object.hasOwn(definition.fields, name)) throw new Error('Unsupported Swift.Menu ' + item.type + ' property: ' + name)
      }
      const payload: Record<string, unknown> = { ...defaults, parentId, type: item.type }
      for (const [name, field] of Object.entries(definition.fields)) {
        const value = input[name] ?? field.default
        if (field.required && input[name] == null) throw new Error('Swift.Menu ' + item.type + ' requires ' + name)
        if (field.type === 'boolean[]') {
          if (!Array.isArray(value) || !value.length || value.some(v => typeof v !== 'boolean')) throw new Error('Swift.Menu toggle values must be a nonempty boolean array')
        } else if (Object.hasOwn(swiftUIValues, field.type)) {
          if (typeof value !== 'string') throw new Error('Invalid Swift.Menu ' + name)
          if (value !== '' || field.default !== '') assertSwiftUIValue(field.type as keyof typeof swiftUIValues, value, iosVersion)
        } else if (typeof value !== field.type) throw new Error('Invalid Swift.Menu ' + name)
        payload[name] = value
      }
      if (!item.id || ids.has(item.id)) throw new Error('Swift.Menu requires unique, nonempty item ids: "' + item.id + '"')
      ids.add(item.id)
      payload.disabled = disabled || payload.disabled
      payload.hidden = hidden || payload.hidden
      result.push(payload as unknown as NativeMenuItem)
      if (definition.children) {
        if (!Array.isArray(input.children)) throw new Error('Swift.Menu ' + item.type + ' requires children')
        append(input.children, item.id, Boolean(payload.disabled), Boolean(payload.hidden))
      }
    }
  }
  append(items, '', false, false)
  return result
}
`
)
let swift = header + 'import SwiftUI\n\nenum OneNativeGenerated {\n'
for (const [type, cases] of Object.entries(enums)) {
  if (type === 'ControlGroupStyle') continue
  const optional = ['ButtonRole', 'TabRole'].includes(type)
  const minimum = Math.min(...Object.values(cases))
  if (minimum > 18) swift += `  @available(iOS ${minimum}, *)\n`
  swift += `  static func ${type[0].toLowerCase() + type.slice(1)}(_ value: String) -> ${type}${optional ? '?' : ''} {\n    switch value {\n`
  if (optional) swift += '    case "": return nil\n'
  for (const [name, version] of Object.entries(cases)) {
    swift += `    case "${name}":\n`
    swift +=
      version > Math.max(18, minimum)
        ? `      if #available(iOS ${version}, *) { return .${name} }\n      preconditionFailure("${type}.${name} requires iOS ${version}")\n`
        : `      return .${name}\n`
  }
  swift += `    default: preconditionFailure("invalid ${type}: \\(value)")\n    }\n  }\n`
}
swift += `  @MainActor @TabContentBuilder<String> static func tab<Content: View>(id: String, title: String, systemImage: String, badge: String, role: String, @ViewBuilder content: () -> Content) -> some TabContent<String> {
    Tab(value: id, role: tabRole(role)) { content() } label: {
      if systemImage.isEmpty { Text(title) } else { Label(title, systemImage: systemImage) }
    }
    .badge(badge.isEmpty ? nil : Text(badge))
  }
`
swift +=
  '}\n\nenum OneNativeControlGroupStyle: String {\n' +
  Object.keys(enums.ControlGroupStyle)
    .map((name) => '  case ' + name)
    .join('\n') +
  '\n}\n\nextension View {\n'
for (const method of methods) {
  if (method.type === 'ControlGroupStyle') {
    swift +=
      '  @ViewBuilder func oneNativeControlGroupStyle(_ value: String) -> some View {\n    switch OneNativeControlGroupStyle(rawValue: value)! {\n'
    for (const [name, version] of Object.entries(enums.ControlGroupStyle)) {
      swift += `    case .${name}:\n`
      swift +=
        version > 18
          ? `      if #available(iOS ${version}, *) { self.controlGroupStyle(.${name}) } else { let _ = preconditionFailure("ControlGroupStyle.${name} requires iOS ${version}"); self }\n`
          : `      self.controlGroupStyle(.${name})\n`
    }
    swift += '    }\n  }\n'
    continue
  }
  const apply = `self.${method.name}(OneNativeGenerated.${method.type[0].toLowerCase() + method.type.slice(1)}(value))`
  swift += `  @ViewBuilder func oneNative${method.type}(_ value: String) -> some View {\n`
  if (method.ios > 18) {
    swift += `    if #available(iOS ${method.ios}, *) {\n      if value.isEmpty { self } else { ${apply} }\n    } else {\n      let _ = precondition(value.isEmpty, "${method.name} requires iOS ${method.ios}")\n      self\n    }\n`
  } else swift += `    if value.isEmpty { self } else { ${apply} }\n`
  swift += '  }\n'
}
swift += '}\n'
outputs.set('ios/Generated/OneNativeSwiftUI.swift', swift)
outputs.set(
  'ios/Generated/OneNativeMenuContent.swift',
  header +
    `import SwiftUI

enum OneNativeMenuKind: String {
${nodes.map((node) => `  case ${node.kind}`).join('\n')}
}
struct OneNativeMenuNode: Identifiable {
${Object.entries(nativeFields)
  .map(
    ([name, field]) =>
      `  let ${name}: ${name === 'type' ? 'OneNativeMenuKind' : field.type === 'boolean' ? 'Bool' : field.type === 'boolean[]' ? '[Bool]' : 'String'}`
  )
  .join('\n')}
  init(_ item: [String: Any]) {
${Object.entries(nativeFields)
  .map(([name, field]) =>
    name === 'type'
      ? '    type = OneNativeMenuKind(rawValue: item["type"] as! String)!'
      : `    ${name} = item["${name}"] as! ${field.type === 'boolean' ? 'Bool' : field.type === 'boolean[]' ? '[Bool]' : 'String'}`
  )
  .join('\n')}
  }
}
struct OneNativeMenuLabel: View {
  let item: OneNativeMenuNode
  var body: some View {
    if item.systemImage.isEmpty { Text(item.title) }
    else { Label(item.title, systemImage: item.systemImage) }
  }
}
struct OneNativeGeneratedMenuContent: View {
  @ObservedObject var model: OneNativeMenuModel
  let parentId: String
  var body: some View {
    ForEach(model.children[parentId] ?? []) { item in
      if !item.hidden {
        Group {
          switch item.type {
${nodes.map((node) => `          case .${node.kind}:\n            ${node.swift}`).join('\n')}
          }
        }
        .disabled(item.disabled)
        .help(item.help)
        .oneNativeMenuOrder(item.menuOrder)
        .oneNativeMenuActionDismissBehavior(item.menuActionDismissBehavior)
      }
    }
  }
}
`
)
outputs.set(
  'ios/Generated/OneNativeMenuPayload.h',
  header +
    `#ifdef __cplusplus
#import <React/RCTConversions.h>
#import <react/renderer/components/OneNativeSpec/Props.h>
inline NSArray *OneNativeMenuPayload(const std::vector<facebook::react::OneNativeMenuItemsStruct> &items) {
  NSMutableArray *result = [NSMutableArray new];
  for (const auto &item : items) {
    NSMutableArray *values = [NSMutableArray new];
    for (bool value : item.values) [values addObject:@(value)];
    [result addObject:@{
${Object.entries(nativeFields)
  .map(
    ([name, field]) =>
      `      @"${name}": ${field.type === 'boolean' ? `@(item.${name})` : field.type === 'boolean[]' ? 'values' : `RCTNSStringFromString(item.${name})`}`
  )
  .join(',\n')}
    }];
  }
  return result;
}
#endif
`
)
const manifest = {
  compiler: run(swiftc, ['--version'])
    .split('\n')
    .filter((line) => !line.startsWith('Target:'))
    .join('\n'),
  sdk: run('xcrun', ['--sdk', 'iphonesimulator', '--show-sdk-version']),
  inputs: paths.map((path, index) => ({
    module: ['SwiftUI', 'SwiftUICore'][index],
    sha256: createHash('sha256').update(readFileSync(path)).digest('hex'),
  })),
  extractedDeclarations: inventory.length,
  unmappedModifiers: [
    ...new Set(
      inventory
        .filter(
          (d) =>
            d.kind === 'func' &&
            shortOwner(d) === 'View' &&
            available(d) &&
            /^(menu|tabBar|tabView|controlGroup|palette)/.test(d.name) &&
            !methods.some((m) => m.name === d.name)
        )
        .map((d) => d.name)
    ),
  ].sort(),
  enums,
  modifiers: methods,
  constructors: selected
    .filter((d) => d.kind === 'init')
    .map((d) => ({
      module: d.module,
      type: shortOwner(d),
      parameters: d.parameters,
      ios: ios(d),
    })),
}
outputs.set('codegen/swiftui-manifest.json', JSON.stringify(manifest, null, 2) + '\n')
const changed: string[] = []
for (const [path, source] of outputs) {
  const temporary = join(cache, path.replaceAll('/', '_'))
  writeFileSync(temporary, source)
  if (path.endsWith('.ts'))
    run('bunx', ['oxfmt', '-c', resolve(root, '../../.prettierrc'), temporary])
  const generated = readFileSync(temporary, 'utf8')
  let existing = ''
  try {
    existing = readFileSync(join(root, path), 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  if (existing !== generated) changed.push(path)
  if (!process.argv.includes('--check')) writeFileSync(join(root, path), generated)
}
if (process.argv.includes('--check') && changed.length)
  throw new Error('Generated SwiftUI bindings differ: ' + changed.join(', '))
console.log(
  `SwiftUI SDK ${manifest.sdk}: ${inventory.length} declarations, ${selected.length} mapped symbols, ${outputs.size} generated files${process.argv.includes('--check') ? ', verified' : ''}`
)
