import { containerComponents, emitContainers } from './emitContainers'
import { emitPopover, popoverComponents, popoverMethods } from './emitPopover'
import { emitSheet, sheetComponents, sheetMethods } from './emitSheet'
import { controls } from './controlCatalog'
import { emitControls } from './emitControls'
import { emitMenuValidator } from './menuValidator'
import {
  readInventory,
  ios,
  available,
  selectConstructor,
  selectModifier,
  type Declaration,
} from './inventory'
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  tabConstructor,
  components,
  modifierFamilies,
  enumTypes,
  fields,
  modifiers,
  nodes,
} from './catalog'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cache = join(root, '.codegen-cache')
mkdirSync(cache, { recursive: true })
const run = (file: string, args: string[]) =>
  execFileSync(file, args, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 }).trim()
const { sdk, swiftc, paths, inventory } = readInventory(root)
const shortOwner = (d: Declaration) => d.owner.split('.').at(-1)
const selected: Declaration[] = []
const enums = Object.fromEntries(
  enumTypes.map((type) => {
    const cases = inventory.filter(
      (d) =>
        shortOwner(d) === type &&
        d.kind === 'static' &&
        (type.endsWith('Style') || d.type?.split('.').at(-1) === type) &&
        available(d)
    )
    if (!cases.length) throw new Error(`no SDK cases for ${type}`)
    selected.push(...cases)
    return [type, Object.fromEntries(cases.map((d) => [d.name, ios(d)]))]
  })
) as Record<string, Record<string, number>>
const methods = modifiers.map((modifier) => {
  const isStyle = modifier.type.endsWith('Style')
  const method = selectModifier(inventory, {
    name: modifier.name,
    parameters: [
      {
        label: '_',
        type: isStyle
          ? 'S'
          : `${'module' in modifier ? modifier.module : 'SwiftUI'}.${modifier.type}${'optional' in modifier && modifier.optional ? '?' : ''}`,
      },
    ],
    requirements: isStyle ? [`S: SwiftUI.${modifier.type}`] : [],
  })
  selected.push(method)
  return {
    ...modifier,
    ios: ios(method),
    parameters: method.parameters,
    requirements: method.requirements,
  }
})
for (const constructor of [
  ...nodes.map((node) => node.constructor),
  tabConstructor,
  ...controls.flatMap((control) => control.constructors),
]) {
  selected.push(selectConstructor(inventory, constructor))
}
for (const control of controls) {
  for (const method of control.methods ?? [])
    selected.push(selectModifier(inventory, method))
}
const header =
  '// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.\n// edit the generator or catalog, then regenerate.\n'
const outputs = new Map<string, string>()
const { schema: controlComponents, payloads: controlPayloads } = emitControls(
  header,
  outputs
) ?? { schema: [], payloads: {} }
emitSheet(header, outputs)
emitContainers(header, outputs)
emitPopover(header, outputs)
selected.push(
  ...[...sheetMethods, ...popoverMethods].map((method) => selectModifier(inventory, method))
)
outputs.set(
  'src/generated/swiftui.ts',
  header +
    Object.entries(enums)
      .map(
        ([name, cases]) =>
          `export type ${name} = ${Object.keys(cases)
            .map((c) => JSON.stringify(c))
            .join(' | ')}`
      )
      .join('\n') +
    `
export const swiftUIValues = ${JSON.stringify(enums, null, 2)} as const
export function assertSwiftUIValue(type: keyof typeof swiftUIValues, value: string, iosVersion: number) {
  const values: Record<string, number> = swiftUIValues[type]
  if (!Object.hasOwn(values, value)) throw new Error('Unknown SwiftUI ' + type + ': ' + value)
  if (iosVersion < values[value]) throw new Error(type + '.' + value + ' requires iOS ' + values[value])
}
`
)
const fieldType = (type: string, publicType = false) =>
  type === 'boolean[]'
    ? publicType
      ? 'readonly boolean[]'
      : 'ReadonlyArray<boolean>'
    : enumTypes.includes(type)
      ? publicType
        ? type
        : 'string'
      : type
outputs.set(
  'src/generated/types.ts',
  header +
    `import type { ReactNode } from 'react'
import type { ViewProps } from 'react-native'
import type { ${enumTypes.join(', ')} } from './swiftui'
export type { ${enumTypes.join(', ')} } from './swiftui'
` +
    nodes
      .map(
        (node) => `export interface ${node.name} {
  type: '${node.kind}'
${node.fields.map((name) => `  ${name}${(node.required as readonly string[]).includes(name) ? '' : '?'}: ${fieldType(fields[name].type, true)}`).join('\n')}
${node.children ? '  children: readonly MenuItem[]\n' : ''}}
`
      )
      .join('\n') +
    `
export type MenuItem = ${nodes.map((node) => node.name).join(' | ')}
export interface MenuProps extends ViewProps {
  items: readonly MenuItem[]
  onAction: (id: string) => void
  onValueChange?: (id: string, value: boolean, sourceIndex: number) => void
  accessibilityLabel: string
  revision?: number
  disabled?: boolean
  menuOrder?: MenuOrder
  menuActionDismissBehavior?: MenuActionDismissBehavior
  children: ReactNode
}
export interface TabProps {
  id: string
  title: string
  systemImage?: string
  badge?: string
  role?: TabRole
  testID?: string
  children: ReactNode
}
export interface TabsProps extends ViewProps {
  selection: string
  onSelectionChange: (id: string) => void
  revision?: number
  sidebarAdaptable?: boolean
  tabBarMinimizeBehavior?: TabBarMinimizeBehavior
}
`
)
const nativeFields = { parentId: { type: 'string' }, type: { type: 'string' }, ...fields }
const nativeItem = `export type NativeMenuItem = Readonly<{\n${Object.entries(
  nativeFields
)
  .map(([name, field]) => `  ${name}: ${fieldType(field.type)}`)
  .join('\n')}\n}>`
for (const component of components) {
  outputs.set(
    `src/specs/${component.name}NativeComponent.ts`,
    header +
      `import type { ViewProps } from 'react-native'
import type { DirectEventHandler, Int32 } from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
${component.name === 'OneNativeMenu' ? nativeItem : ''}
interface NativeProps extends ViewProps {
${Object.entries(component.props)
  .map(([name, type]) => `  ${name}: ${type}`)
  .join('\n')}
${Object.entries(component.events)
  .map(
    ([name, fields]) =>
      `  ${name}?: DirectEventHandler<Readonly<{ ${Object.entries(fields)
        .map(([name, type]) => `${name}: ${type}`)
        .join('; ')} }>>`
  )
  .join('\n')}
}
export default codegenNativeComponent<NativeProps>('${component.name}'${component.interfaceOnly ? ', { interfaceOnly: true }' : ''})
`
  )
}
outputs.set(
  'schema.json',
  JSON.stringify(
    {
      version: 2,
      platform: 'ios',
      minimumVersion: 18,
      controlledProtocol: {
        version: 1,
        revision: 'revision',
        acknowledgement: 'acknowledgedEvent',
        eventCount: 'eventCount',
      },
      eventDelivery: {
        kind: 'direct',
        payloadWrapper: 'nativeEvent',
        note: 'React Native delivers each event as onX({ nativeEvent: payload }).',
      },
      components: [
        ...components,
        ...controlComponents,
        ...sheetComponents,
        ...containerComponents,
        ...popoverComponents,
      ].map(
        (component) => {
          const enumProps: Record<string, string> =
            'enumProps' in component ? component.enumProps : {}
          return {
            name: component.name,
            publicName: component.publicName,
            props: Object.fromEntries(
              Object.entries(component.props).map(([key, type]) => [
                key,
                enumProps[key] ? { type, enum: enumProps[key] } : { type },
              ])
            ),
            events: Object.fromEntries(
              Object.entries(component.events).map(([key, payload]) => [
                key,
                Object.fromEntries(
                  Object.entries(payload as Record<string, string>).map(
                    ([field, type]) => [field, { type }]
                  )
                ),
              ])
            ),
            controlled: 'controlled' in component ? component.controlled : undefined,
            actions: 'actions' in component ? component.actions : [],
            layout: 'layout' in component ? component.layout : undefined,
            slots: component.slots,
            interfaceOnly: component.interfaceOnly,
          }
        }
      ),
      payloads: {
        ...Object.fromEntries(
          Object.entries(controlPayloads).map(([name, payload]) => [
            name,
            {
              fields: Object.fromEntries(
                Object.entries(payload.element).map(([field, type]) => [field, { type }])
              ),
            },
          ])
        ),
        NativeSheetDetent: {
          fields: { type: { type: 'string' }, value: { type: 'Double' } },
        },
        NativeMenuItem: {
          fields: nativeFields,
          nodes: nodes.map(({ swift, constructor, ...node }) => ({
            ...node,
            swiftType: constructor.type,
          })),
        },
      },
      enums,
    },
    null,
    2
  ) + '\n'
)
outputs.set('src/menuItems.ts', emitMenuValidator(header))
let swift = header + 'import SwiftUI\n\nenum OneNativeGenerated {\n'
for (const [type, cases] of Object.entries(enums)) {
  if (type.endsWith('Style')) continue
  // an empty string is the SDK's own default, which these express as nil.
  const optional = ['ButtonRole', 'TabRole', 'Edge'].includes(type)
  const minimum = Math.min(...Object.values(cases))
  if (minimum > 18) swift += `  @available(iOS ${minimum}, *)\n`
  swift += `  static func ${type[0].toLowerCase() + type.slice(1)}(_ value: String) -> ${type}${optional ? '?' : ''} {\n    switch value {\n`
  if (optional) swift += '    case "": return nil\n'
  for (const [name, version] of Object.entries(cases)) {
    swift += `    case "${name}":\n`
    swift +=
      version > Math.max(18, minimum)
        ? `      if #available(iOS ${version}, *) { return .${name} }\n      preconditionFailure("${type}.${name} requires iOS ${version}")\n`
        : `      return .${name}\n`
  }
  swift += `    default: preconditionFailure("invalid ${type}: \\(value)")\n    }\n  }\n`
}
swift += `  @MainActor @TabContentBuilder<String> static func tab<Content: View>(id: String, title: String, systemImage: String, badge: String, role: String, @ViewBuilder content: () -> Content) -> some TabContent<String> {
    Tab(value: id, role: tabRole(role)) { content() } label: {
      if systemImage.isEmpty { Text(title) } else { Label(title, systemImage: systemImage) }
    }
    .badge(badge.isEmpty ? nil : Text(badge))
  }
`
swift += '}\n\nextension View {\n'
for (const method of methods) {
  if (method.type.endsWith('Style')) {
    swift += `  @ViewBuilder func oneNative${method.name[0].toUpperCase() + method.name.slice(1)}(_ value: String) -> some View {\n    switch value {\n`
    for (const [name, version] of Object.entries(enums[method.type])) {
      swift += `    case "${name}":\n`
      swift +=
        version > 18
          ? `      if #available(iOS ${version}, *) { self.${method.name}(.${name}) } else { let _ = preconditionFailure("${method.type}.${name} requires iOS ${version}"); self }\n`
          : `      self.${method.name}(.${name})\n`
    }
    swift += `    default: let _ = preconditionFailure("invalid ${method.type}: \\(value)"); self\n    }\n  }\n`
    continue
  }
  const apply = `self.${method.name}(OneNativeGenerated.${method.type[0].toLowerCase() + method.type.slice(1)}(value))`
  swift += `  @ViewBuilder func oneNative${method.name[0].toUpperCase() + method.name.slice(1)}(_ value: String) -> some View {\n`
  if (method.ios > 18) {
    swift += `    if #available(iOS ${method.ios}, *) {\n      if value.isEmpty { self } else { ${apply} }\n    } else {\n      let _ = precondition(value.isEmpty, "${method.name} requires iOS ${method.ios}")\n      self\n    }\n`
  } else swift += `    if value.isEmpty { self } else { ${apply} }\n`
  swift += '  }\n'
}
swift += '}\n'
outputs.set('ios/Generated/OneNativeSwiftUI.swift', swift)
outputs.set(
  'ios/Generated/OneNativeMenuContent.swift',
  header +
    `import SwiftUI

enum OneNativeMenuKind: String {
${nodes.map((node) => `  case ${node.kind}`).join('\n')}
}
struct OneNativeMenuNode: Identifiable {
${Object.entries(nativeFields)
  .map(
    ([name, field]) =>
      `  let ${name}: ${name === 'type' ? 'OneNativeMenuKind' : field.type === 'boolean' ? 'Bool' : field.type === 'boolean[]' ? '[Bool]' : 'String'}`
  )
  .join('\n')}
  init(_ item: [String: Any]) {
${Object.entries(nativeFields)
  .map(([name, field]) =>
    name === 'type'
      ? '    type = OneNativeMenuKind(rawValue: item["type"] as! String)!'
      : `    ${name} = item["${name}"] as! ${field.type === 'boolean' ? 'Bool' : field.type === 'boolean[]' ? '[Bool]' : 'String'}`
  )
  .join('\n')}
  }
}
struct OneNativeMenuLabel: View {
  let item: OneNativeMenuNode
  var body: some View {
    if item.systemImage.isEmpty { Text(item.title) }
    else { Label(item.title, systemImage: item.systemImage) }
  }
}
struct OneNativeGeneratedMenuContent: View {
  @ObservedObject var model: OneNativeMenuModel
  let parentId: String
  var body: some View {
    ForEach(model.children[parentId] ?? []) { item in
      if !item.hidden {
        Group {
          switch item.type {
${nodes.map((node) => `          case .${node.kind}:\n            ${node.swift}`).join('\n')}
          }
        }
        .disabled(item.disabled)
        .help(item.help)
        .oneNativeMenuOrder(item.menuOrder)
        .oneNativeMenuActionDismissBehavior(item.menuActionDismissBehavior)
      }
    }
  }
}
`
)
outputs.set(
  'ios/Generated/OneNativeMenuPayload.h',
  header +
    `#ifdef __cplusplus
#import <React/RCTConversions.h>
#import <react/renderer/components/OneNativeSpec/Props.h>
template <typename Item>
inline bool OneNativeMenuItemsEqual(const std::vector<Item> &a, const std::vector<Item> &b) {
  if (a.size() != b.size()) return false;
  for (size_t i = 0; i < a.size(); i++) {
    if (${Object.keys(nativeFields)
      .map((name) => `a[i].${name} != b[i].${name}`)
      .join(' || ')}) return false;
  }
  return true;
}
template <typename Item>
inline NSArray *OneNativeMenuPayload(const std::vector<Item> &items) {
  NSMutableArray *result = [NSMutableArray new];
  for (const auto &item : items) {
    NSMutableArray *values = [NSMutableArray new];
    for (bool value : item.values) [values addObject:@(value)];
    [result addObject:@{
${Object.entries(nativeFields)
  .map(
    ([name, field]) =>
      `      @"${name}": ${field.type === 'boolean' ? `@(item.${name})` : field.type === 'boolean[]' ? 'values' : `RCTNSStringFromString(item.${name})`}`
  )
  .join(',\n')}
    }];
  }
  return result;
}
#endif
`
)
const manifest = {
  compiler: run(swiftc, ['--version'])
    .split('\n')
    .filter((line) => !line.startsWith('Target:'))
    .join('\n'),
  sdk: run('xcrun', ['--sdk', 'iphonesimulator', '--show-sdk-version']),
  inputs: paths.map((path, index) => ({
    module: ['SwiftUI', 'SwiftUICore'][index],
    sha256: createHash('sha256').update(readFileSync(path)).digest('hex'),
  })),
  extractedDeclarations: inventory.length,
  unmappedModifiers: [
    ...new Set(
      inventory
        .filter(
          (d) =>
            d.kind === 'func' &&
            shortOwner(d) === 'View' &&
            available(d) &&
            modifierFamilies.some((prefix) => d.name.startsWith(prefix)) &&
            !methods.some((m) => m.name === d.name)
        )
        .map((d) => d.name)
    ),
  ].sort(),
  enums,
  modifiers: methods,
  constructors: selected
    .filter((d) => d.kind === 'init')
    .map((d) => ({
      module: d.module,
      type: shortOwner(d),
      parameters: d.parameters,
      requirements: d.requirements,
      ios: ios(d),
    })),
}
outputs.set('codegen/swiftui-manifest.json', JSON.stringify(manifest, null, 2) + '\n')
const packagePath = join(root, 'package.json')
const packageMetadata = JSON.parse(readFileSync(packagePath, 'utf8'))
packageMetadata.codegenConfig.ios.componentProvider = Object.fromEntries(
  [
    ...components,
    ...controlComponents,
    ...sheetComponents,
    ...containerComponents,
    ...popoverComponents,
  ].map((component) => [
    component.name,
    component.name + 'ComponentView',
  ])
)
outputs.set('package.json', JSON.stringify(packageMetadata, null, 2) + '\n')
const changed: string[] = []
for (const [path, source] of outputs) {
  const temporary = join(cache, path.replaceAll('/', '_'))
  writeFileSync(temporary, source.trimEnd() + '\n')
  if (/\.tsx?$/.test(path))
    run('bunx', ['oxfmt', '-c', resolve(root, '../../.prettierrc'), temporary])
  const generated = readFileSync(temporary, 'utf8')
  let existing = ''
  try {
    existing = readFileSync(join(root, path), 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  if (existing !== generated) changed.push(path)
  if (!process.argv.includes('--check')) writeFileSync(join(root, path), generated)
}
if (process.argv.includes('--check') && changed.length)
  throw new Error('Generated SwiftUI bindings differ: ' + changed.join(', '))
// compile the assembled source so SDK provenance and emitted recipes are checked together.
run(swiftc, [
  '-typecheck',
  '-sdk',
  sdk,
  '-target',
  'arm64-apple-ios18.0-simulator',
  ...['ios', 'ios/Generated'].flatMap((dir) =>
    readdirSync(join(root, dir))
      .filter((file) => file.endsWith('.swift'))
      .map((file) => join(root, dir, file))
  ),
])
run(swiftc, [
  '-sdk',
  run('xcrun', ['--sdk', 'macosx', '--show-sdk-path']),
  join(root, 'ios/OneNativeControlled.swift'),
  join(root, 'codegen/VerifyControlled.swift'),
  '-o',
  join(cache, 'verify-controlled'),
])
console.log(run(join(cache, 'verify-controlled'), []))
console.log(
  `SwiftUI SDK ${manifest.sdk}: ${inventory.length} declarations, ${selected.length} mapped symbols, ${outputs.size} generated files${process.argv.includes('--check') ? ', verified' : ''}`
)
