// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
#include "OneNativeShareLinkShadowNode.h"

namespace facebook::react {
extern const char OneNativeShareLinkComponentName[] = "OneNativeShareLink";
}
