// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
#include "OneNativeEmptyViewShadowNode.h"

namespace facebook::react {
extern const char OneNativeEmptyViewComponentName[] = "OneNativeEmptyView";
}
