name: 'Install'
description: 'Install and build packages'
inputs:
  workspace-focus:
    required: false
    description: 'Only install and build a specific workspace (and its dependencies)'
    type: string
  install-playwright:
    required: false
    description: 'Install Playwright browsers (default: true)'
    default: 'true'
  npm-upgrade:
    required: false
    description: 'Upgrade npm to latest (needed for expo prebuild)'
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: 'package.json'

    # Expo prebuild runs a command like `npm view expo-template-bare-minimum@sdk-53 dist --json`
    # under the hood, which may fail with older npm versions (see https://github.com/npm/cli/issues/7834).
    - name: Upgrade npm
      if: ${{ inputs.npm-upgrade == 'true' }}
      shell: bash
      run: |
        npm install -g npm@latest
        npm --version

    - name: Cache Bun
      uses: actions/cache@v4
      env:
        cache-name: bun_cache
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-

    - name: Install Dependencies
      shell: bash
      run: bun install

    - name: Install Playwright
      if: ${{ inputs.install-playwright == 'true' }}
      shell: bash
      run: npx playwright install chromium

    - name: Build
      shell: bash
      run: ${{ inputs.workspace-focus && format('bunx turbo run build --filter={0}...', inputs.workspace-focus) || 'bun run build'}}
