name: 'Install'
description: 'Install and build packages'
inputs:
  workspace-focus:
    required: false
    description: 'Only install and build a specific workspace (and its dependencies)'
    type: string
runs:
  using: composite
  steps:
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        registry-url: 'https://registry.npmjs.org'

    # - name: install yarn
    #   shell: bash
    #   run: npm i yarn -g

    # - name: Install npm
    #   shell: bash
    #   run: npm i -g npm@10.8.2

    - name: Install corepack
      shell: bash
      run: corepack enable

    - name: Get Home Dir Path
      id: get-home-dir-path
      shell: bash
      run: |
        echo "Home dir path: $HOME"
        echo "path=$HOME" >> $GITHUB_OUTPUT

    - name: Cache Yarn Cache
      uses: cirruslabs/cache@v4
      env:
        cache-name: yarn_cache
      with:
        path: ${{ steps.get-home-dir-path.outputs.path }}/.yarn/berry
        key: ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-

    - name: Cache node_modules
      uses: cirruslabs/cache@v4
      env:
        cache-name: node_modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-${{ hashFiles('packages/vxrn/src/utils/depPatches.ts') }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-${{ hashFiles('packages/vxrn/src/utils/depPatches.ts') }}-

    - name: Cache Playwright
      uses: cirruslabs/cache@v4
      env:
        cache-name: playwright_cache
      with:
        path: ${{ steps.get-home-dir-path.outputs.path }}/.cache/ms-playwright
        key: ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}${{ inputs.workspace-focus && format('-{0}', inputs.workspace-focus) || '' }}-

    - name: Install Dependencies
      shell: bash
      run: ${{ inputs.workspace-focus && format('yarn workspaces focus vxrn-monorepo {0}', inputs.workspace-focus) || 'yarn install'}}

    - name: Install Playwright
      shell: bash
      run: npx playwright install

    - name: Clean Build
      shell: bash
      run: ${{ inputs.workspace-focus && format('yarn workspaces foreach -Rpt --from "{0}" run clean:build', inputs.workspace-focus) || 'yarn clean:build'}}

    - name: Build
      shell: bash
      run: ${{ inputs.workspace-focus && format('yarn workspaces foreach -Rpt --from "{0}" run build', inputs.workspace-focus) || 'yarn build'}}
