import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import type { Plugin } from 'vite'

// the contract parser loads on the first .kt import, so an app without one
// never evaluates it.
export function kotlinSourcePlugin(platform: 'ios' | 'android', root: string): Plugin {
  const appManifest = join(root, 'package.json')
  const app = existsSync(appManifest) ? JSON.parse(readFileSync(appManifest, 'utf8')) : {}
  const expo = Object.hasOwn(app.dependencies ?? {}, 'expo') || Object.hasOwn(app.devDependencies ?? {}, 'expo')
  return {
    name: 'one:kotlin-source',
    load: {
      filter: { id: /\.kt$/ },
      async handler(id) {
        if (platform !== 'android') {
          throw new Error(`[one] ${id} is Kotlin source and cannot be imported into an iOS build; use an .ios.ts entry`)
        }
        if (expo) throw new Error(`[one] ${id} needs one prebuild; direct Kotlin imports are not generated by Expo prebuild`)
        // the load hook reads the source itself, so the bundler's watcher never sees it.
        this.addWatchFile(id)
        const { kotlinSourceId, renderKotlinSourceGlue, writeNativeSourceDeclaration } =
          await import('vxrn/native-source-contract')
        const contract = writeNativeSourceDeclaration(id)
        const sourceId = kotlinSourceId(root, id)
        const hash = renderKotlinSourceGlue(sourceId, contract).hash
        const oneRoot = dirname(createRequire(id).resolve('one/package.json'))
        const nativeSource = join(oneRoot, 'dist/esm/platform/native-source/index.native.js')
        const exports = contract.modules.map((module) =>
          `export const ${module.name} = Object.freeze({${module.methods.map((method) =>
            `${method.name}: (...args) => callNativeSource(${JSON.stringify(`${sourceId}.${module.name}`)}, ${JSON.stringify(method.name)}, args, ${JSON.stringify(hash)})`
          ).join(',')}})`
        ).join('\n')
        if (!exports) throw new Error(`[one] ${id} has no OneModule object to import`)
        return `import { callNativeSource } from ${JSON.stringify(nativeSource)}\n${exports}\n`
      },
    },
  }
}
