import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { swiftPackageDirOf, swiftPackageId } from 'vxrn/swift-package-id'
import type { Plugin } from 'vite'

// on device a .swift import is the swift package compiled into the app by
// prebuild (see vxrn generateSwiftPackages): the module is a host view naming
// the package, with the importer's props passed through as json. an imported
// file whose @main type is an App is a whole swift app, so its root fills the
// screen instead of sizing to its content. the contract parser loads on the
// first .swift import, so an app without one never evaluates it.
export function swiftPackagePlugin(platform: 'ios' | 'android', root: string): Plugin {
  const appManifest = join(root, 'package.json')
  const app = existsSync(appManifest) ? JSON.parse(readFileSync(appManifest, 'utf8')) : {}
  const expo = Object.hasOwn(app.dependencies ?? {}, 'expo') || Object.hasOwn(app.devDependencies ?? {}, 'expo')
  return {
    name: 'one:swift-package',
    load: {
      filter: { id: /\.swift$/ },
      async handler(id) {
        if (platform !== 'ios') {
          throw new Error(`[one] ${id} is Swift source and cannot be imported into an Android build; use an .android.ts entry`)
        }
        if (expo) throw new Error(`[one] ${id} needs one prebuild; direct Swift imports are not generated by Expo prebuild`)
        const packageDir = swiftPackageDirOf(id)
        if (!packageDir) {
          throw new Error(`[one] ${id} is not inside a swift package (no Package.swift above it)`)
        }
        const { writeNativeSourceDeclaration, writeSwiftPackageArtifacts } = await import(
          'vxrn/native-source-contract'
        )
        const contract = writeNativeSourceDeclaration(id)
        const packageName = swiftPackageId(packageDir)
        const artifacts = writeSwiftPackageArtifacts(packageDir)
        const hash = artifacts.hash
        // the load hook reads the source itself, so the bundler's watcher never
        // sees it; every file in the package feeds the contract hash.
        for (const file of Object.keys(artifacts.files)) this.addWatchFile(join(packageDir, file))
        const fill = /@main\s+struct\s+\w+\s*:\s*(SwiftUI\.)?App\b/.test(readFileSync(id, 'utf8'))
        // the generated module is bundled as if it lived at the .swift file, so
        // one's own swift host resolves from the importer to an absolute path.
        const oneRoot = dirname(createRequire(id).resolve('one/package.json'))
        const swiftHost = join(oneRoot, 'dist/esm/platform/swift/index.native.js')
        const nativeSource = join(oneRoot, 'dist/esm/platform/native-source/index.native.js')
        const exports = contract.modules.map((module) =>
          `export const ${module.name} = Object.freeze({${module.methods.map((method) =>
            `${method.name}: (...args) => callNativeSource(${JSON.stringify(`${packageName}.${module.name}`)}, ${JSON.stringify(method.name)}, args, ${JSON.stringify(hash)})`
          ).join(',')}})`
        ).join('\n')
        return `${contract.modules.length > 0 ? `import { callNativeSource } from ${JSON.stringify(nativeSource)}\n` : ''}${contract.defaultView ? `import { createElement } from 'react'
import { SwiftPackageView } from ${JSON.stringify(swiftHost)}
export default function SwiftPackage(props) {
  return createElement(SwiftPackageView, { packageName: ${JSON.stringify(packageName)}, props, fill: ${fill} })
}
` : ''}${exports}
`
      },
    },
  }
}
