import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { blessedNativePackages } from '../packages/one/src/native-packages'

const root = resolve(import.meta.dirname, '..')
const check = process.argv.includes('--check')
const dependencies = Object.fromEntries(
  blessedNativePackages.map(({ name, range }) => [name, range])
)
function update(file: string, content: string) {
  const target = resolve(root, file)
  if (readFileSync(target, 'utf8') === content) return
  if (check)
    throw new Error(
      `${file} differs from one/native-packages; run bun sync:native-packages`
    )
  writeFileSync(target, content)
}

const starterFile = 'examples/one-basic/package.json'
const starter = JSON.parse(readFileSync(resolve(root, starterFile), 'utf8'))
Object.assign(starter.dependencies, dependencies)
update(starterFile, JSON.stringify(starter, null, 2) + '\n')

const oneFile = 'packages/one/package.json'
const one = JSON.parse(readFileSync(resolve(root, oneFile), 'utf8'))
Object.assign(one.peerDependencies, dependencies)
Object.assign(one.devDependencies, dependencies)
update(oneFile, JSON.stringify(one, null, 2) + '\n')

const installFile = 'apps/onestack.dev/data/docs/installation.mdx'
const installation = readFileSync(resolve(root, installFile), 'utf8')
update(
  installFile,
  installation.replace(
    /(```json fileName=package.json\n)([\s\S]*?)(\n```)/,
    (_match, start, body, end) => {
      const manifest = JSON.parse(body)
      Object.assign(manifest.dependencies, dependencies)
      return start + JSON.stringify(manifest, null, 2) + end
    }
  )
)

const setupFile = 'apps/onestack.dev/data/docs/native-setup.mdx'
const setup = readFileSync(resolve(root, setupFile), 'utf8')
const table = [
  '<!-- native-packages:start (generated by bun sync:native-packages) -->',
  '| Package | Tested range | Native requirement | Purpose |',
  '| --- | --- | --- | --- |',
  ...blessedNativePackages.map(
    (pkg) =>
      `| \`${pkg.name}\` | \`${pkg.range}\` | ${pkg.required ? 'Required' : 'Recommended'} | ${pkg.why} |`
  ),
  '<!-- native-packages:end -->',
].join('\n')
update(
  setupFile,
  setup.replace(/<!-- native-packages:start[\s\S]*?<!-- native-packages:end -->/, table)
)
