/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "replication-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "replication-manager": {
      "service": string
      "type": "sst.aws.Service"
    }
    "vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
