// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { ViewProps } from 'react-native'
import type {
  DirectEventHandler,
  Int32,
  Double,
} from 'react-native/Libraries/Types/CodegenTypes'
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent'
type UiMapMarker = Readonly<{
  id: string
  title: string
  latitude: Double
  longitude: Double
  tint: string
}>

interface NativeProps extends ViewProps {
  latitude: Double
  longitude: Double
  zoom: Double
  markers: ReadonlyArray<UiMapMarker>
  overlays: string
  onNativeUiMapCameraMove?: DirectEventHandler<
    Readonly<{ latitude: Double; longitude: Double; zoom: Double }>
  >
  onNativeUiMapMarkerClick?: DirectEventHandler<Readonly<{ id: string }>>
  onNativeUiMapClick?: DirectEventHandler<
    Readonly<{ latitude: Double; longitude: Double }>
  >
}
export default codegenNativeComponent<NativeProps>('OneNativeUiMap')
