// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
#include "OneNativeLabelShadowNode.h"

namespace facebook::react {
extern const char OneNativeLabelComponentName[] = "OneNativeLabel";
}
