// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
#pragma once
#ifdef __cplusplus
#include <react/renderer/components/OneNativeSpec/EventEmitters.h>
#include <react/renderer/components/OneNativeSpec/Props.h>
#include "OneNativeMeasuredShadowNode.h"
namespace facebook::react {
extern const char OneNativeButtonComponentName[];
using OneNativeButtonShadowNode = OneNativeMeasuredShadowNode<OneNativeButtonComponentName, OneNativeButtonProps, OneNativeButtonEventEmitter>;
using OneNativeButtonComponentDescriptor = OneNativeMeasuredComponentDescriptor<OneNativeButtonShadowNode>;
}
#endif
