// generated by bun run generate from the SwiftUI SDK and codegen/catalog.ts.
// edit the generator or catalog, then regenerate.
import type { NativeMenuItem } from './specs/OneNativeMenuNativeComponent'
import type { MenuItem } from './types'
import { assertSwiftUIValue, swiftUIValues } from './generated/swiftui'
const definitions: Record<
  string,
  {
    fields: Record<string, { type: string; default: unknown; required: boolean }>
    children: boolean
  }
> = {
  action: {
    fields: {
      id: {
        type: 'string',
        default: '',
        required: true,
      },
      title: {
        type: 'string',
        default: '',
        required: true,
      },
      systemImage: {
        type: 'string',
        default: '',
        required: false,
      },
      role: {
        type: 'ButtonRole',
        default: '',
        required: false,
      },
      disabled: {
        type: 'boolean',
        default: false,
        required: false,
      },
      hidden: {
        type: 'boolean',
        default: false,
        required: false,
      },
      help: {
        type: 'string',
        default: '',
        required: false,
      },
      menuActionDismissBehavior: {
        type: 'MenuActionDismissBehavior',
        default: '',
        required: false,
      },
    },
    children: false,
  },
  toggle: {
    fields: {
      id: {
        type: 'string',
        default: '',
        required: true,
      },
      title: {
        type: 'string',
        default: '',
        required: true,
      },
      systemImage: {
        type: 'string',
        default: '',
        required: false,
      },
      values: {
        type: 'boolean[]',
        default: [],
        required: true,
      },
      disabled: {
        type: 'boolean',
        default: false,
        required: false,
      },
      hidden: {
        type: 'boolean',
        default: false,
        required: false,
      },
      help: {
        type: 'string',
        default: '',
        required: false,
      },
      menuActionDismissBehavior: {
        type: 'MenuActionDismissBehavior',
        default: '',
        required: false,
      },
    },
    children: false,
  },
  submenu: {
    fields: {
      id: {
        type: 'string',
        default: '',
        required: true,
      },
      title: {
        type: 'string',
        default: '',
        required: true,
      },
      systemImage: {
        type: 'string',
        default: '',
        required: false,
      },
      disabled: {
        type: 'boolean',
        default: false,
        required: false,
      },
      hidden: {
        type: 'boolean',
        default: false,
        required: false,
      },
      help: {
        type: 'string',
        default: '',
        required: false,
      },
      menuOrder: {
        type: 'MenuOrder',
        default: '',
        required: false,
      },
      menuActionDismissBehavior: {
        type: 'MenuActionDismissBehavior',
        default: '',
        required: false,
      },
    },
    children: true,
  },
  section: {
    fields: {
      id: {
        type: 'string',
        default: '',
        required: true,
      },
      title: {
        type: 'string',
        default: '',
        required: false,
      },
      hidden: {
        type: 'boolean',
        default: false,
        required: false,
      },
    },
    children: true,
  },
  controlGroup: {
    fields: {
      id: {
        type: 'string',
        default: '',
        required: true,
      },
      title: {
        type: 'string',
        default: '',
        required: false,
      },
      systemImage: {
        type: 'string',
        default: '',
        required: false,
      },
      disabled: {
        type: 'boolean',
        default: false,
        required: false,
      },
      hidden: {
        type: 'boolean',
        default: false,
        required: false,
      },
      controlGroupStyle: {
        type: 'ControlGroupStyle',
        default: 'automatic',
        required: false,
      },
    },
    children: true,
  },
  divider: {
    fields: {
      id: {
        type: 'string',
        default: '',
        required: true,
      },
    },
    children: false,
  },
}
const defaults = {
  id: '',
  title: '',
  systemImage: '',
  role: '',
  disabled: false,
  hidden: false,
  help: '',
  controlGroupStyle: 'automatic',
  values: [],
  menuOrder: '',
  menuActionDismissBehavior: '',
}
export function flattenMenuItems(
  items: readonly MenuItem[],
  iosVersion = 18
): NativeMenuItem[] {
  const result: NativeMenuItem[] = []
  const ids = new Set<string>()
  const append = (
    items: readonly MenuItem[],
    parentId: string,
    disabled: boolean,
    hidden: boolean
  ) => {
    for (const item of items) {
      const definition = definitions[item.type]
      if (!definition) throw new Error('Unknown Swift.Menu item type: ' + item.type)
      const input = item as unknown as Record<string, unknown>
      for (const name of Object.keys(input)) {
        if (
          name !== 'type' &&
          !(name === 'children' && definition.children) &&
          !Object.hasOwn(definition.fields, name)
        )
          throw new Error('Unsupported Swift.Menu ' + item.type + ' property: ' + name)
      }
      const payload: Record<string, unknown> = { ...defaults, parentId, type: item.type }
      for (const [name, field] of Object.entries(definition.fields)) {
        const value = input[name] ?? field.default
        if (field.required && input[name] == null)
          throw new Error('Swift.Menu ' + item.type + ' requires ' + name)
        if (field.type === 'boolean[]') {
          if (
            !Array.isArray(value) ||
            !value.length ||
            value.some((v) => typeof v !== 'boolean')
          )
            throw new Error('Swift.Menu toggle values must be a nonempty boolean array')
        } else if (Object.hasOwn(swiftUIValues, field.type)) {
          if (typeof value !== 'string') throw new Error('Invalid Swift.Menu ' + name)
          if (value !== '' || field.default !== '')
            assertSwiftUIValue(
              field.type as keyof typeof swiftUIValues,
              value,
              iosVersion
            )
        } else if (typeof value !== field.type)
          throw new Error('Invalid Swift.Menu ' + name)
        payload[name] = value
      }
      if (!item.id || ids.has(item.id))
        throw new Error(
          'Swift.Menu requires unique, nonempty item ids: "' + item.id + '"'
        )
      ids.add(item.id)
      payload.disabled = disabled || payload.disabled
      payload.hidden = hidden || payload.hidden
      result.push(payload as unknown as NativeMenuItem)
      if (definition.children) {
        if (!Array.isArray(input.children))
          throw new Error('Swift.Menu ' + item.type + ' requires children')
        append(
          input.children,
          item.id,
          Boolean(payload.disabled),
          Boolean(payload.hidden)
        )
      }
    }
  }
  append(items, '', false, false)
  return result
}
