name: Changelog

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Changelog
    runs-on: ubuntu-latest
    # needs: release

    permissions:
      contents: write

    steps:
      - uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          generate_release_notes: true
