/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "chat-replication-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "chat-replication-manager": {
      "service": string
      "type": "sst.aws.Service"
    }
    "chat-view-syncer": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "chat-vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
