import { createHash, randomUUID } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, relative } from 'node:path'
import { swiftPackageDirectories, swiftPackageId } from './swiftPackageId'

export interface NativeSourceMethod {
  name: string
  parameters: { name: string; label: string | null; type: string; nativeType: string }[]
  result: string
  nativeResult: string
  throws: boolean
  async: boolean
}

export interface NativeSourceModule {
  name: string
  methods: NativeSourceMethod[]
}

// a public @Composable function in a .kt file: imported as a react component
// whose props are its parameters. a function-typed parameter is a callback.
export interface NativeSourceViewProp {
  name: string
  type: string
  nativeType: string
  optional: boolean
  callback: { type: string; nativeType: string }[] | null
}

export interface NativeSourceView {
  name: string
  props: NativeSourceViewProp[]
}

export interface NativeSourceContract {
  language: 'swift' | 'kotlin'
  packageName?: string
  modules: NativeSourceModule[]
  views: NativeSourceView[]
  defaultView: boolean
  hash: string
  declaration: string
}

export interface SwiftPackageArtifacts {
  packageId: string
  hash: string
  files: Record<string, string[]>
  modules: Record<string, string[]>
  defaultViewFiles: string[]
  contracts: NativeSourceContract[]
  glue: string
}

const GENERATED_HEADER = '// generated by one typegen; edits will be replaced\n'
const SKIP_SOURCE_DIRS = new Set(['node_modules', 'ios', 'android', 'dist', 'types', 'build', '.build'])

function writeGeneratedFile(file: string, content: string): void {
  try {
    if (readFileSync(file, 'utf8') === content) return
  } catch (error) {
    if (!error || typeof error !== 'object' || !('code' in error) || error.code !== 'ENOENT') throw error
  }
  const temporary = join(dirname(file), `.${basename(file)}.${randomUUID()}.tmp`)
  try {
    writeFileSync(temporary, content)
    renameSync(temporary, file)
  } finally {
    rmSync(temporary, { force: true })
  }
}

interface Token {
  text: string
  line: number
  column: number
}

function fail(file: string, token: Token | undefined, message: string): never {
  throw new Error(`${file}:${(token?.line ?? 0) + 1}:${(token?.column ?? 0) + 1}: ${message}`)
}

// only declarations are read. strings and comments cannot supply a marker,
// method, brace, or type; native compilers validate every emitted call.
function tokens(file: string, source: string): Token[] {
  const result: Token[] = []
  let offset = 0
  let line = 0
  let column = 0
  const advance = () => {
    if (source[offset] === '\n') { line++; column = 0 }
    else column++
    offset++
  }
  while (offset < source.length) {
    const char = source[offset]
    if (/\s/.test(char)) { advance(); continue }
    if (source.startsWith('//', offset)) {
      while (offset < source.length && source[offset] !== '\n') advance()
      continue
    }
    if (source.startsWith('/*', offset)) {
      let depth = 0
      do {
        if (source.startsWith('/*', offset)) { depth++; advance(); advance() }
        else if (source.startsWith('*/', offset)) { depth--; advance(); advance() }
        else advance()
      } while (depth > 0 && offset < source.length)
      if (depth > 0) fail(file, { text: '/*', line, column }, 'unclosed native source comment')
      continue
    }
    if (char === '"' || char === "'") {
      const quote = source.startsWith(char.repeat(3), offset) ? char.repeat(3) : char
      for (let n = 0; n < quote.length; n++) advance()
      while (offset < source.length && !source.startsWith(quote, offset)) {
        if (source[offset] === '\\') advance()
        advance()
      }
      if (offset >= source.length) fail(file, { text: quote, line, column }, 'unclosed native source string')
      for (let n = 0; n < quote.length; n++) advance()
      continue
    }
    const start = offset
    const startLine = line
    const startColumn = column
    if (/[A-Za-z_]/.test(char)) {
      while (offset < source.length && /[A-Za-z0-9_]/.test(source[offset])) advance()
    } else if (source.startsWith('->', offset)) {
      advance(); advance()
    } else advance()
    result.push({ text: source.slice(start, offset), line: startLine, column: startColumn })
  }
  return result
}

function close(file: string, list: Token[], start: number, left: string, right: string): number {
  let depth = 0
  for (let i = start; i < list.length; i++) {
    if (list[i].text === left) depth++
    if (list[i].text === right && --depth === 0) return i
  }
  fail(file, list[start], `unclosed ${left} in native export`)
}

function split(list: Token[], separator: string): Token[][] {
  const parts: Token[][] = []
  let start = 0
  let square = 0
  let angle = 0
  let round = 0
  for (let i = 0; i < list.length; i++) {
    const value = list[i].text
    if (value === '[') square++
    if (value === ']') square--
    if (value === '<') angle++
    if (value === '>') angle--
    if (value === '(') round++
    if (value === ')') round--
    if (value === separator && square === 0 && angle === 0 && round === 0) {
      parts.push(list.slice(start, i))
      start = i + 1
    }
  }
  parts.push(list.slice(start))
  return parts
}

function tsType(file: string, list: Token[], language: 'swift' | 'kotlin'): string {
  if (list.length === 0) fail(file, list[0], 'native export needs an explicit type')
  if (list.at(-1)?.text === '?') return `${tsType(file, list.slice(0, -1), language)} | null`
  const value = list.map((token) => token.text).join('')
  if (value === 'String') return 'string'
  if (value === 'Bool' || value === 'Boolean') return 'boolean'
  if (['Double', 'Float', 'Int', 'Long'].includes(value)) return 'number'
  if (value === 'Void' || value === 'Unit') return 'void'
  if (language === 'swift' && list[0].text === '[' && list.at(-1)?.text === ']') {
    const inner = list.slice(1, -1)
    const entries = split(inner, ':')
    if (entries.length === 1) return `${tsType(file, inner, language)}[]`
    if (entries.length === 2 && entries[0].map((token) => token.text).join('') === 'String') {
      return `Record<string, ${tsType(file, entries[1], language)}>`
    }
  }
  if (language === 'kotlin' && list[1]?.text === '<' && list.at(-1)?.text === '>') {
    const entries = split(list.slice(2, -1), ',')
    if (list[0].text === 'List' && entries.length === 1) return `${tsType(file, entries[0], language)}[]`
    if (list[0].text === 'Map' && entries.length === 2 && entries[0].map((token) => token.text).join('') === 'String') {
      return `Record<string, ${tsType(file, entries[1], language)}>`
    }
  }
  fail(file, list[0], `unsupported native export type ${value}`)
}

function parameters(file: string, list: Token[], language: 'swift' | 'kotlin'): NativeSourceMethod['parameters'] {
  if (list.length === 0) return []
  return split(list, ',').map((part, index) => {
    if (part.some((token) => token.text === '=')) fail(file, part[0], 'default native export arguments are unsupported')
    const colon = part.findIndex((token) => token.text === ':')
    if (colon < 0) fail(file, part[0], 'native export parameter needs an explicit type')
    const names = part.slice(0, colon).filter((token) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(token.text))
    const name = (language === 'swift' ? names.at(-1) : names[0])?.text ?? `arg${index}`
    if (name === '_') fail(file, part[0], 'native export parameter needs an internal name')
    const label = language === 'swift' ? names[0]?.text ?? name : null
    const sourceType = part.slice(colon + 1)
    return { name, label, type: tsType(file, sourceType, language), nativeType: sourceType.map((token) => token.text).join('') }
  })
}

const DECLARATION_MODIFIERS = new Set([
  'private', 'fileprivate', 'public', 'internal', 'open', 'override', 'static', 'class', 'final',
  'suspend', 'inline', 'operator', 'infix', 'tailrec', 'external', 'nonisolated', 'isolated',
  'mutating', 'nonmutating', 'dynamic', 'required', 'convenience', 'optional',
])

// a method's modifiers are the words and attributes directly before its keyword:
// a property declared above it (`private var hits = 0`) is not part of it
function declarationStart(list: Token[], floor: number, keyword: number): number {
  let first = keyword
  while (first > floor) {
    const text = list[first - 1].text
    if (DECLARATION_MODIFIERS.has(text)) { first--; continue }
    if (list[first - 2]?.text === '@') { first -= 2; continue }
    if (text === ')') {
      let open = first - 1
      for (let depth = 0; open > floor; open--) {
        if (list[open].text === ')') depth++
        if (list[open].text === '(' && --depth === 0) break
      }
      if (list[open - 2]?.text === '@') { first = open - 2; continue }
    }
    break
  }
  return first
}

function methods(file: string, list: Token[], start: number, end: number, language: 'swift' | 'kotlin'): NativeSourceMethod[] {
  const result: NativeSourceMethod[] = []
  let i = start + 1
  let previous = i
  const keyword = language === 'swift' ? 'func' : 'fun'
  while (i < end) {
    if (list[i].text === '{') { i = close(file, list, i, '{', '}') + 1; previous = i; continue }
    if (list[i].text !== keyword) { i++; continue }
    const modifiers = list.slice(declarationStart(list, previous, i), i).map((token) => token.text)
    const hidden = modifiers.includes('private') || modifiers.includes('fileprivate')
    if (!hidden && (modifiers.includes('static') || modifiers.includes('class'))) {
      fail(file, list[i], 'static native exports are unsupported')
    }
    const name = list[i + 1]?.text
    if (!name || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) fail(file, list[i], 'native export has no method name')
    if (result.some((method) => method.name === name)) fail(file, list[i], `overloaded native export ${name} is unsupported`)
    if (list[i + 2]?.text === '<') fail(file, list[i], 'generic native exports are unsupported')
    const open = i + 2
    if (list[open]?.text !== '(') fail(file, list[i], 'native export has no parameter list')
    const closing = close(file, list, open, '(', ')')
    const args = hidden ? [] : parameters(file, list.slice(open + 1, closing), language)
    let headerEnd = closing + 1
    while (headerEnd < end && !['{', '=', ';'].includes(list[headerEnd].text)) headerEnd++
    const header = list.slice(closing + 1, headerEnd)
    const separator = header.findIndex((token) => token.text === (language === 'swift' ? '->' : ':'))
    const sourceType = hidden || separator < 0 ? [] : header.slice(separator + 1)
    const type = sourceType.length === 0 ? 'void' : tsType(file, sourceType, language)
    if (!hidden) {
      result.push({
        name,
        parameters: args,
        result: type,
        nativeResult: sourceType.length === 0 ? language === 'swift' ? 'Void' : 'Unit' : sourceType.map((token) => token.text).join(''),
        throws: language === 'swift' ? header.some((token) => token.text === 'throws') : true,
        async: language === 'swift' ? header.some((token) => token.text === 'async') : modifiers.includes('suspend'),
      })
    }
    if (list[headerEnd]?.text === '{') i = close(file, list, headerEnd, '{', '}') + 1
    else if (list[headerEnd]?.text === '=') {
      const bodyLine = list[headerEnd].line
      i = headerEnd + 1
      while (i < end && list[i].line === bodyLine && list[i].text !== ';') i++
    } else i = headerEnd + 1
    previous = i
  }
  return result
}

function viewProp(file: string, part: Token[]): NativeSourceViewProp | null {
  const colon = part.findIndex((token) => token.text === ':')
  if (colon !== 1 || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(part[0].text)) {
    fail(file, part[0], 'composable parameter needs a name and an explicit type')
  }
  const name = part[0].text
  const equals = split(part.slice(colon + 1), '=')
  const typeTokens = equals[0]
  const fallback = equals[1]?.map((token) => token.text).join('')
  const nativeType = typeTokens.map((token) => token.text).join('')
  // the host supplies the modifier: the composable keeps its own default
  if (nativeType === 'Modifier') {
    if (fallback !== 'Modifier') fail(file, part[0], 'a composable modifier parameter needs the default Modifier')
    return null
  }
  const nullable = typeTokens.at(-1)?.text === '?'
  if (fallback !== undefined && !(nullable && fallback === 'null')) {
    fail(file, part[0], `composable parameter ${name} may only default to null`)
  }
  const optional = fallback !== undefined
  // (A, B) -> Unit, optionally parenthesized and nullable
  let fn = nullable ? typeTokens.slice(0, -1) : typeTokens
  if (fn[0]?.text === '(' && close(file, fn, 0, '(', ')') === fn.length - 1 && fn.some((token) => token.text === '->')) {
    fn = fn.slice(1, -1)
  }
  const arrow = fn.findIndex((token) => token.text === '->')
  if (arrow >= 0 && fn[0]?.text === '(' && close(file, fn, 0, '(', ')') === arrow - 1) {
    const result = fn.slice(arrow + 1).map((token) => token.text).join('')
    if (result !== 'Unit') fail(file, part[0], `composable callback ${name} must return Unit`)
    const inner = fn.slice(1, arrow - 1)
    const callback = inner.length === 0 ? [] : split(inner, ',').map((arg) => ({
      type: tsType(file, arg, 'kotlin'),
      nativeType: arg.map((token) => token.text).join(''),
    }))
    const signature = `(${callback.map((arg, index) => `value${index}: ${arg.type}`).join(', ')}) => void`
    return { name, type: nullable ? `(${signature}) | null` : signature, nativeType, optional, callback }
  }
  return { name, type: tsType(file, typeTokens, 'kotlin'), nativeType, optional, callback: null }
}

// a top-level public @Composable fun, or null for any other top-level fun
function composableView(file: string, list: Token[], keyword: number, floor: number): NativeSourceView | null {
  const modifiers = list.slice(declarationStart(list, floor, keyword), keyword).map((token) => token.text)
  if (!modifiers.some((value, index) => value === '@' && modifiers[index + 1] === 'Composable')) return null
  if (modifiers.includes('private') || modifiers.includes('internal')) return null
  const name = list[keyword + 1]?.text
  if (!name || !/^[A-Z][A-Za-z0-9_]*$/.test(name)) fail(file, list[keyword], 'an imported composable needs a capitalized name')
  if (list[keyword + 2]?.text !== '(') fail(file, list[keyword], 'generic or extension composables are unsupported')
  const closing = close(file, list, keyword + 2, '(', ')')
  if (list[closing + 1]?.text === ':') fail(file, list[closing + 1], `composable ${name} must return Unit`)
  const inner = list.slice(keyword + 3, closing)
  const props = inner.length === 0 ? [] : split(inner, ',').flatMap((part) => {
    if (part.length === 0) return []
    const prop = viewProp(file, part)
    return prop ? [prop] : []
  })
  return { name, props }
}

export function nativeSourceContract(file: string, source: string): NativeSourceContract {
  const language = file.endsWith('.swift') ? 'swift' : file.endsWith('.kt') ? 'kotlin' : undefined
  if (!language) throw new Error(`${file}: expected a .swift or .kt source file`)
  const list = tokens(file, source)
  const packageToken = language === 'kotlin' ? list.findIndex((token) => token.text === 'package') : -1
  const packageName = packageToken < 0 ? undefined : list
    .slice(packageToken + 1)
    .filter((token) => token.line === list[packageToken].line)
    .map((token) => token.text)
    .join('')
  if (packageName && !/^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(packageName)) {
    fail(file, list[packageToken], `unsupported kotlin package ${packageName}`)
  }
  const modules: NativeSourceModule[] = []
  const views: NativeSourceView[] = []
  let defaultView = false
  let i = 0
  let previous = 0
  while (i < list.length) {
    const kind = list[i].text
    const declaration = language === 'swift' ? kind === 'class' || kind === 'struct' : kind === 'object'
    if (language === 'kotlin' && kind === 'fun') {
      const view = composableView(file, list, i, previous)
      if (view) {
        if (views.some((other) => other.name === view.name)) fail(file, list[i], `overloaded composable ${view.name} is unsupported`)
        views.push(view)
      }
      i++
      continue
    }
    if (!declaration) {
      if (kind === '{') { i = close(file, list, i, '{', '}') + 1; previous = i }
      else i++
      continue
    }
    const name = list[i + 1]?.text
    if (!name) fail(file, list[i], 'native type has no name')
    let body = i + 2
    while (body < list.length && list[body].text !== '{') body++
    if (body === list.length) fail(file, list[i], 'native type has no body')
    const end = close(file, list, body, '{', '}')
    const prefix = list.slice(previous, i).map((token) => token.text)
    if (language === 'swift' && prefix.some((value, index) => value === '@' && prefix[index + 1] === 'main')) {
      defaultView = true
    }
    const inherits = list.slice(i + 2, body).map((token) => token.text)
    if (inherits.includes(language === 'swift' ? 'RNXModule' : 'OneModule')) {
      modules.push({ name, methods: methods(file, list, body, end, language) })
    }
    i = end + 1
    previous = i
  }
  const canonical = JSON.stringify({ language, packageName, modules, views, defaultView })
  const hash = createHash('sha256').update(canonical).digest('hex')
  const declarations = modules.map((module) => [
    `export declare const ${module.name}: {`,
    ...module.methods.map((method) =>
      `  ${method.name}(${method.parameters.map((param) => `${param.name}: ${param.type}`).join(', ')}): Promise<${method.result}>`
    ),
    '}',
  ].join('\n'))
  declarations.push(...views.map((view) =>
    `export declare function ${view.name}(props: {${view.props.map((prop) => ` ${prop.name}${prop.optional ? '?' : ''}: ${prop.type}`).join(';')} }): ReactElement`
  ))
  if (defaultView) {
    declarations.unshift("export default function SwiftPackage(props: Record<string, unknown>): ReactElement")
  }
  if (defaultView || views.length > 0) declarations.unshift("import type { ReactElement } from 'react'")
  const declaration = `${GENERATED_HEADER}${declarations.join('\n\n')}\n`
  return { language, packageName, modules, views, defaultView, hash, declaration }
}

export function kotlinSourceId(root: string, file: string): string {
  const path = relative(root, file).replaceAll('\\', '/')
  if (path.startsWith('../') || !path.endsWith('.kt')) {
    throw new Error(`${file} is not a kotlin source under ${root}`)
  }
  return `K_${createHash('sha256').update(path).digest('hex').slice(0, 16)}`
}

export function swiftPodManifest(file: string, source: string): {
  languageMode: 5 | 6
  mainActorIsolation: boolean
} {
  const list = tokens(file, source)
  const modes = new Set<number>()
  let mainActorIsolation = false
  for (let i = 0; i < list.length; i++) {
    if (list[i].text === '.' && list[i + 1]?.text === 'package' && list[i + 2]?.text === '(') {
      fail(file, list[i], 'SwiftPM package dependencies are unsupported by One prebuild')
    }
    if (list[i].text === '.' && list[i + 1]?.text === 'swiftLanguageMode' && list[i + 2]?.text === '(') {
      const mode = /^v(\d+)$/.exec(list[i + 4]?.text ?? '')
      if (list[i + 3]?.text !== '.' || !mode) fail(file, list[i], 'unsupported swift language mode')
      modes.add(Number(mode[1]))
    }
    if (list[i].text === 'swiftLanguageModes' && list[i + 1]?.text === ':') {
      const opening = i + 2
      if (list[opening]?.text !== '[') fail(file, list[i], 'unsupported swift language modes')
      const ending = close(file, list, opening, '[', ']')
      for (let j = opening; j < ending; j++) {
        if (list[j].text === '.' && /^v\d+$/.test(list[j + 1]?.text ?? '')) {
          modes.add(Number(list[j + 1].text.slice(1)))
        }
      }
    }
    if (list[i].text === '.' && list[i + 1]?.text === 'defaultIsolation' && list[i + 2]?.text === '(') {
      if (list[i + 3]?.text !== 'MainActor') fail(file, list[i], 'unsupported swift default isolation')
      mainActorIsolation = true
    }
  }
  if (modes.size > 1) throw new Error(`${file}: One pod needs one swift language mode; found ${[...modes].join(', ')}`)
  const languageMode = modes.values().next().value ?? 5
  if (languageMode !== 5 && languageMode !== 6) {
    throw new Error(`${file}: unsupported swift language mode v${languageMode}`)
  }
  return { languageMode, mainActorIsolation }
}

export function writeNativeSourceDeclaration(file: string): NativeSourceContract {
  const contract = nativeSourceContract(file, readFileSync(file, 'utf8'))
  const extension = contract.language === 'swift' ? '.swift' : '.kt'
  const declaration = join(dirname(file), `${basename(file, extension)}.d${extension}.ts`)
  if (contract.modules.length === 0 && contract.views.length === 0 && !contract.defaultView) {
    if (existsSync(declaration) && readFileSync(declaration, 'utf8').startsWith(GENERATED_HEADER)) {
      rmSync(declaration, { force: true })
    }
    return contract
  }
  writeGeneratedFile(declaration, contract.declaration)
  return contract
}

export function writeNativeSourceDeclarations(root: string): NativeSourceContract[] {
  const contracts: NativeSourceContract[] = []
  const visit = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || SKIP_SOURCE_DIRS.has(entry.name)) continue
      const file = join(dir, entry.name)
      if (entry.isDirectory()) visit(file)
      else if (entry.isFile() && /\.(swift|kt)$/.test(entry.name) && entry.name !== 'Package.swift') {
        contracts.push(writeNativeSourceDeclaration(file))
      }
    }
  }
  visit(root)
  for (const packageDir of swiftPackageDirectories(root).values()) {
    writeSwiftPackageArtifacts(packageDir)
  }
  return contracts
}

export function writeSwiftPackageArtifacts(packageDir: string): SwiftPackageArtifacts {
  const contracts: NativeSourceContract[] = []
  const files: Record<string, string[]> = {}
  const modules: Record<string, string[]> = {}
  const defaultViewFiles: string[] = []
  const visit = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || SKIP_SOURCE_DIRS.has(entry.name)) continue
      const file = join(dir, entry.name)
      if (entry.isDirectory()) visit(file)
      else if (entry.isFile() && entry.name.endsWith('.swift') && entry.name !== 'Package.swift') {
        const contract = writeNativeSourceDeclaration(file)
        contracts.push(contract)
        const name = relative(packageDir, file).replaceAll('\\', '/')
        files[name] = contract.modules.map((module) => module.name)
        for (const module of contract.modules) modules[module.name] = module.methods.map((method) => method.name)
        if (contract.defaultView) defaultViewFiles.push(name)
      }
    }
  }
  visit(packageDir)
  const packageId = swiftPackageId(packageDir)
  const rendered = renderSwiftSourceGlue(packageId, contracts)
  const descriptor = join(packageDir, '.one-native-source.json')
  const glue = join(packageDir, '.one-native-source.swift.txt')
  if (contracts.some((contract) => contract.modules.length > 0)) {
    const json = `${JSON.stringify({ generatedBy: 'one typegen', packageId, hash: rendered.hash, files, modules, defaultViewFiles }, null, 2)}\n`
    writeGeneratedFile(descriptor, json)
    writeGeneratedFile(glue, rendered.source)
  } else if (existsSync(descriptor) && readFileSync(descriptor, 'utf8').includes('"generatedBy": "one typegen"')) {
    rmSync(descriptor, { force: true })
    rmSync(glue, { force: true })
  }
  return { packageId, hash: rendered.hash, files, modules, defaultViewFiles, contracts, glue: rendered.source }
}

export function renderSwiftSourceGlue(
  packageId: string,
  contracts: NativeSourceContract[]
): { hash: string; source: string } {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(packageId)) {
    throw new Error(`invalid swift package id ${packageId}`)
  }
  const modules = contracts.flatMap((contract) => {
    if (contract.language !== 'swift') throw new Error('swift glue received a kotlin contract')
    return contract.modules
  })
  const names = new Set<string>()
  for (const module of modules) {
    if (names.has(module.name)) throw new Error(`swift package ${packageId} declares ${module.name} twice`)
    names.add(module.name)
  }
  const hash = createHash('sha256')
    .update(JSON.stringify({ packageId, modules }))
    .digest('hex')
  const hasMain = contracts.some((contract) => contract.defaultView)
  const bodyName = `OneNativeSourceBody_${packageId}`
  const className = `OneNativeSource_${packageId}`
  const renderCase = (method: NativeSourceMethod, module: NativeSourceModule): string[] => {
    const lines = [
      `      case ${JSON.stringify(method.name)}:`,
      `        guard values.count == ${method.parameters.length} else { throw NSError(domain: "OneNativeSource", code: 2, userInfo: [NSLocalizedDescriptionKey: "${packageId}.${module.name}.${method.name} expects ${method.parameters.length} arguments"]) }`,
    ]
    method.parameters.forEach((parameter, index) => {
      lines.push(`        let arg${index} = try decode(values[${index}], as: ${parameter.nativeType}.self)`)
    })
    const argumentsText = method.parameters.map((parameter, index) =>
      `${parameter.label === '_' ? '' : `${parameter.label}: `}arg${index}`
    ).join(', ')
    const prefix = `${method.throws ? 'try ' : ''}${method.async ? 'await ' : ''}`
    const call = `${module.name}Instance.${method.name}(${argumentsText})`
    if (method.result === 'void') {
      lines.push(`        ${prefix}${call}`, '        return "null"')
    } else {
      lines.push(`        let result = ${prefix}${call}`)
      if (method.nativeResult === 'Int') {
        lines.push('        guard abs(Double(result)) <= 9_007_199_254_740_991 else { throw NSError(domain: "OneNativeSource", code: 2, userInfo: [NSLocalizedDescriptionKey: "result exceeds the JavaScript safe integer range"]) }')
      }
      lines.push('        return String(decoding: try JSONEncoder().encode(result), as: UTF8.self)')
    }
    return lines
  }
  const renderCall = (): string[] => [
    '  static func call(_ module: String, _ method: String, _ argsJson: String) async throws -> String {',
    '    guard let values = try JSONSerialization.jsonObject(with: Data(argsJson.utf8)) as? [Any] else {',
    '      throw NSError(domain: "OneNativeSource", code: 2, userInfo: [NSLocalizedDescriptionKey: "arguments must be a JSON array"])',
    '    }',
    '    switch module {',
    ...modules.flatMap((module) => [
      `    case ${JSON.stringify(`${packageId}.${module.name}`)}:`,
      '      switch method {',
      ...module.methods.flatMap((method) => renderCase(method, module)),
      '      default: throw NSError(domain: "OneNativeSource", code: 1, userInfo: [NSLocalizedDescriptionKey: "native method \\(module).\\(method) is not linked; rebuild the app"])',
      '      }',
    ]),
    '    default: throw NSError(domain: "OneNativeSource", code: 1, userInfo: [NSLocalizedDescriptionKey: "native module \\(module) is not linked; rebuild the app"])',
    '    }',
    '  }',
  ]
  const source = [
    'import Foundation',
    '#if os(WASI)',
    'import SwiftUI',
    '#endif',
    '',
    `@MainActor public enum ${bodyName} {`,
    `  public static let hash = ${JSON.stringify(hash)}`,
    '#if os(WASI)',
    '  private struct Request: Decodable { let module: String; let method: String; let argsJson: String; let contractHash: String }',
    '  private struct Reply: Encodable { let ok: Bool; let value: String?; let error: String?; let pending: Int32? }',
    '  private static var output: [UInt8] = []',
    '  private static var finished: [Int32: Reply] = [:]',
    '  private static var nextCall: Int32 = 0',
    '  // peach runs tasks inline, so a call finishes before its task launch returns',
    '  // unless it waits on the clock; then it answers pending and the host polls',
    '  // it after running the timers.',
    '  static func callWasm(_ payload: UnsafePointer<UInt8>?, _ length: Int32) -> UnsafeMutablePointer<UInt8>? {',
    '    let id = nextCall',
    '    nextCall &+= 1',
    '    do {',
    '      guard let payload, length >= 0 else { throw NSError(domain: "OneNativeSource", code: 2, userInfo: [NSLocalizedDescriptionKey: "missing call payload"]) }',
    '      let request = try JSONDecoder().decode(Request.self, from: Data(bytes: payload, count: Int(length)))',
    '      guard request.contractHash == hash else { throw NSError(domain: "OneNativeSource", code: 4, userInfo: [NSLocalizedDescriptionKey: "native module \\(request.module) changed; rebuild the app"]) }',
    '      Task {',
    '        do {',
    '          finished[id] = Reply(ok: true, value: try await call(request.module, request.method, request.argsJson), error: nil, pending: nil)',
    '        } catch {',
    '          // the native hosts name the method on everything a call throws',
    '          finished[id] = Reply(ok: false, value: nil, error: "\\(request.module).\\(request.method): \\(error.localizedDescription)", pending: nil)',
    '        }',
    '      }',
    '    } catch {',
    '      finished[id] = Reply(ok: false, value: nil, error: error.localizedDescription, pending: nil)',
    '    }',
    '    return pollWasm(id)',
    '  }',
    '  static func pollWasm(_ id: Int32) -> UnsafeMutablePointer<UInt8>? {',
    '    let reply = finished.removeValue(forKey: id) ?? Reply(ok: true, value: nil, error: nil, pending: id)',
    '    let bytes = (try? JSONEncoder().encode(reply)) ?? Data("{\\"ok\\":false,\\"error\\":\\"encoding failed\\"}".utf8)',
    '    let count = UInt32(bytes.count)',
    '    output = [UInt8(count & 0xff), UInt8((count >> 8) & 0xff), UInt8((count >> 16) & 0xff), UInt8(count >> 24)] + Array(bytes)',
    '    return output.withUnsafeMutableBufferPointer { $0.baseAddress }',
    '  }',
    '#endif',
    ...modules.map((module) => `  private static let ${module.name}Instance = ${module.name}()`),
    '  private static func decode<T: Decodable>(_ value: Any, as type: T.Type) throws -> T {',
    '    let data = try JSONSerialization.data(withJSONObject: value, options: [.fragmentsAllowed])',
    '    return try JSONDecoder().decode(T.self, from: data)',
    '  }',
    ...renderCall(),
    '}',
    '',
    '#if os(WASI)',
    '@_expose(wasm, "rnx_call")',
    '@_cdecl("rnx_call")',
    `@MainActor public func rnx_call(_ payload: UnsafePointer<UInt8>?, _ length: Int32) -> UnsafeMutablePointer<UInt8>? { ${bodyName}.callWasm(payload, length) }`,
    '@_expose(wasm, "rnx_call_poll")',
    '@_cdecl("rnx_call_poll")',
    `@MainActor public func rnx_call_poll(_ id: Int32) -> UnsafeMutablePointer<UInt8>? { ${bodyName}.pollWasm(id) }`,
    ...(!hasMain ? [
      `@main struct OneNativeSourceMain_${packageId}: App {`,
      '  var body: some Scene { WindowGroup { EmptyView() } }',
      '}',
    ] : []),
    '#endif',
    '',
    '#if canImport(ObjectiveC)',
    `@objc(${className}) @MainActor public final class ${className}: NSObject, OneNativeSourceDispatch {`,
    '  public required override init() {}',
    `  public var contractHash: String { ${bodyName}.hash }`,
    `  public func call(_ module: String, _ method: String, _ argsJson: String) async throws -> String { try await ${bodyName}.call(module, method, argsJson) }`,
    '}',
    '#endif',
    '',
  ].join('\n')
  return { hash, source }
}

export function renderKotlinSourceGlue(
  sourceId: string,
  contract: NativeSourceContract
): { hash: string; source: string } {
  if (contract.language !== 'kotlin') throw new Error('kotlin glue received a swift contract')
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(sourceId)) throw new Error(`invalid kotlin source id ${sourceId}`)
  const hash = createHash('sha256').update(JSON.stringify({ sourceId, contract: contract.hash })).digest('hex')
  const value = (type: string, input: string, path: string): string => {
    if (type.endsWith('?')) {
      return `(if (${input} == JSONObject.NULL) null else ${value(type.slice(0, -1), input, path)})`
    }
    if (type === 'String') return `readString(${input}, ${path})`
    if (type === 'Boolean') return `readBoolean(${input}, ${path})`
    if (type === 'Double') return `readDouble(${input}, ${path})`
    if (type === 'Float') return `readDouble(${input}, ${path}).toFloat()`
    if (type === 'Int') return `readInt(${input}, ${path})`
    if (type === 'Long') return `readLong(${input}, ${path})`
    if (type.startsWith('List<') && type.endsWith('>')) {
      return `readList(${input}, ${path}) { item, itemPath -> ${value(type.slice(5, -1), 'item', 'itemPath')} }`
    }
    if (type.startsWith('Map<String,') && type.endsWith('>')) {
      return `readMap(${input}, ${path}) { item, itemPath -> ${value(type.slice(11, -1), 'item', 'itemPath')} }`
    }
    throw new Error(`unsupported kotlin glue type ${type}`)
  }
  const source = [
    'import androidx.annotation.Keep',
    ...(contract.views.length === 0 ? [] : ['import androidx.compose.runtime.Composable', 'import dev.onejs.one.OneNativeSourceViewDispatch']),
    'import dev.onejs.one.OneNativeSourceDispatch',
    'import org.json.JSONArray',
    'import org.json.JSONObject',
    '',
    'private fun readString(value: Any, path: String): String = value as? String ?: error("$path: expected string")',
    'private fun readBoolean(value: Any, path: String): Boolean = value as? Boolean ?: error("$path: expected boolean")',
    'private fun readDouble(value: Any, path: String): Double {',
    '  val result = (value as? Number)?.toDouble() ?: error("$path: expected number")',
    '  if (!result.isFinite()) error("$path: expected finite number")',
    '  return result',
    '}',
    'private fun readInt(value: Any, path: String): Int {',
    '  val result = readDouble(value, path)',
    '  if (result % 1.0 != 0.0 || result < Int.MIN_VALUE || result > Int.MAX_VALUE) error("$path: expected Int")',
    '  return result.toInt()',
    '}',
    'private fun readLong(value: Any, path: String): Long {',
    '  val result = readDouble(value, path)',
    '  if (result % 1.0 != 0.0 || result < -9007199254740991.0 || result > 9007199254740991.0) error("$path: expected safe Long")',
    '  return result.toLong()',
    '}',
    'private fun <T> readList(value: Any, path: String, read: (Any, String) -> T): List<T> {',
    '  val array = value as? JSONArray ?: error("$path: expected array")',
    '  return (0 until array.length()).map { index -> read(array.get(index), "$path[$index]") }',
    '}',
    'private fun <T> readMap(value: Any, path: String, read: (Any, String) -> T): Map<String, T> {',
    '  val objectValue = value as? JSONObject ?: error("$path: expected object")',
    '  return objectValue.keys().asSequence().associateWith { key -> read(objectValue.get(key), "$path.$key") }',
    '}',
    '',
    `@Keep class OneNativeSource_${sourceId}: OneNativeSourceDispatch {`,
    `  override val contractHash = ${JSON.stringify(hash)}`,
    '  override suspend fun call(module: String, method: String, argsJson: String): String {',
    '    val args = JSONArray(argsJson)',
    '    return when (module) {',
    ...contract.modules.flatMap((module) => [
      `      ${JSON.stringify(`${sourceId}.${module.name}`)} -> when (method) {`,
      ...module.methods.flatMap((method) => {
        const lines = [
          `        ${JSON.stringify(method.name)} -> {`,
          `          require(args.length() == ${method.parameters.length}) { "${sourceId}.${module.name}.${method.name} expects ${method.parameters.length} arguments" }`,
        ]
        method.parameters.forEach((parameter, index) => {
          lines.push(`          val arg${index} = ${value(parameter.nativeType, `args.get(${index})`, JSON.stringify(`args[${index}]`))}`)
        })
        const qualifier = contract.packageName ? `${contract.packageName}.` : ''
        const call = `${qualifier}${module.name}.${method.name}(${method.parameters.map((_, index) => `arg${index}`).join(', ')})`
        if (method.result === 'void') {
          lines.push(`          ${call}`, '          "null"')
        } else {
          lines.push(`          val result = ${call}`)
          if (method.nativeResult === 'Long') {
            lines.push('          require(result >= -9007199254740991L && result <= 9007199254740991L) { "result exceeds the JavaScript safe integer range" }')
          }
          lines.push('          JSONArray().put(JSONObject.wrap(result)).toString().drop(1).dropLast(1)')
        }
        return [...lines, '        }']
      }),
      '        else -> error("native method $module.$method is not linked; rebuild the app")',
      '      }',
    ]),
    '      else -> error("native module $module is not linked; rebuild the app")',
    '    }',
    '  }',
    '}',
    '',
    ...(contract.views.length === 0 ? [] : viewGlue(sourceId, contract, hash, value)),
  ].join('\n')
  return { hash, source }
}

// renders an imported composable from the host's json props; a callback
// parameter reports its arguments to the host as a json array.
function viewGlue(
  sourceId: string,
  contract: NativeSourceContract,
  hash: string,
  value: (type: string, input: string, path: string) => string
): string[] {
  const qualifier = contract.packageName ? `${contract.packageName}.` : ''
  return [
    `@Keep class OneNativeSourceViews_${sourceId}: OneNativeSourceViewDispatch {`,
    `  override val contractHash = ${JSON.stringify(hash)}`,
    '  @Composable',
    '  override fun Content(view: String, propsJson: String, emit: (String, String) -> Unit) {',
    '    val props = JSONObject(propsJson)',
    '    when (view) {',
    ...contract.views.flatMap((view) => [
      `      ${JSON.stringify(view.name)} -> ${qualifier}${view.name}(`,
      ...view.props.map((prop) => {
        const path = JSON.stringify(`props.${prop.name}`)
        if (prop.callback) {
          const args = prop.callback.map((_, index) => `a${index}`)
          const body = `emit(${JSON.stringify(prop.name)}, JSONArray()${args.map((arg) => `.put(JSONObject.wrap(${arg}))`).join('')}.toString())`
          const lambda = `{ ${args.length > 0 ? `${args.join(', ')} -> ` : ''}${body} }`
          // the host sends true for each callback the element passed
          return `        ${prop.name} = ${prop.nativeType.endsWith('?') ? `if (props.optBoolean(${JSON.stringify(prop.name)})) (${lambda}) else null` : lambda},`
        }
        const input = prop.optional
          ? `(props.opt(${JSON.stringify(prop.name)}) ?: JSONObject.NULL)`
          : `(props.opt(${JSON.stringify(prop.name)}) ?: error(${JSON.stringify(`props.${prop.name}: required`)}))`
        return `        ${prop.name} = ${value(prop.nativeType, input, path)},`
      }),
      '      )',
    ]),
    '      else -> error("composable $view is not linked; rebuild the app")',
    '    }',
    '  }',
    '}',
    '',
  ]
}
