import { createHash } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'

export interface NativeSourceMethod {
  name: string
  parameters: { name: string; label: string | null; type: string; nativeType: string }[]
  result: string
  nativeResult: string
  throws: boolean
  async: boolean
}

export interface NativeSourceModule {
  name: string
  methods: NativeSourceMethod[]
}

export interface NativeSourceContract {
  language: 'swift' | 'kotlin'
  modules: NativeSourceModule[]
  defaultView: boolean
  hash: string
  declaration: string
}

const GENERATED_HEADER = '// generated by one typegen; edits will be replaced\n'
const SKIP_SOURCE_DIRS = new Set(['node_modules', 'ios', 'android', 'dist', 'types', 'build', '.build'])

interface Token {
  text: string
  line: number
  column: number
}

function fail(file: string, token: Token | undefined, message: string): never {
  throw new Error(`${file}:${(token?.line ?? 0) + 1}:${(token?.column ?? 0) + 1}: ${message}`)
}

// only declarations are read. strings and comments cannot supply a marker,
// method, brace, or type; native compilers validate every emitted call.
function tokens(file: string, source: string): Token[] {
  const result: Token[] = []
  let offset = 0
  let line = 0
  let column = 0
  const advance = () => {
    if (source[offset] === '\n') { line++; column = 0 }
    else column++
    offset++
  }
  while (offset < source.length) {
    const char = source[offset]
    if (/\s/.test(char)) { advance(); continue }
    if (source.startsWith('//', offset)) {
      while (offset < source.length && source[offset] !== '\n') advance()
      continue
    }
    if (source.startsWith('/*', offset)) {
      let depth = 0
      do {
        if (source.startsWith('/*', offset)) { depth++; advance(); advance() }
        else if (source.startsWith('*/', offset)) { depth--; advance(); advance() }
        else advance()
      } while (depth > 0 && offset < source.length)
      if (depth > 0) fail(file, { text: '/*', line, column }, 'unclosed native source comment')
      continue
    }
    if (char === '"' || char === "'") {
      const quote = source.startsWith(char.repeat(3), offset) ? char.repeat(3) : char
      for (let n = 0; n < quote.length; n++) advance()
      while (offset < source.length && !source.startsWith(quote, offset)) {
        if (source[offset] === '\\') advance()
        advance()
      }
      if (offset >= source.length) fail(file, { text: quote, line, column }, 'unclosed native source string')
      for (let n = 0; n < quote.length; n++) advance()
      continue
    }
    const start = offset
    const startLine = line
    const startColumn = column
    if (/[A-Za-z_]/.test(char)) {
      while (offset < source.length && /[A-Za-z0-9_]/.test(source[offset])) advance()
    } else if (source.startsWith('->', offset)) {
      advance(); advance()
    } else advance()
    result.push({ text: source.slice(start, offset), line: startLine, column: startColumn })
  }
  return result
}

function close(file: string, list: Token[], start: number, left: string, right: string): number {
  let depth = 0
  for (let i = start; i < list.length; i++) {
    if (list[i].text === left) depth++
    if (list[i].text === right && --depth === 0) return i
  }
  fail(file, list[start], `unclosed ${left} in native export`)
}

function split(list: Token[], separator: string): Token[][] {
  const parts: Token[][] = []
  let start = 0
  let square = 0
  let angle = 0
  let round = 0
  for (let i = 0; i < list.length; i++) {
    const value = list[i].text
    if (value === '[') square++
    if (value === ']') square--
    if (value === '<') angle++
    if (value === '>') angle--
    if (value === '(') round++
    if (value === ')') round--
    if (value === separator && square === 0 && angle === 0 && round === 0) {
      parts.push(list.slice(start, i))
      start = i + 1
    }
  }
  parts.push(list.slice(start))
  return parts
}

function tsType(file: string, list: Token[], language: 'swift' | 'kotlin'): string {
  if (list.length === 0) fail(file, list[0], 'native export needs an explicit type')
  if (list.at(-1)?.text === '?') return `${tsType(file, list.slice(0, -1), language)} | null`
  const value = list.map((token) => token.text).join('')
  if (value === 'String') return 'string'
  if (value === 'Bool' || value === 'Boolean') return 'boolean'
  if (['Double', 'Float', 'Int', 'Long'].includes(value)) return 'number'
  if (value === 'Void' || value === 'Unit') return 'void'
  if (language === 'swift' && list[0].text === '[' && list.at(-1)?.text === ']') {
    const inner = list.slice(1, -1)
    const entries = split(inner, ':')
    if (entries.length === 1) return `${tsType(file, inner, language)}[]`
    if (entries.length === 2 && entries[0].map((token) => token.text).join('') === 'String') {
      return `Record<string, ${tsType(file, entries[1], language)}>`
    }
  }
  if (language === 'kotlin' && list[1]?.text === '<' && list.at(-1)?.text === '>') {
    const entries = split(list.slice(2, -1), ',')
    if (list[0].text === 'List' && entries.length === 1) return `${tsType(file, entries[0], language)}[]`
    if (list[0].text === 'Map' && entries.length === 2 && entries[0].map((token) => token.text).join('') === 'String') {
      return `Record<string, ${tsType(file, entries[1], language)}>`
    }
  }
  fail(file, list[0], `unsupported native export type ${value}`)
}

function parameters(file: string, list: Token[], language: 'swift' | 'kotlin'): NativeSourceMethod['parameters'] {
  if (list.length === 0) return []
  return split(list, ',').map((part, index) => {
    if (part.some((token) => token.text === '=')) fail(file, part[0], 'default native export arguments are unsupported')
    const colon = part.findIndex((token) => token.text === ':')
    if (colon < 0) fail(file, part[0], 'native export parameter needs an explicit type')
    const names = part.slice(0, colon).filter((token) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(token.text))
    const name = (language === 'swift' ? names.at(-1) : names[0])?.text ?? `arg${index}`
    if (name === '_') fail(file, part[0], 'native export parameter needs an internal name')
    const label = language === 'swift' ? names[0]?.text ?? name : null
    const sourceType = part.slice(colon + 1)
    return { name, label, type: tsType(file, sourceType, language), nativeType: sourceType.map((token) => token.text).join('') }
  })
}

function methods(file: string, list: Token[], start: number, end: number, language: 'swift' | 'kotlin'): NativeSourceMethod[] {
  const result: NativeSourceMethod[] = []
  let i = start + 1
  let previous = i
  const keyword = language === 'swift' ? 'func' : 'fun'
  while (i < end) {
    if (list[i].text === '{') { i = close(file, list, i, '{', '}') + 1; previous = i; continue }
    if (list[i].text !== keyword) { i++; continue }
    const modifiers = list.slice(previous, i).map((token) => token.text)
    const hidden = modifiers.includes('private') || modifiers.includes('fileprivate')
    if (!hidden && (modifiers.includes('static') || modifiers.includes('class'))) {
      fail(file, list[i], 'static native exports are unsupported')
    }
    const name = list[i + 1]?.text
    if (!name || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) fail(file, list[i], 'native export has no method name')
    if (result.some((method) => method.name === name)) fail(file, list[i], `overloaded native export ${name} is unsupported`)
    if (list[i + 2]?.text === '<') fail(file, list[i], 'generic native exports are unsupported')
    const open = i + 2
    if (list[open]?.text !== '(') fail(file, list[i], 'native export has no parameter list')
    const closing = close(file, list, open, '(', ')')
    const args = hidden ? [] : parameters(file, list.slice(open + 1, closing), language)
    let headerEnd = closing + 1
    while (headerEnd < end && !['{', '=', ';'].includes(list[headerEnd].text)) headerEnd++
    const header = list.slice(closing + 1, headerEnd)
    const separator = header.findIndex((token) => token.text === (language === 'swift' ? '->' : ':'))
    const sourceType = hidden || separator < 0 ? [] : header.slice(separator + 1)
    const type = sourceType.length === 0 ? 'void' : tsType(file, sourceType, language)
    if (!hidden) {
      result.push({
        name,
        parameters: args,
        result: type,
        nativeResult: sourceType.length === 0 ? language === 'swift' ? 'Void' : 'Unit' : sourceType.map((token) => token.text).join(''),
        throws: language === 'swift' ? header.some((token) => token.text === 'throws') : true,
        async: language === 'swift' ? header.some((token) => token.text === 'async') : modifiers.includes('suspend'),
      })
    }
    if (list[headerEnd]?.text === '{') i = close(file, list, headerEnd, '{', '}') + 1
    else if (list[headerEnd]?.text === '=') {
      const bodyLine = list[headerEnd].line
      i = headerEnd + 1
      while (i < end && list[i].line === bodyLine && list[i].text !== ';') i++
    } else i = headerEnd + 1
    previous = i
  }
  return result
}

export function nativeSourceContract(file: string, source: string): NativeSourceContract {
  const language = file.endsWith('.swift') ? 'swift' : file.endsWith('.kt') ? 'kotlin' : undefined
  if (!language) throw new Error(`${file}: expected a .swift or .kt source file`)
  const list = tokens(file, source)
  const modules: NativeSourceModule[] = []
  let defaultView = false
  let i = 0
  let previous = 0
  while (i < list.length) {
    const kind = list[i].text
    const declaration = language === 'swift' ? kind === 'class' || kind === 'struct' : kind === 'object'
    if (!declaration) {
      if (kind === '{') { i = close(file, list, i, '{', '}') + 1; previous = i }
      else i++
      continue
    }
    const name = list[i + 1]?.text
    if (!name) fail(file, list[i], 'native type has no name')
    let body = i + 2
    while (body < list.length && list[body].text !== '{') body++
    if (body === list.length) fail(file, list[i], 'native type has no body')
    const end = close(file, list, body, '{', '}')
    const prefix = list.slice(previous, i).map((token) => token.text)
    if (language === 'swift' && prefix.some((value, index) => value === '@' && prefix[index + 1] === 'main')) {
      defaultView = true
    }
    const inherits = list.slice(i + 2, body).map((token) => token.text)
    if (inherits.includes(language === 'swift' ? 'RNXModule' : 'OneModule')) {
      modules.push({ name, methods: methods(file, list, body, end, language) })
    }
    i = end + 1
    previous = i
  }
  const canonical = JSON.stringify({ language, modules, defaultView })
  const hash = createHash('sha256').update(canonical).digest('hex')
  const declarations = modules.map((module) => [
    `export declare const ${module.name}: {`,
    ...module.methods.map((method) =>
      `  ${method.name}(${method.parameters.map((param) => `${param.name}: ${param.type}`).join(', ')}): Promise<${method.result}>`
    ),
    '}',
  ].join('\n'))
  if (defaultView) {
    declarations.unshift("import type { ReactElement } from 'react'\nexport default function SwiftPackage(props: Record<string, unknown>): ReactElement")
  }
  const declaration = `${GENERATED_HEADER}${declarations.join('\n\n')}\n`
  return { language, modules, defaultView, hash, declaration }
}

export function writeNativeSourceDeclaration(file: string): NativeSourceContract {
  const contract = nativeSourceContract(file, readFileSync(file, 'utf8'))
  const extension = contract.language === 'swift' ? '.swift' : '.kt'
  const declaration = join(dirname(file), `${basename(file, extension)}.d${extension}.ts`)
  if (contract.modules.length === 0 && !contract.defaultView) {
    if (existsSync(declaration) && readFileSync(declaration, 'utf8').startsWith(GENERATED_HEADER)) {
      unlinkSync(declaration)
    }
    return contract
  }
  if (!existsSync(declaration) || readFileSync(declaration, 'utf8') !== contract.declaration) {
    writeFileSync(declaration, contract.declaration)
  }
  return contract
}

export function writeNativeSourceDeclarations(root: string): NativeSourceContract[] {
  const contracts: NativeSourceContract[] = []
  const visit = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || SKIP_SOURCE_DIRS.has(entry.name)) continue
      const file = join(dir, entry.name)
      if (entry.isDirectory()) visit(file)
      else if (entry.isFile() && /\.(swift|kt)$/.test(entry.name) && entry.name !== 'Package.swift') {
        contracts.push(writeNativeSourceDeclaration(file))
      }
    }
  }
  visit(root)
  return contracts
}
